name: mental
description: MENTAL — cliente Flutter (Vertical Slice 01)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  http: ^1.2.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.2.1
  audioplayers: ^6.8.1
  confetti: ^0.8.0
  sound_mode_advanced: ^4.0.0
  fl_chart: ^1.2.0
  pedometer: ^4.2.0
  permission_handler: ^12.0.3
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
