-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote3.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Formerly$q$, $q$outrora$q$, $q$This building was formerly a train station.$q$, $q$Este prédio era outrora uma estação de trem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Henceforth$q$, $q$doravante$q$, $q$Henceforth, all reports must be submitted online.$q$, $q$Doravante, todos os relatórios devem ser enviados online.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Simultaneously$q$, $q$simultaneamente$q$, $q$She manages three projects simultaneously.$q$, $q$Ela administra três projetos simultaneamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subsequently$q$, $q$subsequentemente$q$, $q$The company hired her and subsequently promoted her.$q$, $q$A empresa a contratou e subsequentemente a promoveu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Previously$q$, $q$previamente$q$, $q$He worked previously as a translator.$q$, $q$Ele trabalhou previamente como tradutor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Eventually$q$, $q$eventualmente$q$, $q$She eventually finds a solution to the problem.$q$, $q$Ela eventualmente encontra uma solução para o problema.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Perpetually$q$, $q$perpetuamente$q$, $q$The city seems perpetually under construction.$q$, $q$A cidade parece perpetuamente em obras.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Occasionally$q$, $q$ocasionalmente$q$, $q$I occasionally work from home on Fridays.$q$, $q$Eu ocasionalmente trabalho de casa nas sextas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Briefly$q$, $q$brevemente$q$, $q$She briefly explains the new policy before the meeting.$q$, $q$Ela explica brevemente a nova política antes da reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Incessantly$q$, $q$incessantemente$q$, $q$The dog barks incessantly during the storm.$q$, $q$O cachorro late incessantemente durante a tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deliberately$q$, $q$deliberadamente$q$, $q$He deliberately avoids the topic during dinner.$q$, $q$Ele deliberadamente evita o assunto durante o jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stealthily$q$, $q$sorrateiramente$q$, $q$The cat moves stealthily toward the bird.$q$, $q$O gato se move sorrateiramente em direção ao pássaro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vehemently$q$, $q$veementemente$q$, $q$She vehemently denies the accusation.$q$, $q$Ela nega a acusação veementemente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inadvertently$q$, $q$inadvertidamente$q$, $q$I inadvertently delete the entire file.$q$, $q$Eu inadvertidamente apago o arquivo inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reluctantly$q$, $q$relutantemente$q$, $q$He reluctantly agrees to attend the meeting.$q$, $q$Ele relutantemente concorda em comparecer à reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fervently$q$, $q$fervorosamente$q$, $q$She fervently believes in the cause.$q$, $q$Ela acredita fervorosamente na causa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subtly$q$, $q$sutilmente$q$, $q$The design subtly hints at the brand's history.$q$, $q$O design sugere sutilmente a história da marca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Overtly$q$, $q$abertamente$q$, $q$He overtly criticizes the new policy in the meeting.$q$, $q$Ele critica a nova política abertamente na reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Shrewdly$q$, $q$astutamente$q$, $q$She shrewdly negotiates a better contract.$q$, $q$Ela negocia astutamente um contrato melhor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Resolutely$q$, $q$resolutamente$q$, $q$He resolutely pursues his goal despite the setbacks.$q$, $q$Ele persegue o objetivo dele resolutamente apesar dos contratempos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Furthermore$q$, $q$outrossim$q$, $q$The plan is risky; furthermore, it costs too much.$q$, $q$O plano é arriscado; além disso, custa caro demais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thus$q$, $q$destarte$q$, $q$The bridge collapses; thus, traffic is rerouted.$q$, $q$A ponte desaba; assim, o trânsito é desviado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Besides$q$, $q$ademais$q$, $q$I don't like the color; besides, it is too expensive.$q$, $q$Eu não gosto da cor; ademais, é caro demais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Notwithstanding$q$, $q$não obstante$q$, $q$Notwithstanding the risks, she accepts the new position.$q$, $q$Não obstante os riscos, ela aceita a nova posição.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Consequently$q$, $q$por conseguinte$q$, $q$Sales dropped; consequently, the company cuts costs.$q$, $q$As vendas caíram; por conseguinte, a empresa corta custos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Namely$q$, $q$a saber$q$, $q$Two countries, namely France and Spain, sign the deal.$q$, $q$Dois países, a saber, França e Espanha, assinam o acordo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Overall$q$, $q$em suma$q$, $q$Overall, the project meets its main objectives.$q$, $q$No geral, o projeto atinge seus principais objetivos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Alike$q$, $q$assim como$q$, $q$The two proposals are alike in structure but not in cost.$q$, $q$As duas propostas são parecidas na estrutura, mas não no custo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Yet$q$, $q$todavia$q$, $q$The plan is bold, yet it may fail completely.$q$, $q$O plano é ousado, todavia pode fracassar completamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chiefly$q$, $q$mormente$q$, $q$The delay is chiefly due to bad weather.$q$, $q$O atraso se deve principalmente ao mau tempo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Adversity$q$, $q$adversidade$q$, $q$She shows great strength in the face of adversity.$q$, $q$Ela mostra grande força diante da adversidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prosperity$q$, $q$prosperidade$q$, $q$The region enjoys decades of prosperity.$q$, $q$A região desfruta de décadas de prosperidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Turmoil$q$, $q$tumulto$q$, $q$The country falls into political turmoil.$q$, $q$O país cai num tumulto político.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Abundance$q$, $q$abundância$q$, $q$The valley produces fruit in great abundance.$q$, $q$O vale produz fruta em grande abundância.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Decline$q$, $q$declínio$q$, $q$The industry suffers a steady decline in profits.$q$, $q$A indústria sofre um declínio constante nos lucros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Collapse$q$, $q$colapso$q$, $q$The old bridge suffers a sudden collapse.$q$, $q$A ponte antiga sofre um colapso repentino.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Trace$q$, $q$vestígio$q$, $q$Investigators find no trace of the missing documents.$q$, $q$Os investigadores não encontram vestígio dos documentos desaparecidos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Threshold$q$, $q$limiar$q$, $q$The company crosses an important growth threshold.$q$, $q$A empresa cruza um limiar importante de crescimento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Equilibrium$q$, $q$equilíbrio$q$, $q$The market slowly returns to equilibrium.$q$, $q$O mercado retorna lentamente ao equilíbrio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deadlock$q$, $q$impasse$q$, $q$The negotiations reach a complete deadlock.$q$, $q$As negociações chegam a um impasse completo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Adversary$q$, $q$adversário$q$, $q$He treats his political adversary with respect.$q$, $q$Ele trata o adversário político dele com respeito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Apprentice$q$, $q$aprendiz$q$, $q$The young apprentice learns from the master carpenter.$q$, $q$O jovem aprendiz aprende com o mestre carpinteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Retiree$q$, $q$aposentado$q$, $q$The retiree spends his mornings gardening.$q$, $q$O aposentado passa as manhãs dele jardinando.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pioneer$q$, $q$pioneiro$q$, $q$She is a pioneer in renewable energy research.$q$, $q$Ela é uma pioneira na pesquisa de energia renovável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Defector$q$, $q$desertor$q$, $q$The defector reveals classified information.$q$, $q$O desertor revela informações confidenciais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mediator$q$, $q$mediador$q$, $q$A neutral mediator helps resolve the dispute.$q$, $q$Um mediador neutro ajuda a resolver a disputa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Benefactor$q$, $q$benfeitor$q$, $q$An anonymous benefactor funds the new library.$q$, $q$Um benfeitor anônimo financia a nova biblioteca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Intruder$q$, $q$intruso$q$, $q$The alarm goes off when an intruder enters the house.$q$, $q$O alarme dispara quando um intruso entra na casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fugitive$q$, $q$fugitivo$q$, $q$Police finally capture the fugitive after two years.$q$, $q$A polícia finalmente captura o fugitivo depois de dois anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bystander$q$, $q$espectador casual$q$, $q$A bystander calls for help during the accident.$q$, $q$Um espectador casual pede ajuda durante o acidente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Biome$q$, $q$bioma$q$, $q$The rainforest is a rich biome full of life.$q$, $q$A floresta tropical é um bioma rico e cheio de vida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Estuary$q$, $q$estuário$q$, $q$Many fish species breed in the estuary.$q$, $q$Muitas espécies de peixes se reproduzem no estuário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ravine$q$, $q$ravina$q$, $q$The trail crosses a deep ravine.$q$, $q$A trilha atravessa uma ravina profunda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Plateau$q$, $q$planalto$q$, $q$The city sits on a high plateau.$q$, $q$A cidade fica num planalto alto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dune$q$, $q$duna$q$, $q$Children slide down the tall sand dune.$q$, $q$As crianças deslizam pela duna alta de areia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gorge$q$, $q$desfiladeiro estreito$q$, $q$The river carves a narrow gorge through the rock.$q$, $q$O rio esculpe um desfiladeiro estreito pela rocha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cove$q$, $q$enseada$q$, $q$They anchor the boat in a quiet cove.$q$, $q$Eles ancoram o barco numa enseada tranquila.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Marsh$q$, $q$charco$q$, $q$Birds nest in the reeds of the marsh.$q$, $q$Pássaros fazem ninho nos juncos do charco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Boulder$q$, $q$penedo$q$, $q$A huge boulder blocks the mountain path.$q$, $q$Um penedo enorme bloqueia a trilha da montanha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Savanna$q$, $q$savana$q$, $q$Lions roam freely across the open savanna.$q$, $q$Leões vagam livremente pela savana aberta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Barn$q$, $q$celeiro$q$, $q$The farmer keeps the tractor in the barn.$q$, $q$O fazendeiro guarda o trator no celeiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Corral$q$, $q$curral$q$, $q$The cowboys herd the cattle into the corral.$q$, $q$Os vaqueiros conduzem o gado para o curral.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Plow$q$, $q$arado$q$, $q$The old plow rests against the barn wall.$q$, $q$O arado velho fica encostado na parede do celeiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stable$q$, $q$estábulo$q$, $q$She brushes the horse in the stable.$q$, $q$Ela escova o cavalo no estábulo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scarecrow$q$, $q$espantalho$q$, $q$A scarecrow stands guard over the cornfield.$q$, $q$Um espantalho vigia a plantação de milho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Orchard$q$, $q$pomar$q$, $q$We pick apples in my grandfather's orchard.$q$, $q$Nós colhemos maçãs no pomar do meu avô.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vineyard$q$, $q$vinhedo$q$, $q$The family owns a small vineyard in the hills.$q$, $q$A família tem um vinhedo pequeno nas colinas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mill$q$, $q$moinho$q$, $q$The old mill still grinds wheat every autumn.$q$, $q$O moinho antigo ainda mói trigo todo outono.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pasture$q$, $q$pasto$q$, $q$The cows graze peacefully in the pasture.$q$, $q$As vacas pastam tranquilamente no pasto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Trough$q$, $q$cocho$q$, $q$The pigs eat from a wooden trough.$q$, $q$Os porcos comem de um cocho de madeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Truce$q$, $q$trégua$q$, $q$Both sides agree to a temporary truce.$q$, $q$Os dois lados concordam com uma trégua temporária.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Siege$q$, $q$cerco militar$q$, $q$The city endures a long siege before surrendering.$q$, $q$A cidade suporta um longo cerco antes de se render.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fortress$q$, $q$fortaleza$q$, $q$The ancient fortress overlooks the valley.$q$, $q$A fortaleza antiga domina o vale.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ambush$q$, $q$emboscada$q$, $q$The soldiers fall into a well-planned ambush.$q$, $q$Os soldados caem numa emboscada bem planejada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Armistice$q$, $q$armistício$q$, $q$The two nations sign an armistice after years of war.$q$, $q$As duas nações assinam um armistício depois de anos de guerra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mercenary$q$, $q$mercenário$q$, $q$The mercenary fights for whoever pays the most.$q$, $q$O mercenário luta para quem pagar mais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Refugee$q$, $q$refugiado$q$, $q$The refugee finally finds a safe place to live.$q$, $q$O refugiado finalmente encontra um lugar seguro para viver.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Army$q$, $q$exército$q$, $q$The army retreats before the harsh winter.$q$, $q$O exército recua antes do inverno rigoroso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Battle$q$, $q$batalha$q$, $q$The two armies meet for a decisive battle.$q$, $q$Os dois exércitos se encontram para uma batalha decisiva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Strategy$q$, $q$estratégia$q$, $q$The coach designs a new strategy for the final.$q$, $q$O treinador cria uma nova estratégia para a final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sear$q$, $q$selar carne$q$, $q$I sear the steak for two minutes on each side.$q$, $q$Eu selo o bife por dois minutos de cada lado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blanch$q$, $q$branquear legumes$q$, $q$I blanch the vegetables before freezing them.$q$, $q$Eu branqueio os legumes antes de congelá-los.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Caramelize$q$, $q$caramelizar$q$, $q$I caramelize the onions slowly in the pan.$q$, $q$Eu caramelizo as cebolas devagar na frigideira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Garnish$q$, $q$guarnição$q$, $q$I add a garnish of fresh herbs to the dish.$q$, $q$Eu acrescento uma guarnição de ervas frescas ao prato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Infusion$q$, $q$infusão$q$, $q$I prepare a warm infusion of ginger and lemon.$q$, $q$Eu preparo uma infusão quente de gengibre e limão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Curdle$q$, $q$talhar leite$q$, $q$The milk starts to curdle in the hot pan.$q$, $q$O leite começa a talhar na frigideira quente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Grind$q$, $q$moer$q$, $q$I grind the coffee beans every morning.$q$, $q$Eu moo os grãos de café toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Strain$q$, $q$coar$q$, $q$I strain the pasta before adding the sauce.$q$, $q$Eu coo a massa antes de adicionar o molho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Roast$q$, $q$tostar$q$, $q$I roast the nuts until they turn golden.$q$, $q$Eu tosto as castanhas até ficarem douradas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Delicacy$q$, $q$iguaria$q$, $q$Truffle risotto is considered a rare delicacy.$q$, $q$Risoto de trufa é considerado uma iguaria rara.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mourn$q$, $q$prantear$q$, $q$I mourn the loss of my grandfather deeply.$q$, $q$Eu pranteio profundamente a perda do meu avô.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rejoice$q$, $q$regozijar-se$q$, $q$The fans rejoice after the final whistle.$q$, $q$Os torcedores se regozijam depois do apito final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Terrify$q$, $q$aterrorizar$q$, $q$Loud thunder tends to terrify my dog.$q$, $q$Trovão alto tende a aterrorizar meu cachorro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Infuriate$q$, $q$enfurecer$q$, $q$Careless remarks like that infuriate me.$q$, $q$Comentários descuidados assim me enfurecem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Enchant$q$, $q$encantar$q$, $q$This old castle never fails to enchant me.$q$, $q$Este castelo antigo nunca deixa de me encantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Humiliate$q$, $q$humilhar$q$, $q$He refuses to humiliate his opponent in public.$q$, $q$Ele se recusa a humilhar o adversário dele em público.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fascinate$q$, $q$fascinar$q$, $q$The documentary continues to fascinate viewers.$q$, $q$O documentário continua a fascinar os espectadores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bore$q$, $q$entediar$q$, $q$The long lecture starts to bore the students.$q$, $q$A palestra longa começa a entediar os alunos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cherish$q$, $q$estimar com carinho$q$, $q$I cherish the memories of our trip together.$q$, $q$Eu estimo com carinho as memórias da nossa viagem juntos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Loathe$q$, $q$detestar$q$, $q$I loathe waiting in long lines at the bank.$q$, $q$Eu detesto esperar em filas longas no banco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
