-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote4.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Acquire$q$, $q$adquirir$q$, $q$The company plans to acquire a smaller rival.$q$, $q$A empresa planeja adquirir uma rival menor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Eliminate$q$, $q$eliminar$q$, $q$The new process aims to eliminate unnecessary steps.$q$, $q$O novo processo visa eliminar etapas desnecessárias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Proceed$q$, $q$prosseguir$q$, $q$We proceed with the plan despite the risks.$q$, $q$Nós prosseguimos com o plano apesar dos riscos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prevail$q$, $q$prevalecer$q$, $q$I hope common sense will prevail in the debate.$q$, $q$Eu espero que o bom senso prevaleça no debate.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Compensate$q$, $q$compensar$q$, $q$The airline agrees to compensate passengers for the delay.$q$, $q$A companhia aérea concorda em compensar os passageiros pelo atraso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Consolidate$q$, $q$consolidar$q$, $q$The bank decides to consolidate its regional branches.$q$, $q$O banco decide consolidar as agências regionais dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mobilize$q$, $q$mobilizar$q$, $q$Volunteers mobilize quickly after the earthquake.$q$, $q$Voluntários se mobilizam rapidamente depois do terremoto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Neutralize$q$, $q$neutralizar$q$, $q$The vaccine helps neutralize the virus effectively.$q$, $q$A vacina ajuda a neutralizar o vírus com eficácia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Obstruct$q$, $q$obstruir$q$, $q$Fallen trees obstruct the main road after the storm.$q$, $q$Árvores caídas obstruem a estrada principal depois da tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Perpetrate$q$, $q$perpetrar$q$, $q$Nobody wants to perpetrate a fraud like that.$q$, $q$Ninguém quer perpetrar uma fraude assim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Initiative$q$, $q$iniciativa$q$, $q$She takes the initiative to organize the event.$q$, $q$Ela toma a iniciativa de organizar o evento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hierarchy$q$, $q$hierarquia$q$, $q$The company follows a strict hierarchy of command.$q$, $q$A empresa segue uma hierarquia rígida de comando.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ideology$q$, $q$ideologia$q$, $q$The two parties differ sharply in ideology.$q$, $q$Os dois partidos diferem fortemente em ideologia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subterfuge$q$, $q$subterfúgio$q$, $q$He avoids the truth through clever subterfuge.$q$, $q$Ele evita a verdade através de um subterfúgio esperto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Consensus$q$, $q$consenso$q$, $q$The team reaches consensus after a long discussion.$q$, $q$A equipe chega a um consenso depois de uma longa discussão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Jurisdiction$q$, $q$jurisdição$q$, $q$This case falls outside the court's jurisdiction.$q$, $q$Este caso está fora da jurisdição do tribunal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Legacy$q$, $q$legado$q$, $q$His legacy lives on through the scholarship fund.$q$, $q$O legado dele continua vivo através do fundo de bolsas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Regression$q$, $q$retrocesso$q$, $q$The economy shows signs of regression this quarter.$q$, $q$A economia mostra sinais de retrocesso neste trimestre.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Obstacle$q$, $q$obstáculo$q$, $q$Lack of funding remains the biggest obstacle.$q$, $q$Falta de financiamento continua sendo o maior obstáculo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Premise$q$, $q$premissa$q$, $q$The argument rests on a flawed premise.$q$, $q$O argumento se apoia numa premissa falha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inevitable$q$, $q$inevitável$q$, $q$A price increase seems inevitable this year.$q$, $q$Um aumento de preço parece inevitável este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Substantial$q$, $q$substancial$q$, $q$They make substantial progress on the project.$q$, $q$Eles fazem um progresso substancial no projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Plausible$q$, $q$plausível$q$, $q$Her explanation sounds plausible under the circumstances.$q$, $q$A explicação dela soa plausível diante das circunstâncias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inherent$q$, $q$inerente$q$, $q$Every job carries an inherent level of risk.$q$, $q$Todo emprego carrega um nível inerente de risco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Volatile$q$, $q$volátil$q$, $q$The stock market remains volatile this week.$q$, $q$O mercado de ações permanece volátil esta semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tangible$q$, $q$tangível$q$, $q$The training program shows tangible results already.$q$, $q$O programa de treinamento já mostra resultados tangíveis.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Comprehensive$q$, $q$abrangente$q$, $q$The report offers a comprehensive analysis of the market.$q$, $q$O relatório oferece uma análise abrangente do mercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Superfluous$q$, $q$supérfluo$q$, $q$Most of the details in the report seem superfluous.$q$, $q$A maioria dos detalhes no relatório parece supérflua.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Random$q$, $q$aleatório$q$, $q$The winners are chosen at random from the list.$q$, $q$Os vencedores são escolhidos de forma aleatória na lista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dispensable$q$, $q$dispensável$q$, $q$In a crisis, luxury items become dispensable.$q$, $q$Numa crise, itens de luxo se tornam dispensáveis.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Agenda$q$, $q$pauta de reunião$q$, $q$The manager sends the agenda before the meeting.$q$, $q$O gerente envia a pauta antes da reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Minutes$q$, $q$ata de reunião$q$, $q$She takes the minutes during every board meeting.$q$, $q$Ela redige a ata durante toda reunião do conselho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Quorum$q$, $q$quórum$q$, $q$The committee fails to reach a quorum today.$q$, $q$O comitê não consegue atingir o quórum hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Motion$q$, $q$moção$q$, $q$He proposes a motion to postpone the vote.$q$, $q$Ele propõe uma moção para adiar a votação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Proxy$q$, $q$procuração$q$, $q$She votes by proxy since she cannot attend.$q$, $q$Ela vota por procuração já que não pode comparecer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mandate$q$, $q$mandato$q$, $q$The new manager receives a clear mandate for reform.$q$, $q$O novo gerente recebe um mandato claro para reformas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deliverable$q$, $q$entregável de projeto$q$, $q$The final deliverable is due next Friday.$q$, $q$O entregável final tem prazo para a próxima sexta-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stakeholder$q$, $q$parte interessada$q$, $q$Every stakeholder receives a copy of the report.$q$, $q$Toda parte interessada recebe uma cópia do relatório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Baseline$q$, $q$linha de base$q$, $q$We compare the new data to the original baseline.$q$, $q$Nós comparamos os dados novos com a linha de base original.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bottleneck$q$, $q$gargalo$q$, $q$Slow approval creates a major bottleneck in production.$q$, $q$A aprovação lenta cria um gargalo importante na produção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Differentiate$q$, $q$diferenciar$q$, $q$It is hard to differentiate the two similar products.$q$, $q$É difícil diferenciar os dois produtos parecidos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Contemplate$q$, $q$cogitar$q$, $q$She sits quietly to contemplate her next move.$q$, $q$Ela fica sentada em silêncio para cogitar o próximo passo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Presume$q$, $q$presumir$q$, $q$I presume the meeting will start on time.$q$, $q$Eu presumo que a reunião vai começar no horário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Acknowledge$q$, $q$reconhecer o erro$q$, $q$I finally acknowledge my mistake to the team.$q$, $q$Eu finalmente reconheço meu erro para a equipe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Unravel$q$, $q$desvendar$q$, $q$I slowly unravel the mystery behind the letter.$q$, $q$Eu desvendo lentamente o mistério por trás da carta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Decipher$q$, $q$decifrar$q$, $q$Experts try to decipher the ancient inscription.$q$, $q$Especialistas tentam decifrar a inscrição antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reminisce$q$, $q$rememorar$q$, $q$They reminisce about their college years.$q$, $q$Eles rememoram os anos de faculdade deles.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mistrust$q$, $q$desconfiar$q$, $q$Voters mistrust the candidate's sudden promises.$q$, $q$Os eleitores desconfiam das promessas repentinas do candidato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Perceive$q$, $q$captar$q$, $q$I perceive a change in her tone during the call.$q$, $q$Eu capto uma mudança no tom dela durante a ligação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fathom$q$, $q$compreender a fundo$q$, $q$I cannot fathom why he made that decision.$q$, $q$Eu não consigo compreender a fundo por que ele tomou aquela decisão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tendon$q$, $q$tendão$q$, $q$She strains a tendon during the race.$q$, $q$Ela distende um tendão durante a corrida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Joint$q$, $q$articulação$q$, $q$His knee joint hurts after the long hike.$q$, $q$A articulação do joelho dele dói depois da caminhada longa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bladder$q$, $q$bexiga$q$, $q$The doctor examines his bladder for infection.$q$, $q$O médico examina a bexiga dele para verificar infecção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nerve$q$, $q$nervo$q$, $q$A pinched nerve causes pain in her arm.$q$, $q$Um nervo comprimido causa dor no braço dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thyroid$q$, $q$tireoide$q$, $q$The doctor checks her thyroid during the exam.$q$, $q$O médico examina a tireoide dela durante o exame.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pancreas$q$, $q$pâncreas$q$, $q$The pancreas produces insulin for the body.$q$, $q$O pâncreas produz insulina para o corpo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Marrow$q$, $q$medula óssea$q$, $q$Bone marrow produces new blood cells.$q$, $q$A medula óssea produz novas células sanguíneas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Esophagus$q$, $q$esôfago$q$, $q$Food travels down the esophagus to the stomach.$q$, $q$O alimento desce pelo esôfago até o estômago.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hormone$q$, $q$hormônio$q$, $q$Stress affects the level of this hormone.$q$, $q$Estresse afeta o nível deste hormônio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gland$q$, $q$glândula$q$, $q$The gland regulates hormones in the body.$q$, $q$A glândula regula hormônios no corpo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Anchor$q$, $q$âncora$q$, $q$The sailor drops the anchor near the shore.$q$, $q$O marinheiro solta a âncora perto da costa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rudder$q$, $q$leme$q$, $q$The captain steers using the ship's rudder.$q$, $q$O capitão guia usando o leme do navio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hull$q$, $q$casco de navio$q$, $q$Waves crash against the ship's hull.$q$, $q$Ondas batem contra o casco do navio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mast$q$, $q$mastro$q$, $q$The flag flies from the top of the mast.$q$, $q$A bandeira tremula no topo do mastro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deck$q$, $q$convés$q$, $q$Passengers relax on the upper deck.$q$, $q$Os passageiros relaxam no convés superior.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bow$q$, $q$proa$q$, $q$Water splashes over the bow of the boat.$q$, $q$Água respinga sobre a proa do barco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stern$q$, $q$popa$q$, $q$He stands at the stern watching the sunset.$q$, $q$Ele fica na popa observando o pôr do sol.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sail$q$, $q$vela de barco$q$, $q$The wind fills the ship's sail.$q$, $q$O vento enche a vela do navio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Shipwreck$q$, $q$naufrágio$q$, $q$Divers discover an old shipwreck near the reef.$q$, $q$Mergulhadores descobrem um naufrágio antigo perto do recife.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lighthouse$q$, $q$farol marítimo$q$, $q$The lighthouse guides ships through the fog.$q$, $q$O farol marítimo guia navios através da neblina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Colonnade$q$, $q$colunata$q$, $q$Tourists walk along the ancient colonnade.$q$, $q$Turistas caminham ao longo da colunata antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dome$q$, $q$cúpula$q$, $q$Sunlight streams through the glass dome.$q$, $q$A luz do sol entra pela cúpula de vidro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vault$q$, $q$abóbada$q$, $q$The ceiling forms a stone vault above the hall.$q$, $q$O teto forma uma abóbada de pedra acima do salão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Foundation$q$, $q$alicerce$q$, $q$Workers pour concrete for the building's foundation.$q$, $q$Os trabalhadores despejam concreto para o alicerce do prédio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scaffold$q$, $q$andaime$q$, $q$Workers climb the scaffold to paint the wall.$q$, $q$Trabalhadores sobem no andaime para pintar a parede.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Arch$q$, $q$arco de pedra$q$, $q$The bridge stands on a single stone arch.$q$, $q$A ponte fica apoiada num único arco de pedra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pillar$q$, $q$pilar$q$, $q$A marble pillar supports the roof.$q$, $q$Um pilar de mármore sustenta o telhado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tile$q$, $q$telha$q$, $q$A broken tile lies near the front door.$q$, $q$Uma telha quebrada está perto da porta da frente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chimney$q$, $q$chaminé$q$, $q$Smoke rises from the old brick chimney.$q$, $q$Fumaça sobe da chaminé antiga de tijolos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mansion$q$, $q$mansão$q$, $q$The family lives in a large mansion outside the city.$q$, $q$A família mora numa mansão grande fora da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Trainee$q$, $q$estagiário$q$, $q$The trainee shadows a senior engineer this month.$q$, $q$O estagiário acompanha um engenheiro sênior este mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Severance$q$, $q$verbas rescisórias$q$, $q$She receives severance after the layoff.$q$, $q$Ela recebe verbas rescisórias depois da demissão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Perk$q$, $q$regalia de trabalho$q$, $q$Free lunch is one perk of this job.$q$, $q$Almoço grátis é uma regalia deste emprego.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Exhaustion$q$, $q$esgotamento profissional$q$, $q$He reaches a state of professional exhaustion after months of overtime.$q$, $q$Ele chega a um estado de esgotamento profissional depois de meses de hora extra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Union$q$, $q$sindicato$q$, $q$The union negotiates better wages for the workers.$q$, $q$O sindicato negocia salários melhores para os trabalhadores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pension$q$, $q$aposentadoria$q$, $q$She plans her pension carefully for the future.$q$, $q$Ela planeja a aposentadoria dela com cuidado para o futuro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Layoff$q$, $q$demissão em massa$q$, $q$The company announces a major layoff this week.$q$, $q$A empresa anuncia uma demissão em massa esta semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Contractor$q$, $q$prestador de serviço$q$, $q$The firm hires a contractor for the new building.$q$, $q$A firma contrata um prestador de serviço para o prédio novo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Freelancer$q$, $q$profissional autônomo$q$, $q$She works as a freelancer designing websites.$q$, $q$Ela trabalha como profissional autônoma criando sites.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Workforce$q$, $q$força de trabalho$q$, $q$The factory expands its workforce this year.$q$, $q$A fábrica expande a força de trabalho dela este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Predate$q$, $q$anteceder$q$, $q$This tradition seems to predate the founding of the city.$q$, $q$Esta tradição parece anteceder a fundação da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Succeed$q$, $q$suceder$q$, $q$Spring will succeed winter in a few months.$q$, $q$A primavera vai suceder o inverno em poucos meses.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Coincide$q$, $q$coincidir$q$, $q$Her birthday happens to coincide with the holiday.$q$, $q$O aniversário dela por acaso coincide com o feriado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Linger$q$, $q$perdurar$q$, $q$I linger in the kitchen to enjoy the smell of coffee.$q$, $q$Eu perduro na cozinha para aproveitar o cheiro de café.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cease$q$, $q$cessar$q$, $q$I hope the rain will cease soon.$q$, $q$Eu espero que a chuva cesse logo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Commence$q$, $q$iniciar formalmente$q$, $q$The ceremony will commence at exactly noon.$q$, $q$A cerimônia vai começar exatamente ao meio-dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Finalize$q$, $q$finalizar$q$, $q$We finalize the contract before the deadline.$q$, $q$Nós finalizamos o contrato antes do prazo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Resume$q$, $q$retomar$q$, $q$Classes resume next Monday after the break.$q$, $q$As aulas retomam na próxima segunda depois do recesso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Protract$q$, $q$estender no tempo$q$, $q$Delays protract the trial for several more months.$q$, $q$Atrasos estendem o julgamento por vários meses a mais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Anticipate$q$, $q$antecipar$q$, $q$We anticipate higher demand during the holidays.$q$, $q$Nós antecipamos uma demanda maior durante os feriados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
