-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote7.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lawn$q$, $q$gramado$q$, $q$I mow the lawn every Sunday.$q$, $q$Eu corto o gramado todo domingo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hedge$q$, $q$cerca viva$q$, $q$We trim the hedge in front of the house.$q$, $q$Nós aparamos a cerca viva na frente da casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hose$q$, $q$mangueira de jardim$q$, $q$I water the plants with a hose.$q$, $q$Eu rego as plantas com uma mangueira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wheelbarrow$q$, $q$carrinho de mão$q$, $q$He carries the dirt in a wheelbarrow.$q$, $q$Ele carrega a terra num carrinho de mão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fertilizer$q$, $q$adubo$q$, $q$She adds fertilizer to the garden soil.$q$, $q$Ela adiciona adubo à terra do jardim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Greenhouse$q$, $q$estufa de plantas$q$, $q$They grow tomatoes in a greenhouse.$q$, $q$Eles cultivam tomates numa estufa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Flowerbed$q$, $q$canteiro de flores$q$, $q$I plant roses in the flowerbed.$q$, $q$Eu planto rosas no canteiro de flores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Grill$q$, $q$churrasqueira$q$, $q$We cook burgers on the grill.$q$, $q$Nós cozinhamos hambúrgueres na churrasqueira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Clothesline$q$, $q$varal de roupas$q$, $q$She hangs the clothes on the clothesline.$q$, $q$Ela pendura as roupas no varal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gutter$q$, $q$calha do telhado$q$, $q$Leaves block the gutter after the storm.$q$, $q$Folhas entopem a calha depois da tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Microwave$q$, $q$micro-ondas$q$, $q$I heat the soup in the microwave.$q$, $q$Eu esquento a sopa no micro-ondas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Toaster$q$, $q$torradeira$q$, $q$She puts two slices of bread in the toaster.$q$, $q$Ela põe duas fatias de pão na torradeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vacuum$q$, $q$aspirador de pó$q$, $q$He cleans the carpet with a vacuum.$q$, $q$Ele limpa o tapete com um aspirador de pó.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Washer$q$, $q$máquina de lavar roupa$q$, $q$I put the towels in the washer.$q$, $q$Eu ponho as toalhas na máquina de lavar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Kettle$q$, $q$chaleira$q$, $q$She boils water in the kettle.$q$, $q$Ela ferve água na chaleira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Remote$q$, $q$controle remoto$q$, $q$I can't find the TV remote.$q$, $q$Eu não consigo encontrar o controle remoto da TV.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Headphones$q$, $q$fones de ouvido$q$, $q$He listens to music with his headphones.$q$, $q$Ele escuta música com os fones de ouvido dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Radiator$q$, $q$radiador$q$, $q$The radiator warms up the whole room.$q$, $q$O radiador esquenta o quarto inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Heater$q$, $q$aquecedor$q$, $q$We turn on the heater in winter.$q$, $q$Nós ligamos o aquecedor no inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Freezer$q$, $q$congelador$q$, $q$I keep the meat in the freezer.$q$, $q$Eu guardo a carne no congelador.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Butcher$q$, $q$açougue$q$, $q$I buy fresh meat from the butcher.$q$, $q$Eu compro carne fresca no açougue.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bookstore$q$, $q$livraria$q$, $q$She spends an hour in the bookstore.$q$, $q$Ela passa uma hora na livraria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Florist$q$, $q$floricultura$q$, $q$He orders flowers from a local florist.$q$, $q$Ele encomenda flores numa floricultura local.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Laundromat$q$, $q$lavanderia self-service$q$, $q$I wash my clothes at the laundromat.$q$, $q$Eu lavo minhas roupas na lavanderia self-service.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Barbershop$q$, $q$barbearia$q$, $q$He gets a haircut at the barbershop.$q$, $q$Ele corta o cabelo na barbearia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jewelry$q$, $q$joalheria$q$, $q$She buys a ring at the jewelry store.$q$, $q$Ela compra um anel na joalheria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stationery$q$, $q$papelaria$q$, $q$I buy notebooks at the stationery shop.$q$, $q$Eu compro cadernos na papelaria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Supermarket$q$, $q$supermercado$q$, $q$We shop for groceries at the supermarket.$q$, $q$Nós compramos mantimentos no supermercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hairdresser$q$, $q$cabeleireiro$q$, $q$She visits the hairdresser every month.$q$, $q$Ela visita o cabeleireiro todo mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Agency$q$, $q$agência de viagens$q$, $q$They book the trip through a travel agency.$q$, $q$Eles reservam a viagem por uma agência de viagens.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sender$q$, $q$remetente$q$, $q$The sender writes his name on the box.$q$, $q$O remetente escreve o nome dele na caixa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Recipient$q$, $q$destinatário$q$, $q$The recipient signs for the package.$q$, $q$O destinatário assina o recebimento do pacote.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Parcel$q$, $q$encomenda$q$, $q$I receive a small parcel today.$q$, $q$Eu recebo uma pequena encomenda hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Address$q$, $q$endereço$q$, $q$She writes her address on the form.$q$, $q$Ela escreve o endereço dela no formulário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Inbox$q$, $q$caixa de entrada$q$, $q$I have ten new messages in my inbox.$q$, $q$Eu tenho dez mensagens novas na minha caixa de entrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Attachment$q$, $q$anexo$q$, $q$Please open the attachment in this email.$q$, $q$Por favor, abra o anexo neste e-mail.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Draft$q$, $q$rascunho$q$, $q$I save this letter as a draft.$q$, $q$Eu salvo esta carta como rascunho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Signature$q$, $q$assinatura de e-mail$q$, $q$Add your signature at the end of the email.$q$, $q$Adicione sua assinatura no final do e-mail.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Delivery$q$, $q$entrega$q$, $q$The delivery arrives before noon.$q$, $q$A entrega chega antes do meio-dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shipment$q$, $q$remessa$q$, $q$The shipment leaves the warehouse today.$q$, $q$A remessa sai do depósito hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sum$q$, $q$soma$q$, $q$Add these two numbers to find the sum.$q$, $q$Some estes dois números para encontrar a soma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Subtraction$q$, $q$subtração$q$, $q$She learns subtraction in first grade.$q$, $q$Ela aprende subtração no primeiro ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Division$q$, $q$divisão$q$, $q$This division has a difficult answer.$q$, $q$Esta divisão tem uma resposta difícil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Percentage$q$, $q$porcentagem$q$, $q$What percentage of students pass the exam?$q$, $q$Que porcentagem de alunos passa na prova?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fraction$q$, $q$fração$q$, $q$He writes the fraction on the board.$q$, $q$Ele escreve a fração no quadro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Average$q$, $q$média aritmética$q$, $q$The average of these numbers is ten.$q$, $q$A média destes números é dez.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Angle$q$, $q$ângulo$q$, $q$Measure the angle with a protractor.$q$, $q$Meça o ângulo com um transferidor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Width$q$, $q$largura$q$, $q$The width of the table is one meter.$q$, $q$A largura da mesa é um metro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Weight$q$, $q$peso$q$, $q$The weight of the box surprises me.$q$, $q$O peso da caixa me surpreende.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Length$q$, $q$comprimento$q$, $q$The length of the rope is five meters.$q$, $q$O comprimento da corda é cinco metros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Liquid$q$, $q$líquido$q$, $q$Water is a liquid at room temperature.$q$, $q$Água é um líquido em temperatura ambiente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gas$q$, $q$gás$q$, $q$The balloon fills with gas.$q$, $q$O balão enche de gás.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Solid$q$, $q$sólido$q$, $q$Ice is water in a solid state.$q$, $q$Gelo é água em estado sólido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mixture$q$, $q$mistura$q$, $q$The mixture of colors creates a new shade.$q$, $q$A mistura de cores cria um tom novo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rust$q$, $q$ferrugem$q$, $q$Rust covers the old metal gate.$q$, $q$Ferrugem cobre o portão de metal velho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Flame$q$, $q$chama$q$, $q$A small flame lights the candle.$q$, $q$Uma chama pequena acende a vela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spark$q$, $q$faísca$q$, $q$A spark starts the fire in the fireplace.$q$, $q$Uma faísca começa o fogo na lareira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Steam$q$, $q$vapor$q$, $q$Steam rises from the hot cup of tea.$q$, $q$Vapor sobe da xícara quente de chá.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Electricity$q$, $q$eletricidade$q$, $q$Electricity powers the whole building.$q$, $q$Eletricidade alimenta o prédio inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Magnet$q$, $q$ímã$q$, $q$The magnet sticks to the refrigerator.$q$, $q$O ímã gruda na geladeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Exhausting$q$, $q$cansativo$q$, $q$The trip is long and exhausting.$q$, $q$A viagem é longa e cansativa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Risky$q$, $q$arriscado$q$, $q$This business plan seems risky.$q$, $q$Este plano de negócio parece arriscado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Comfortable$q$, $q$confortável$q$, $q$This chair feels very comfortable.$q$, $q$Esta cadeira parece muito confortável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Uncomfortable$q$, $q$desconfortável$q$, $q$The room feels uncomfortable and cold.$q$, $q$O quarto parece desconfortável e frio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Crowded$q$, $q$lotado$q$, $q$The train is crowded during rush hour.$q$, $q$O trem está lotado durante o horário de pico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Deserted$q$, $q$deserto de gente$q$, $q$The street looks deserted at midnight.$q$, $q$A rua parece deserta à meia-noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Available$q$, $q$disponível$q$, $q$The manager is not available right now.$q$, $q$O gerente não está disponível agora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Costly$q$, $q$caríssimo$q$, $q$The repair turns out to be very costly.$q$, $q$O conserto acaba sendo muito caro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sufficient$q$, $q$suficiente$q$, $q$This amount of food is sufficient for us.$q$, $q$Esta quantidade de comida é suficiente para nós.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reliable$q$, $q$confiável$q$, $q$She is a reliable and honest worker.$q$, $q$Ela é uma trabalhadora confiável e honesta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Coward$q$, $q$covarde$q$, $q$He is not a coward in a difficult moment.$q$, $q$Ele não é um covarde num momento difícil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Foolish$q$, $q$tolo$q$, $q$It is foolish to drive without checking the map.$q$, $q$É tolo dirigir sem conferir o mapa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wise$q$, $q$sábio$q$, $q$Her grandmother gives wise advice.$q$, $q$A avó dela dá conselhos sábios.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Naive$q$, $q$ingênuo$q$, $q$It is naive to trust every stranger.$q$, $q$É ingênuo confiar em todo estranho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Greedy$q$, $q$ganancioso$q$, $q$The greedy man never shares his money.$q$, $q$O homem ganancioso nunca compartilha o dinheiro dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Envious$q$, $q$invejoso$q$, $q$She feels envious of her sister's success.$q$, $q$Ela se sente invejosa do sucesso da irmã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Serious$q$, $q$sério$q$, $q$He looks serious during the meeting.$q$, $q$Ele parece sério durante a reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Amusing$q$, $q$divertido$q$, $q$The clown tells an amusing story.$q$, $q$O palhaço conta uma história divertida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cheerful$q$, $q$bem-humorado$q$, $q$She has a cheerful personality.$q$, $q$Ela tem uma personalidade bem-humorada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Creative$q$, $q$criativo$q$, $q$The team comes up with a creative idea.$q$, $q$A equipe apresenta uma ideia criativa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Blink$q$, $q$piscar$q$, $q$I blink twice because of the bright light.$q$, $q$Eu pisco duas vezes por causa da luz forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Frown$q$, $q$franzir a testa$q$, $q$I frown when I read the message.$q$, $q$Eu franzo a testa quando leio a mensagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Beam$q$, $q$sorrir largamente$q$, $q$I beam with pride at the ceremony.$q$, $q$Eu sorrio largamente de orgulho na cerimônia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sigh$q$, $q$suspirar$q$, $q$I sigh after a long day at work.$q$, $q$Eu suspiro depois de um dia longo de trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sob$q$, $q$soluçar$q$, $q$I sob quietly during the sad film.$q$, $q$Eu soluço baixinho durante o filme triste.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Groan$q$, $q$gemer$q$, $q$I groan when I see the long line.$q$, $q$Eu gemo quando vejo a fila longa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mumble$q$, $q$murmurar$q$, $q$I mumble an answer without looking up.$q$, $q$Eu murmuro uma resposta sem olhar para cima.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stutter$q$, $q$gaguejar$q$, $q$I stutter a little when I get nervous.$q$, $q$Eu gaguejo um pouco quando fico nervoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Giggle$q$, $q$rir baixinho$q$, $q$The kids giggle during the funny movie.$q$, $q$As crianças riem baixinho durante o filme engraçado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shiver$q$, $q$estremecer$q$, $q$I shiver in the cold morning air.$q$, $q$Eu estremeço no ar frio da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Leap$q$, $q$saltar$q$, $q$I leap over the small fence.$q$, $q$Eu salto sobre a cerca pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dive$q$, $q$mergulhar$q$, $q$I dive into the pool from the edge.$q$, $q$Eu mergulho na piscina da beirada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Slide$q$, $q$deslizar$q$, $q$The kids slide down the hill on cardboard.$q$, $q$As crianças deslizam morro abaixo em papelão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Slip$q$, $q$escorregar$q$, $q$I slip on the wet floor.$q$, $q$Eu escorrego no chão molhado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rotate$q$, $q$girar$q$, $q$I rotate the chair to face the window.$q$, $q$Eu giro a cadeira para ficar de frente para a janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wiggle$q$, $q$rebolar$q$, $q$I wiggle my toes in the warm sand.$q$, $q$Eu mexo os dedos do pé na areia quente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stroll$q$, $q$passear a pé$q$, $q$We stroll through the park after dinner.$q$, $q$Nós passeamos a pé pelo parque depois do jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Drag$q$, $q$arrastar$q$, $q$I drag the heavy bag across the floor.$q$, $q$Eu arrasto a bolsa pesada pelo chão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sprint$q$, $q$correr em disparada$q$, $q$I sprint to catch the bus.$q$, $q$Eu corro em disparada para pegar o ônibus.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wander$q$, $q$vagar$q$, $q$We wander through the old streets of the city.$q$, $q$Nós vagamos pelas ruas antigas da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
