-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote1.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Career$q$, $q$carreira$q$, $q$She started her career as a teacher.$q$, $q$Ela começou a carreira dela como professora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Colleague$q$, $q$colega de trabalho$q$, $q$I discuss the project with a colleague.$q$, $q$Eu discuto o projeto com um colega de trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Deadline$q$, $q$prazo final$q$, $q$The deadline for this report is Friday.$q$, $q$O prazo final para este relatório é sexta-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Employee$q$, $q$funcionário$q$, $q$Every employee gets a badge.$q$, $q$Todo funcionário recebe um crachá.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Employer$q$, $q$empregador$q$, $q$My employer offers good benefits.$q$, $q$Meu empregador oferece bons benefícios.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Promotion$q$, $q$promoção no emprego$q$, $q$She receives a promotion after two years.$q$, $q$Ela recebe uma promoção depois de dois anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Interview$q$, $q$entrevista de emprego$q$, $q$I have a job interview tomorrow.$q$, $q$Eu tenho uma entrevista de emprego amanhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Manager$q$, $q$gerente$q$, $q$The manager approves the new schedule.$q$, $q$O gerente aprova o novo horário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Retire$q$, $q$aposentar-se$q$, $q$My uncle plans to retire next year.$q$, $q$Meu tio planeja se aposentar no próximo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hire$q$, $q$contratar$q$, $q$The company decides to hire more people.$q$, $q$A empresa decide contratar mais gente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Budget$q$, $q$orçamento$q$, $q$We need to plan a monthly budget.$q$, $q$Nós precisamos planejar um orçamento mensal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Debt$q$, $q$dívida$q$, $q$He works hard to pay off his debt.$q$, $q$Ele trabalha duro para pagar sua dívida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Loan$q$, $q$empréstimo$q$, $q$They apply for a loan to buy a car.$q$, $q$Eles pedem um empréstimo para comprar um carro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tax$q$, $q$imposto$q$, $q$The government raises the tax on fuel.$q$, $q$O governo aumenta o imposto sobre combustível.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Profit$q$, $q$lucro$q$, $q$The company makes a good profit this year.$q$, $q$A empresa tem um bom lucro este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Loss$q$, $q$prejuízo$q$, $q$The business reports a loss last month.$q$, $q$A empresa registrou um prejuízo no mês passado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Savings$q$, $q$poupança$q$, $q$She keeps her savings in the bank.$q$, $q$Ela mantém a poupança dela no banco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Yield$q$, $q$rendimento$q$, $q$The investment offers a low yield.$q$, $q$O investimento oferece um rendimento baixo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rent$q$, $q$aluguel$q$, $q$We pay the rent on the first of the month.$q$, $q$Nós pagamos o aluguel no primeiro dia do mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Invoice$q$, $q$fatura$q$, $q$Please send me the invoice by email.$q$, $q$Por favor, me envie a fatura por e-mail.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Disease$q$, $q$doença$q$, $q$Doctors study a new disease.$q$, $q$Os médicos estudam uma nova doença.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Symptom$q$, $q$sintoma$q$, $q$A headache can be a symptom of stress.$q$, $q$Uma dor de cabeça pode ser um sintoma de estresse.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Surgery$q$, $q$cirurgia$q$, $q$He needs surgery on his knee.$q$, $q$Ele precisa de cirurgia no joelho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vaccine$q$, $q$vacina$q$, $q$The vaccine protects against the flu.$q$, $q$A vacina protege contra a gripe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Allergy$q$, $q$alergia$q$, $q$She has an allergy to peanuts.$q$, $q$Ela tem alergia a amendoim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Injury$q$, $q$ferimento$q$, $q$The player recovers from his injury.$q$, $q$O jogador se recupera do ferimento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Treatment$q$, $q$tratamento$q$, $q$The treatment lasts three weeks.$q$, $q$O tratamento dura três semanas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Prescription$q$, $q$receita médica$q$, $q$The doctor writes a prescription.$q$, $q$O médico escreve uma receita médica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Patient$q$, $q$paciente$q$, $q$The nurse takes care of the patient.$q$, $q$A enfermeira cuida do paciente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Recovery$q$, $q$recuperação$q$, $q$Her recovery takes a few months.$q$, $q$A recuperação dela leva alguns meses.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$College$q$, $q$faculdade$q$, $q$She studies medicine in college.$q$, $q$Ela estuda medicina na faculdade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Degree$q$, $q$graduação$q$, $q$He earns a degree in engineering.$q$, $q$Ele tira uma graduação em engenharia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Scholarship$q$, $q$bolsa de estudos$q$, $q$She wins a scholarship to study abroad.$q$, $q$Ela ganha uma bolsa de estudos para estudar no exterior.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Enrollment$q$, $q$matrícula$q$, $q$The enrollment for classes starts in March.$q$, $q$A matrícula para as aulas começa em março.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lecture$q$, $q$palestra$q$, $q$The professor gives a lecture on history.$q$, $q$O professor dá uma palestra sobre história.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Research$q$, $q$pesquisa acadêmica$q$, $q$They do research on climate change.$q$, $q$Eles fazem pesquisa sobre mudança climática.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Thesis$q$, $q$tese$q$, $q$She writes her thesis about education.$q$, $q$Ela escreve a tese dela sobre educação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Internship$q$, $q$estágio$q$, $q$He completes an internship at a bank.$q$, $q$Ele completa um estágio num banco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Attendance$q$, $q$frequência às aulas$q$, $q$Attendance is required for this class.$q$, $q$A frequência às aulas é obrigatória nesta turma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Freshman$q$, $q$calouro$q$, $q$She is a freshman at the university.$q$, $q$Ela é calouro na universidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Accommodation$q$, $q$hospedagem$q$, $q$We book our accommodation online.$q$, $q$Nós reservamos nossa hospedagem online.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reservation$q$, $q$reserva$q$, $q$I make a reservation for two people.$q$, $q$Eu faço uma reserva para duas pessoas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Luggage$q$, $q$bagagem$q$, $q$Please check your luggage before the flight.$q$, $q$Por favor, cheque sua bagagem antes do voo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Customs$q$, $q$alfândega$q$, $q$We wait in line at customs.$q$, $q$Nós esperamos na fila na alfândega.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Boarding$q$, $q$embarque$q$, $q$Boarding starts thirty minutes before the flight.$q$, $q$O embarque começa trinta minutos antes do voo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Itinerary$q$, $q$roteiro de viagem$q$, $q$Our itinerary includes three cities.$q$, $q$Nosso roteiro de viagem inclui três cidades.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Destination$q$, $q$destino de viagem$q$, $q$Our final destination is Rome.$q$, $q$Nosso destino final é Roma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sightseeing$q$, $q$passeio turístico$q$, $q$We go sightseeing in the old town.$q$, $q$Nós fazemos passeio turístico na cidade antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Currency$q$, $q$moeda estrangeira$q$, $q$I exchange my currency at the airport.$q$, $q$Eu troco minha moeda estrangeira no aeroporto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Delay$q$, $q$atraso$q$, $q$The flight has a two-hour delay.$q$, $q$O voo tem um atraso de duas horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Landlord$q$, $q$proprietário do imóvel$q$, $q$The landlord fixes the leak quickly.$q$, $q$O proprietário do imóvel conserta o vazamento rápido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tenant$q$, $q$inquilino$q$, $q$The new tenant moves in next week.$q$, $q$O novo inquilino se muda na próxima semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Furniture$q$, $q$mobília$q$, $q$They buy new furniture for the living room.$q$, $q$Eles compram móveis novos para a sala.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Renovation$q$, $q$reforma da casa$q$, $q$The renovation takes three months.$q$, $q$A reforma da casa leva três meses.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Plumbing$q$, $q$encanamento$q$, $q$The plumbing in the bathroom is old.$q$, $q$O encanamento do banheiro é velho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Attic$q$, $q$sótão$q$, $q$We store old boxes in the attic.$q$, $q$Nós guardamos caixas velhas no sótão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Balcony$q$, $q$varanda$q$, $q$She grows plants on the balcony.$q$, $q$Ela cultiva plantas na varanda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hallway$q$, $q$corredor da casa$q$, $q$The pictures hang in the hallway.$q$, $q$Os quadros ficam pendurados no corredor da casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Leak$q$, $q$vazamento$q$, $q$There is a leak under the sink.$q$, $q$Há um vazamento embaixo da pia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Resident$q$, $q$morador$q$, $q$Every resident receives a parking pass.$q$, $q$Todo morador recebe um cartão de estacionamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Application$q$, $q$aplicativo$q$, $q$I download a new application.$q$, $q$Eu baixo um novo aplicativo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Update$q$, $q$atualização$q$, $q$The system needs an important update.$q$, $q$O sistema precisa de uma atualização importante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Network$q$, $q$rede de computadores$q$, $q$The office has a fast network.$q$, $q$O escritório tem uma rede de computadores rápida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Server$q$, $q$servidor$q$, $q$The server goes down for an hour.$q$, $q$O servidor sai do ar por uma hora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Browser$q$, $q$navegador de internet$q$, $q$She opens the browser to search online.$q$, $q$Ela abre o navegador para pesquisar online.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Storage$q$, $q$armazenamento$q$, $q$This phone has a lot of storage.$q$, $q$Este telefone tem muito armazenamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Touchscreen$q$, $q$tela sensível ao toque$q$, $q$The tablet has a large touchscreen.$q$, $q$O tablet tem uma tela sensível ao toque grande.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Device$q$, $q$aparelho eletrônico$q$, $q$Every student needs a device for class.$q$, $q$Todo aluno precisa de um aparelho eletrônico para a aula.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Failure$q$, $q$falha técnica$q$, $q$A power failure stops the machines.$q$, $q$Uma queda de energia para as máquinas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Security$q$, $q$segurança digital$q$, $q$The bank improves its digital security.$q$, $q$O banco melhora sua segurança digital.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Environment$q$, $q$meio ambiente$q$, $q$We must protect the environment.$q$, $q$Nós devemos proteger o meio ambiente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pollution$q$, $q$poluição$q$, $q$Pollution affects the air quality.$q$, $q$A poluição afeta a qualidade do ar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Recycling$q$, $q$reciclagem$q$, $q$Recycling helps reduce waste.$q$, $q$A reciclagem ajuda a reduzir o lixo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Deforestation$q$, $q$desmatamento$q$, $q$Deforestation destroys many habitats.$q$, $q$O desmatamento destrói muitos habitats.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Drought$q$, $q$seca$q$, $q$The drought affects the local farmers.$q$, $q$A seca afeta os agricultores locais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hurricane$q$, $q$furacão$q$, $q$The hurricane damages many houses.$q$, $q$O furacão danifica muitas casas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Energy$q$, $q$energia$q$, $q$Solar energy is becoming more common.$q$, $q$A energia solar está se tornando mais comum.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Litter$q$, $q$lixo jogado na rua$q$, $q$Please don't leave litter on the beach.$q$, $q$Por favor, não deixe lixo na praia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Species$q$, $q$espécie animal$q$, $q$This species lives only in the forest.$q$, $q$Esta espécie vive só na floresta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Extinction$q$, $q$extinção$q$, $q$Many animals are close to extinction.$q$, $q$Muitos animais estão perto da extinção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Anxious$q$, $q$ansioso$q$, $q$She feels anxious before the exam.$q$, $q$Ela se sente ansiosa antes da prova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Grateful$q$, $q$grato$q$, $q$I am grateful for your help.$q$, $q$Eu sou grato pela sua ajuda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Disappointed$q$, $q$decepcionado$q$, $q$He is disappointed with the result.$q$, $q$Ele está decepcionado com o resultado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Relieved$q$, $q$aliviado$q$, $q$We feel relieved after the good news.$q$, $q$Nós nos sentimos aliviados depois da boa notícia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Embarrassed$q$, $q$envergonhado$q$, $q$She is embarrassed by the mistake.$q$, $q$Ela está envergonhada pelo erro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Frustrated$q$, $q$frustrado$q$, $q$He is frustrated with the slow internet.$q$, $q$Ele está frustrado com a internet lenta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Optimistic$q$, $q$otimista$q$, $q$She stays optimistic about the future.$q$, $q$Ela permanece otimista sobre o futuro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Confident$q$, $q$confiante$q$, $q$He feels confident before the interview.$q$, $q$Ele se sente confiante antes da entrevista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Resentful$q$, $q$ressentido$q$, $q$She feels resentful about the decision.$q$, $q$Ela se sente ressentida com a decisão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hopeful$q$, $q$esperançoso$q$, $q$We remain hopeful about the results.$q$, $q$Nós permanecemos esperançosos sobre os resultados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Achieve$q$, $q$alcançar$q$, $q$She works hard to achieve her goals.$q$, $q$Ela trabalha duro para alcançar seus objetivos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Improve$q$, $q$melhorar$q$, $q$He wants to improve his English.$q$, $q$Ele quer melhorar o inglês dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Avoid$q$, $q$evitar$q$, $q$I avoid sugar in my coffee.$q$, $q$Eu evito açúcar no meu café.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Demand$q$, $q$exigir$q$, $q$This job will demand a lot of energy.$q$, $q$Este trabalho vai exigir muita energia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Allow$q$, $q$permitir$q$, $q$The rules allow one guest per room.$q$, $q$As regras permitem um convidado por quarto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Endure$q$, $q$aguentar$q$, $q$She has to endure a long journey.$q$, $q$Ela precisa aguentar uma viagem longa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Compare$q$, $q$comparar$q$, $q$We compare the two products before buying.$q$, $q$Nós comparamos os dois produtos antes de comprar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Establish$q$, $q$estabelecer$q$, $q$They establish a new company together.$q$, $q$Eles estabelecem uma nova empresa juntos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Develop$q$, $q$desenvolver$q$, $q$We develop a new app together.$q$, $q$Nós desenvolvemos um novo aplicativo juntos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Prove$q$, $q$provar$q$, $q$The results prove her theory.$q$, $q$Os resultados provam a teoria dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
