-- Frases-exemplo do Mental Lingo: lingo_exemplos_basico_lote6.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Deer$q$, $q$cervo$q$, $q$The deer runs in the forest.$q$, $q$O cervo corre na floresta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fox$q$, $q$raposa$q$, $q$The fox is very smart.$q$, $q$A raposa é muito esperta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Goat$q$, $q$cabra$q$, $q$The goat eats grass.$q$, $q$A cabra come grama.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Squirrel$q$, $q$esquilo$q$, $q$The squirrel climbs the tree.$q$, $q$O esquilo sobe na árvore.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Whale$q$, $q$baleia$q$, $q$The whale is a huge animal.$q$, $q$A baleia é um animal enorme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shark$q$, $q$tubarão$q$, $q$The shark swims in the ocean.$q$, $q$O tubarão nada no oceano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Butterfly$q$, $q$borboleta$q$, $q$The butterfly flies over the flower.$q$, $q$A borboleta voa sobre a flor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Spider$q$, $q$aranha$q$, $q$A spider makes a web.$q$, $q$Uma aranha faz uma teia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Owl$q$, $q$coruja$q$, $q$The owl sleeps during the day.$q$, $q$A coruja dorme durante o dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Parrot$q$, $q$papagaio$q$, $q$The parrot can talk.$q$, $q$O papagaio pode falar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fever$q$, $q$febre$q$, $q$The baby has a fever.$q$, $q$O bebê está com febre.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cough$q$, $q$tosse$q$, $q$He has a bad cough.$q$, $q$Ele está com uma tosse forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Medicine$q$, $q$remédio$q$, $q$Take this medicine twice a day.$q$, $q$Tome este remédio duas vezes ao dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Health$q$, $q$saúde$q$, $q$Good health is important.$q$, $q$Boa saúde é importante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wound$q$, $q$ferida$q$, $q$The nurse cleans the wound.$q$, $q$A enfermeira limpa a ferida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Headache$q$, $q$dor de cabeça$q$, $q$I have a headache today.$q$, $q$Eu estou com dor de cabeça hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Flu$q$, $q$gripe$q$, $q$She has the flu.$q$, $q$Ela está com gripe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pill$q$, $q$comprimido$q$, $q$Take one pill after lunch.$q$, $q$Tome um comprimido depois do almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bandage$q$, $q$curativo$q$, $q$He puts a bandage on his knee.$q$, $q$Ele põe um curativo no joelho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hurt$q$, $q$machucar$q$, $q$Did you hurt your foot?$q$, $q$Você machucou o pé?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lonely$q$, $q$solitário$q$, $q$She feels lonely at night.$q$, $q$Ela se sente solitária à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nervous$q$, $q$nervoso$q$, $q$I feel nervous before the test.$q$, $q$Eu fico nervoso antes da prova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shy$q$, $q$tímido$q$, $q$The new student is very shy.$q$, $q$O aluno novo é muito tímido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Brave$q$, $q$corajoso$q$, $q$The firefighter is very brave.$q$, $q$O bombeiro é muito corajoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lazy$q$, $q$preguiçoso$q$, $q$My cat is very lazy.$q$, $q$Meu gato é muito preguiçoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Clever$q$, $q$esperto$q$, $q$She is a clever student.$q$, $q$Ela é uma aluna esperta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Polite$q$, $q$educado$q$, $q$He is always polite to everyone.$q$, $q$Ele é sempre educado com todos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Jealous$q$, $q$ciumento$q$, $q$My dog gets jealous of the cat.$q$, $q$Meu cachorro fica ciumento do gato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Excited$q$, $q$animado$q$, $q$The kids are excited about the trip.$q$, $q$As crianças estão animadas com a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Worried$q$, $q$preocupado$q$, $q$My mother is worried about me.$q$, $q$Minha mãe está preocupada comigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bring$q$, $q$trazer$q$, $q$Please bring your book tomorrow.$q$, $q$Por favor, traga seu livro amanhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Leave$q$, $q$sair$q$, $q$I leave home at seven.$q$, $q$Eu saio de casa às sete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Meet$q$, $q$encontrar-se com$q$, $q$Let's meet at the park.$q$, $q$Vamos nos encontrar no parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fall$q$, $q$cair$q$, $q$Be careful, don't fall.$q$, $q$Cuidado, não caia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sell$q$, $q$vender$q$, $q$They sell fruit at the market.$q$, $q$Eles vendem fruta no mercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hold$q$, $q$segurar$q$, $q$Can you hold my bag, please?$q$, $q$Você pode segurar minha bolsa, por favor?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Keep$q$, $q$manter$q$, $q$You can keep the book.$q$, $q$Você pode manter o livro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wake$q$, $q$acordar$q$, $q$I wake up at six every day.$q$, $q$Eu acordo às seis todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Turn$q$, $q$virar$q$, $q$Turn left at the corner.$q$, $q$Vire à esquerda na esquina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Climb$q$, $q$escalar$q$, $q$We climb the mountain together.$q$, $q$Nós escalamos a montanha juntos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Arrive$q$, $q$chegar$q$, $q$The train will arrive soon.$q$, $q$O trem vai chegar logo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Try$q$, $q$tentar$q$, $q$Try this cake, it's delicious.$q$, $q$Experimente este bolo, está delicioso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Believe$q$, $q$acreditar$q$, $q$I believe you.$q$, $q$Eu acredito em você.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Remember$q$, $q$lembrar$q$, $q$I remember your name.$q$, $q$Eu lembro do seu nome.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Understand$q$, $q$entender$q$, $q$I understand the lesson now.$q$, $q$Eu entendo a lição agora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Choose$q$, $q$escolher$q$, $q$Choose a color you like.$q$, $q$Escolha uma cor que você goste.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Change$q$, $q$mudar$q$, $q$I want to change my plans.$q$, $q$Eu quero mudar meus planos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hide$q$, $q$esconder$q$, $q$The cat likes to hide under the bed.$q$, $q$O gato gosta de se esconder embaixo da cama.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Share$q$, $q$compartilhar$q$, $q$Let's share the cake.$q$, $q$Vamos compartilhar o bolo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Follow$q$, $q$seguir$q$, $q$Please follow me.$q$, $q$Por favor, me siga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Neighborhood$q$, $q$bairro$q$, $q$I like my neighborhood.$q$, $q$Eu gosto do meu bairro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Path$q$, $q$trilha$q$, $q$We walk along the path.$q$, $q$Nós caminhamos pela trilha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cave$q$, $q$caverna$q$, $q$They explore a dark cave.$q$, $q$Eles exploram uma caverna escura.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Border$q$, $q$fronteira$q$, $q$The river marks the border.$q$, $q$O rio marca a fronteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Zoo$q$, $q$zoológico$q$, $q$We visit the zoo on Sundays.$q$, $q$Nós visitamos o zoológico aos domingos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Harbor$q$, $q$porto$q$, $q$The ship arrives at the harbor.$q$, $q$O navio chega ao porto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pool$q$, $q$piscina$q$, $q$The children swim in the pool.$q$, $q$As crianças nadam na piscina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Playground$q$, $q$parquinho$q$, $q$The kids play at the playground.$q$, $q$As crianças brincam no parquinho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Stadium$q$, $q$estádio$q$, $q$The game is at the stadium.$q$, $q$O jogo é no estádio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mall$q$, $q$shopping$q$, $q$We shop at the mall.$q$, $q$Nós fazemos compras no shopping.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Price$q$, $q$preço$q$, $q$What is the price of this shirt?$q$, $q$Qual é o preço desta camisa?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sale$q$, $q$promoção$q$, $q$There is a big sale today.$q$, $q$Há uma grande promoção hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cash$q$, $q$dinheiro vivo$q$, $q$I pay in cash.$q$, $q$Eu pago em dinheiro vivo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Coin$q$, $q$moeda$q$, $q$I find a coin on the street.$q$, $q$Eu encontro uma moeda na rua.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bill$q$, $q$conta de restaurante$q$, $q$Can I have the bill, please?$q$, $q$Posso ter a conta, por favor?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wallet$q$, $q$carteira de dinheiro$q$, $q$My wallet is in my bag.$q$, $q$Minha carteira está na minha bolsa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Receipt$q$, $q$recibo$q$, $q$Keep the receipt, please.$q$, $q$Guarde o recibo, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Basket$q$, $q$cesta$q$, $q$She carries a basket of fruit.$q$, $q$Ela carrega uma cesta de frutas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cart$q$, $q$carrinho de compras$q$, $q$He pushes the cart at the store.$q$, $q$Ele empurra o carrinho na loja.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Discount$q$, $q$desconto$q$, $q$I get a discount on the shoes.$q$, $q$Eu ganho um desconto nos sapatos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Message$q$, $q$mensagem$q$, $q$I send you a message.$q$, $q$Eu te envio uma mensagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Newspaper$q$, $q$jornal$q$, $q$My father reads the newspaper.$q$, $q$Meu pai lê o jornal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Magazine$q$, $q$revista$q$, $q$She reads a fashion magazine.$q$, $q$Ela lê uma revista de moda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Story$q$, $q$história contada$q$, $q$Tell me a story.$q$, $q$Me conte uma história.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$News$q$, $q$notícias$q$, $q$I watch the news every night.$q$, $q$Eu assisto às notícias toda noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Word$q$, $q$palavra$q$, $q$What does this word mean?$q$, $q$O que esta palavra significa?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Voice$q$, $q$voz$q$, $q$She has a beautiful voice.$q$, $q$Ela tem uma voz bonita.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Language$q$, $q$idioma$q$, $q$English is my second language.$q$, $q$Inglês é meu segundo idioma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sound$q$, $q$som$q$, $q$I hear a strange sound.$q$, $q$Eu ouço um som estranho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Song$q$, $q$canção$q$, $q$I like this song.$q$, $q$Eu gosto desta canção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Minute$q$, $q$minuto$q$, $q$Wait a minute, please.$q$, $q$Espere um minuto, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Second$q$, $q$segundo de tempo$q$, $q$It takes only a second.$q$, $q$Isso leva só um segundo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nowadays$q$, $q$hoje em dia$q$, $q$Nowadays, people use phones a lot.$q$, $q$Hoje em dia, as pessoas usam muito o telefone.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tonight$q$, $q$hoje à noite$q$, $q$We watch a movie tonight.$q$, $q$Nós assistimos a um filme hoje à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Noon$q$, $q$meio-dia$q$, $q$We eat lunch at noon.$q$, $q$Nós almoçamos ao meio-dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Midnight$q$, $q$meia-noite$q$, $q$The party ends at midnight.$q$, $q$A festa termina à meia-noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Season$q$, $q$estação do ano$q$, $q$Summer is my favorite season.$q$, $q$Verão é minha estação favorita.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Past$q$, $q$passado$q$, $q$I don't think about the past.$q$, $q$Eu não penso no passado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Future$q$, $q$futuro$q$, $q$I am excited about the future.$q$, $q$Eu estou animado com o futuro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Soon$q$, $q$logo$q$, $q$I will see you soon.$q$, $q$Eu te vejo logo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Left$q$, $q$esquerda$q$, $q$Turn left, please.$q$, $q$Vire à esquerda, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Right$q$, $q$direita$q$, $q$Turn right at the light.$q$, $q$Vire à direita no semáforo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Up$q$, $q$para cima$q$, $q$Look up at the sky.$q$, $q$Olhe para cima, para o céu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Down$q$, $q$para baixo$q$, $q$Sit down, please.$q$, $q$Sente-se, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Front$q$, $q$frente$q$, $q$She stands in front of the class.$q$, $q$Ela fica na frente da turma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Middle$q$, $q$meio$q$, $q$The park is in the middle of the city.$q$, $q$O parque fica no meio da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Side$q$, $q$lado$q$, $q$He sits on the other side.$q$, $q$Ele senta do outro lado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Top$q$, $q$topo$q$, $q$The book is on top of the desk.$q$, $q$O livro está no topo da mesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bottom$q$, $q$parte de baixo$q$, $q$The cat is at the bottom of the stairs.$q$, $q$O gato está na parte de baixo da escada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Circle$q$, $q$círculo$q$, $q$Draw a circle on the paper.$q$, $q$Desenhe um círculo no papel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
