-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote2.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Startup$q$, $q$empresa iniciante$q$, $q$He works for a tech startup.$q$, $q$Ele trabalha numa empresa iniciante de tecnologia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Competitor$q$, $q$concorrente$q$, $q$Our main competitor lowers its prices.$q$, $q$Nosso principal concorrente baixa os preços.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Loyal$q$, $q$leal$q$, $q$She stays loyal to the company for years.$q$, $q$Ela permanece leal à empresa por anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Supplier$q$, $q$fornecedor$q$, $q$We change our main supplier this year.$q$, $q$Nós trocamos nosso principal fornecedor este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Partner$q$, $q$sócio$q$, $q$He becomes a partner in the firm.$q$, $q$Ele se torna sócio na empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Contract$q$, $q$contrato$q$, $q$They sign the contract this morning.$q$, $q$Eles assinam o contrato hoje de manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sales$q$, $q$vendas$q$, $q$Sales increase during the holidays.$q$, $q$As vendas aumentam durante os feriados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Brand$q$, $q$marca comercial$q$, $q$This brand is popular among young people.$q$, $q$Esta marca comercial é popular entre os jovens.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Retail$q$, $q$varejo$q$, $q$She works in retail management.$q$, $q$Ela trabalha na gestão de varejo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Negotiation$q$, $q$negociação$q$, $q$The negotiation takes several hours.$q$, $q$A negociação leva várias horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Legislation$q$, $q$legislação$q$, $q$New legislation protects consumer rights.$q$, $q$Nova legislação protege os direitos do consumidor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Courthouse$q$, $q$fórum judicial$q$, $q$They meet outside the courthouse.$q$, $q$Eles se encontram do lado de fora do fórum judicial.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Witness$q$, $q$testemunha$q$, $q$The witness describes what she saw.$q$, $q$A testemunha descreve o que ela viu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Verdict$q$, $q$veredito$q$, $q$The jury reaches a verdict quickly.$q$, $q$O júri chega a um veredito rapidamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Attorney$q$, $q$advogado de defesa$q$, $q$She hires an attorney for the case.$q$, $q$Ela contrata um advogado de defesa para o caso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bail$q$, $q$fiança$q$, $q$The judge sets a high bail.$q$, $q$O juiz define uma fiança alta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Equality$q$, $q$igualdade$q$, $q$The law promotes equality for all citizens.$q$, $q$A lei promove igualdade para todos os cidadãos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Citizenship$q$, $q$cidadania$q$, $q$He applies for citizenship after ten years.$q$, $q$Ele solicita a cidadania depois de dez anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Election$q$, $q$eleição$q$, $q$The election takes place in October.$q$, $q$A eleição acontece em outubro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Candidate$q$, $q$candidato$q$, $q$The candidate speaks at the local school.$q$, $q$O candidato fala na escola local.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Batter$q$, $q$massa líquida de bolo$q$, $q$She pours the batter into the pan.$q$, $q$Ela despeja a massa líquida na frigideira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Recipe$q$, $q$receita culinária$q$, $q$This recipe uses only five ingredients.$q$, $q$Esta receita culinária usa só cinco ingredientes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Seasoning$q$, $q$tempero$q$, $q$He adds seasoning to the meat.$q$, $q$Ele adiciona tempero na carne.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dessert$q$, $q$sobremesa$q$, $q$We order chocolate cake for dessert.$q$, $q$Nós pedimos bolo de chocolate de sobremesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Appetizer$q$, $q$aperitivo$q$, $q$The restaurant serves a small appetizer first.$q$, $q$O restaurante serve um pequeno aperitivo primeiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Barbecue$q$, $q$churrasco$q$, $q$We have a barbecue every Sunday.$q$, $q$Nós fazemos um churrasco todo domingo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Marinade$q$, $q$marinada$q$, $q$The chicken sits in the marinade overnight.$q$, $q$O frango fica na marinada durante a noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bland$q$, $q$insosso$q$, $q$The soup tastes bland without salt.$q$, $q$A sopa fica insossa sem sal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Starving$q$, $q$faminto$q$, $q$I am starving after the long hike.$q$, $q$Eu estou faminto depois da longa caminhada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Appetite$q$, $q$apetite$q$, $q$Exercise gives me a big appetite.$q$, $q$Exercício me dá um grande apetite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stretch$q$, $q$alongar$q$, $q$I stretch my legs before running.$q$, $q$Eu alongo as pernas antes de correr.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Crouch$q$, $q$agachar$q$, $q$I crouch to pick up the ball.$q$, $q$Eu me agacho para pegar a bola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Crawl$q$, $q$engatinhar$q$, $q$The baby starts to crawl this month.$q$, $q$O bebê começa a engatinhar este mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Limp$q$, $q$mancar$q$, $q$I limp after twisting my ankle.$q$, $q$Eu manco depois de torcer o tornozelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stumble$q$, $q$tropeçar$q$, $q$I stumble over a rock on the path.$q$, $q$Eu tropeço numa pedra na trilha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stagger$q$, $q$cambalear$q$, $q$I stagger home after a long day.$q$, $q$Eu cambaleio até em casa depois de um dia longo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Creep$q$, $q$rastejar$q$, $q$I creep toward the sleeping cat.$q$, $q$Eu rastejo em direção ao gato adormecido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Skip$q$, $q$saltitar$q$, $q$The kids skip down the street happily.$q$, $q$As crianças saltitam pela rua felizes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lean$q$, $q$inclinar-se$q$, $q$I lean against the wall to rest.$q$, $q$Eu me inclino contra a parede para descansar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fold$q$, $q$dobrar$q$, $q$I fold the shirts and put them away.$q$, $q$Eu dobro as camisas e as guardo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fashion$q$, $q$moda$q$, $q$She studies fashion at design school.$q$, $q$Ela estuda moda na escola de design.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fabric$q$, $q$tecido$q$, $q$This fabric feels very soft.$q$, $q$Este tecido parece muito macio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stitch$q$, $q$ponto de costura$q$, $q$She fixes the stitch on her sleeve.$q$, $q$Ela conserta o ponto de costura na manga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sleeve$q$, $q$manga$q$, $q$The sleeve of his jacket is torn.$q$, $q$A manga da jaqueta dele está rasgada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Collar$q$, $q$gola$q$, $q$His collar is a bit tight.$q$, $q$A gola dele está um pouco apertada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Zipper$q$, $q$zíper$q$, $q$The zipper on my bag is broken.$q$, $q$O zíper da minha bolsa está quebrado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Heel$q$, $q$salto de sapato$q$, $q$Her heel breaks during the party.$q$, $q$O salto do sapato dela quebra durante a festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lining$q$, $q$forro$q$, $q$The coat has a warm lining.$q$, $q$O casaco tem um forro quente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Patterned$q$, $q$estampado$q$, $q$She wears a patterned dress to the event.$q$, $q$Ela usa um vestido estampado para o evento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Snug$q$, $q$justo no corpo$q$, $q$These jeans feel snug on me.$q$, $q$Esta calça jeans fica justa em mim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Conversation$q$, $q$conversa$q$, $q$We have a long conversation about the trip.$q$, $q$Nós temos uma conversa longa sobre a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Argument$q$, $q$discussão acalorada$q$, $q$They have an argument about money.$q$, $q$Eles têm uma discussão acalorada sobre dinheiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Advice$q$, $q$conselho$q$, $q$She gives me good advice about work.$q$, $q$Ela me dá um bom conselho sobre trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Opinion$q$, $q$opinião$q$, $q$Everyone shares an opinion about the movie.$q$, $q$Todo mundo compartilha uma opinião sobre o filme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rumor$q$, $q$boato$q$, $q$A rumor spreads quickly around the office.$q$, $q$Um boato se espalha rápido pelo escritório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gossip$q$, $q$fofoca$q$, $q$She doesn't like to gossip about others.$q$, $q$Ela não gosta de fofocar sobre os outros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lie$q$, $q$mentira$q$, $q$He tells a lie to avoid trouble.$q$, $q$Ele conta uma mentira para evitar problema.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Announcement$q$, $q$anúncio oficial$q$, $q$The company makes an important announcement.$q$, $q$A empresa faz um anúncio oficial importante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Response$q$, $q$resposta$q$, $q$I wait for her response all day.$q$, $q$Eu espero pela resposta dela o dia todo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Comment$q$, $q$comentário$q$, $q$She leaves a kind comment on the photo.$q$, $q$Ela deixa um comentário gentil na foto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Skyscraper$q$, $q$arranha-céu$q$, $q$The new skyscraper is the tallest in the city.$q$, $q$O novo arranha-céu é o mais alto da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Congestion$q$, $q$engarrafamento$q$, $q$Traffic congestion is bad this morning.$q$, $q$O engarrafamento está ruim esta manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Transit$q$, $q$transporte público$q$, $q$Public transit is cheap and fast here.$q$, $q$O transporte público é barato e rápido aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Intersection$q$, $q$cruzamento$q$, $q$The accident happens at the intersection.$q$, $q$O acidente acontece no cruzamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stoplight$q$, $q$semáforo$q$, $q$Stop at the stoplight ahead.$q$, $q$Pare no semáforo à frente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Parking$q$, $q$estacionamento$q$, $q$Parking is difficult downtown.$q$, $q$Estacionamento é difícil no centro da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Homeless$q$, $q$morador de rua$q$, $q$The shelter helps homeless people find food.$q$, $q$O abrigo ajuda moradores de rua a encontrar comida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Outskirts$q$, $q$periferia$q$, $q$They live on the outskirts of the city.$q$, $q$Eles moram na periferia da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Penthouse$q$, $q$cobertura de prédio$q$, $q$They rent a penthouse with a view.$q$, $q$Eles alugam uma cobertura de prédio com vista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Construction$q$, $q$obra de construção$q$, $q$Construction on the bridge starts next week.$q$, $q$A obra de construção na ponte começa na próxima semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stubborn$q$, $q$teimoso$q$, $q$My grandfather is very stubborn.$q$, $q$Meu avô é muito teimoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Calm$q$, $q$calmo$q$, $q$She stays calm during the storm.$q$, $q$Ela permanece calma durante a tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ambitious$q$, $q$ambicioso$q$, $q$He is ambitious about his career.$q$, $q$Ele é ambicioso quanto à carreira dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Selfish$q$, $q$egoísta$q$, $q$It is selfish to ignore your friends.$q$, $q$É egoísta ignorar seus amigos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Humble$q$, $q$humilde$q$, $q$Despite his success, he remains humble.$q$, $q$Apesar do sucesso, ele continua humilde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sincere$q$, $q$sincero$q$, $q$Her apology sounds very sincere.$q$, $q$O pedido de desculpas dela soa muito sincero.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Responsible$q$, $q$responsável$q$, $q$He feels responsible for the mistake.$q$, $q$Ele se sente responsável pelo erro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Moody$q$, $q$mal-humorado$q$, $q$She is moody after a bad night's sleep.$q$, $q$Ela fica mal-humorada depois de dormir mal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stingy$q$, $q$mesquinho$q$, $q$He is too stingy to share his lunch.$q$, $q$Ele é muito mesquinho para compartilhar o almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Courteous$q$, $q$cortês$q$, $q$The staff is always courteous to guests.$q$, $q$A equipe é sempre cortês com os hóspedes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mention$q$, $q$mencionar$q$, $q$She forgets to mention the new schedule.$q$, $q$Ela esquece de mencionar o novo horário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Suggest$q$, $q$sugerir$q$, $q$I suggest we leave early tomorrow.$q$, $q$Eu sugiro que nós saiamos cedo amanhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ensure$q$, $q$garantir$q$, $q$Please ensure the door is locked.$q$, $q$Por favor, garanta que a porta esteja trancada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$State$q$, $q$declarar$q$, $q$I state my opinion clearly.$q$, $q$Eu declaro minha opinião claramente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Deny$q$, $q$negar$q$, $q$I deny knowing about the plan.$q$, $q$Eu nego saber sobre o plano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Complain$q$, $q$reclamar$q$, $q$Customers complain about the slow service.$q$, $q$Os clientes reclamam do atendimento lento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Praise$q$, $q$elogiar$q$, $q$I praise her hard work.$q$, $q$Eu elogio o trabalho duro dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Criticize$q$, $q$criticar$q$, $q$He tends to criticize every small detail.$q$, $q$Ele tende a criticar cada pequeno detalhe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Interrupt$q$, $q$interromper$q$, $q$Please don't interrupt while I am speaking.$q$, $q$Por favor, não interrompa enquanto eu estou falando.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Convince$q$, $q$convencer$q$, $q$She tries to convince him to stay.$q$, $q$Ela tenta convencer ele a ficar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hesitate$q$, $q$hesitar$q$, $q$I hesitate before answering the question.$q$, $q$Eu hesito antes de responder a pergunta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pause$q$, $q$pausar$q$, $q$Let's pause the meeting for lunch.$q$, $q$Vamos pausar a reunião para o almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Withdraw$q$, $q$recuar$q$, $q$The company decides to withdraw the offer.$q$, $q$A empresa decide retirar a oferta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Approve$q$, $q$aprovar$q$, $q$We approve the new budget.$q$, $q$Nós aprovamos o novo orçamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reject$q$, $q$rejeitar$q$, $q$They reject the proposal without explanation.$q$, $q$Eles rejeitam a proposta sem explicação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Support$q$, $q$apoiar$q$, $q$Her friends support her big decision.$q$, $q$Os amigos dela apoiam a grande decisão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Solve$q$, $q$solucionar$q$, $q$We work together to solve the problem.$q$, $q$Nós trabalhamos juntos para solucionar o problema.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gamble$q$, $q$apostar$q$, $q$He decides not to gamble his savings.$q$, $q$Ele decide não apostar a poupança dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Regret$q$, $q$arrepender-se$q$, $q$She doesn't regret her final choice.$q$, $q$Ela não se arrepende da escolha final dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pledge$q$, $q$comprometer-se$q$, $q$They pledge to finish the project on time.$q$, $q$Eles se comprometem a terminar o projeto no prazo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
