-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote8.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Precipitation$q$, $q$precipitação$q$, $q$Heavy precipitation floods several streets downtown.$q$, $q$Precipitação intensa inunda várias ruas no centro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Monsoon$q$, $q$monção$q$, $q$The monsoon season brings weeks of heavy rain.$q$, $q$A estação de monção traz semanas de chuva intensa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cyclone$q$, $q$ciclone$q$, $q$A powerful cyclone forces coastal towns to evacuate.$q$, $q$Um ciclone forte obriga cidades litorâneas a evacuar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blizzard$q$, $q$nevasca$q$, $q$The blizzard shuts down the entire airport.$q$, $q$A nevasca fecha o aeroporto inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deluge$q$, $q$dilúvio$q$, $q$A sudden deluge overwhelms the small drainage system.$q$, $q$Um dilúvio repentino sobrecarrega o pequeno sistema de drenagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dew$q$, $q$orvalho$q$, $q$Morning dew covers the grass in the garden.$q$, $q$Orvalho da manhã cobre a grama no jardim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Smog$q$, $q$neblina poluída$q$, $q$Thick smog hangs over the city every winter.$q$, $q$Neblina poluída densa paira sobre a cidade todo inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thunderstorm$q$, $q$trovoada$q$, $q$A violent thunderstorm knocks out the power.$q$, $q$Uma trovoada violenta derruba a energia elétrica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Breeze$q$, $q$brisa$q$, $q$A gentle breeze cools the beach in the afternoon.$q$, $q$Uma brisa suave refresca a praia à tarde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gust$q$, $q$rajada de vento$q$, $q$A sudden gust knocks over the outdoor chairs.$q$, $q$Uma rajada de vento repentina derruba as cadeiras de fora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Database$q$, $q$banco de dados$q$, $q$The team stores all customer data in a single database.$q$, $q$A equipe armazena todos os dados dos clientes num único banco de dados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Query$q$, $q$consulta a dados$q$, $q$I run a query to find the missing records.$q$, $q$Eu executo uma consulta para encontrar os registros ausentes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Function$q$, $q$função de programa$q$, $q$I write a function to calculate the total automatically.$q$, $q$Eu escrevo uma função para calcular o total automaticamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Compiler$q$, $q$compilador$q$, $q$The compiler flags an error in the code.$q$, $q$O compilador aponta um erro no código.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Queue$q$, $q$fila de espera$q$, $q$Every request waits in a queue before processing.$q$, $q$Toda solicitação espera numa fila antes de ser processada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pointer$q$, $q$ponteiro$q$, $q$A pointer stores the memory address of the variable.$q$, $q$Um ponteiro armazena o endereço de memória da variável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Recursion$q$, $q$recursão$q$, $q$The professor explains recursion with a simple example.$q$, $q$O professor explica recursão com um exemplo simples.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Malware$q$, $q$software malicioso$q$, $q$The antivirus detects malware on the old laptop.$q$, $q$O antivírus detecta software malicioso no laptop velho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cipher$q$, $q$código cifrado$q$, $q$The message is written in an old military cipher.$q$, $q$A mensagem está escrita num código cifrado militar antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hosting$q$, $q$hospedagem de site$q$, $q$The company switches to a faster hosting provider.$q$, $q$A empresa troca para um provedor de hospedagem mais rápido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Earnings$q$, $q$rendimentos$q$, $q$His earnings increase significantly after the promotion.$q$, $q$Os rendimentos dele aumentam significativamente depois da promoção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Interest$q$, $q$juros$q$, $q$The savings account earns very little interest.$q$, $q$A conta poupança rende juros muito baixos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Installment$q$, $q$parcela$q$, $q$I pay for the sofa in one final installment.$q$, $q$Eu pago o sofá numa parcela final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Balance$q$, $q$saldo bancário$q$, $q$I check my account balance every morning.$q$, $q$Eu confiro o saldo bancário toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Statement$q$, $q$extrato bancário$q$, $q$I review my bank statement before paying the bills.$q$, $q$Eu reviso o extrato bancário antes de pagar as contas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Withdrawal$q$, $q$saque$q$, $q$I make a small withdrawal from the ATM.$q$, $q$Eu faço um saque pequeno no caixa eletrônico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Billing$q$, $q$cobrança$q$, $q$There is an error in this month's billing.$q$, $q$Há um erro na cobrança deste mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Refund$q$, $q$reembolso$q$, $q$The store issues a full refund for the broken item.$q$, $q$A loja emite um reembolso integral pelo item quebrado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Overdraft$q$, $q$cheque especial$q$, $q$I use my overdraft to cover an emergency expense.$q$, $q$Eu uso meu cheque especial para cobrir um gasto de emergência.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Allowance$q$, $q$mesada$q$, $q$My daughter saves half of her weekly allowance.$q$, $q$Minha filha economiza metade da mesada semanal dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chandelier$q$, $q$lustre$q$, $q$A large chandelier hangs above the dining table.$q$, $q$Um lustre grande fica pendurado acima da mesa de jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bookshelf$q$, $q$estante de livros$q$, $q$He builds a wooden bookshelf for his office.$q$, $q$Ele constrói uma estante de livros de madeira para o escritório dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tapestry$q$, $q$tapeçaria$q$, $q$An old tapestry decorates the castle's main hall.$q$, $q$Uma tapeçaria antiga decora o salão principal do castelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Armchair$q$, $q$poltrona$q$, $q$She reads by the fire in a comfortable armchair.$q$, $q$Ela lê perto da lareira numa poltrona confortável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lantern$q$, $q$lampião$q$, $q$They light a lantern to guide their way at night.$q$, $q$Eles acendem um lampião para guiar o caminho deles à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cushion$q$, $q$almofada$q$, $q$A soft cushion makes the wooden chair more comfortable.$q$, $q$Uma almofada macia torna a cadeira de madeira mais confortável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blind$q$, $q$persiana$q$, $q$She lowers the blind to block the afternoon sun.$q$, $q$Ela abaixa a persiana para bloquear o sol da tarde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Duvet$q$, $q$edredom$q$, $q$I wash the duvet once every season.$q$, $q$Eu lavo o edredom uma vez por estação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Headboard$q$, $q$cabeceira de cama$q$, $q$The bed has a tall wooden headboard.$q$, $q$A cama tem uma cabeceira de madeira alta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Trunk$q$, $q$baú de viagem$q$, $q$She stores old photographs in a leather trunk.$q$, $q$Ela guarda fotografias antigas num baú de couro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Slender$q$, $q$esguio$q$, $q$The dancer has a tall, slender frame.$q$, $q$O bailarino tem um porte alto e esguio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stocky$q$, $q$atarracado$q$, $q$The wrestler has a short, stocky build.$q$, $q$O lutador tem uma compleição baixa e atarracada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pointed$q$, $q$pontiagudo$q$, $q$The tower ends in a sharp, pointed roof.$q$, $q$A torre termina num telhado afiado e pontiagudo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hollow$q$, $q$oco$q$, $q$The tree trunk sounds hollow when I knock on it.$q$, $q$O tronco da árvore soa oco quando eu bato nele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blunt$q$, $q$rombudo$q$, $q$The knife feels blunt after months of use.$q$, $q$A faca parece rombuda depois de meses de uso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Wavy$q$, $q$ondulado$q$, $q$She has long, wavy hair.$q$, $q$Ela tem cabelo longo e ondulado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Concave$q$, $q$côncavo$q$, $q$The mirror has a slightly concave surface.$q$, $q$O espelho tem uma superfície levemente côncava.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bulging$q$, $q$abaulado$q$, $q$His bag looks bulging after the trip to the market.$q$, $q$A bolsa dele parece abaulada depois da ida ao mercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bulky$q$, $q$volumoso$q$, $q$The old television is heavy and bulky.$q$, $q$A televisão velha é pesada e volumosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Petite$q$, $q$miúdo$q$, $q$She is petite but very strong.$q$, $q$Ela é miúda, mas muito forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Legislate$q$, $q$legislar$q$, $q$Congress works to legislate on climate policy.$q$, $q$O Congresso trabalha para legislar sobre política climática.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Repeal$q$, $q$revogar$q$, $q$Lawmakers vote to repeal the outdated regulation.$q$, $q$Os parlamentares votam para revogar o regulamento ultrapassado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Enact$q$, $q$promulgar$q$, $q$The state moves quickly to enact the new law.$q$, $q$O estado age rápido para promulgar a nova lei.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sanction$q$, $q$sancionar$q$, $q$The government decides to sanction the reform.$q$, $q$O governo decide sancionar a reforma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Regulate$q$, $q$regulamentar$q$, $q$Agencies work to regulate the growing industry.$q$, $q$Agências trabalham para regulamentar a indústria em crescimento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deliberate$q$, $q$deliberar$q$, $q$Judges deliberate for hours before the verdict.$q$, $q$Juízes deliberam por horas antes do veredito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Appoint$q$, $q$nomear para cargo$q$, $q$The president decides to appoint a new advisor.$q$, $q$O presidente decide nomear um novo assessor para o cargo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Depose$q$, $q$destituir do poder$q$, $q$The rebels manage to depose the corrupt leader.$q$, $q$Os rebeldes conseguem destituir o líder corrupto do poder.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Elect$q$, $q$eleger$q$, $q$Citizens elect a new mayor every four years.$q$, $q$Cidadãos elegem um novo prefeito a cada quatro anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Abolish$q$, $q$abolir$q$, $q$The council votes to abolish the old tax.$q$, $q$O conselho vota para abolir o imposto antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Commemorate$q$, $q$homenagear$q$, $q$The town holds a ceremony to commemorate the veterans.$q$, $q$A cidade realiza uma cerimônia para homenagear os veteranos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Glorify$q$, $q$glorificar$q$, $q$The movie tends to glorify a violent past.$q$, $q$O filme tende a glorificar um passado violento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Venerate$q$, $q$venerar$q$, $q$The community continues to venerate its founder.$q$, $q$A comunidade continua a venerar o fundador dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Consecrate$q$, $q$consagrar$q$, $q$The bishop travels to consecrate the new church.$q$, $q$O bispo viaja para consagrar a nova igreja.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Elevate$q$, $q$elevar$q$, $q$This award will elevate her status in the industry.$q$, $q$Este prêmio vai elevar o status dela na indústria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Desecrate$q$, $q$profanar$q$, $q$Vandals desecrate the ancient monument overnight.$q$, $q$Vândalos profanam o monumento antigo durante a noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blaspheme$q$, $q$blasfemar$q$, $q$The old law once used to punish those who blaspheme.$q$, $q$A lei antiga costumava punir quem blasfemasse, no passado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bless$q$, $q$abençoar$q$, $q$I watch the priest bless the newborn baby.$q$, $q$Eu vejo o padre abençoar o bebê recém-nascido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Curse$q$, $q$amaldiçoar$q$, $q$In the old story, the witch will curse the entire village.$q$, $q$Na história antiga, a bruxa vai amaldiçoar a vila inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Worship$q$, $q$cultuar$q$, $q$They travel far to worship at the ancient temple.$q$, $q$Eles viajam longe para cultuar no templo antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Daydream$q$, $q$devaneio$q$, $q$I often daydream about traveling the world.$q$, $q$Eu frequentemente devaneio sobre viajar pelo mundo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nightmare$q$, $q$pesadelo$q$, $q$I wake up shaking after a terrible nightmare.$q$, $q$Eu acordo tremendo depois de um pesadelo terrível.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hallucination$q$, $q$alucinação$q$, $q$The fever causes a brief hallucination.$q$, $q$A febre causa uma alucinação breve.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Delirium$q$, $q$delírio$q$, $q$He speaks in a state of delirium during the fever.$q$, $q$Ele fala num estado de delírio durante a febre.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Obsession$q$, $q$obsessão$q$, $q$His obsession with the project affects his sleep.$q$, $q$A obsessão dele pelo projeto afeta o sono dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subconscious$q$, $q$subconsciente$q$, $q$The dream reveals something from her subconscious.$q$, $q$O sonho revela algo do subconsciente dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Catharsis$q$, $q$catarse$q$, $q$Writing the letter gives her a sense of catharsis.$q$, $q$Escrever a carta dá a ela uma sensação de catarse.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Epiphany$q$, $q$epifania$q$, $q$She has a sudden epiphany while walking home.$q$, $q$Ela tem uma epifania repentina enquanto caminha para casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Illusion$q$, $q$ilusão$q$, $q$The mirror creates an illusion of more space.$q$, $q$O espelho cria uma ilusão de mais espaço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reverie$q$, $q$fantasia mental$q$, $q$He loses himself in a quiet reverie by the window.$q$, $q$Ele se perde numa fantasia mental tranquila perto da janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Liqueur$q$, $q$licor$q$, $q$She sips a sweet liqueur after dinner.$q$, $q$Ela bebe um licor doce aos poucos depois do jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Truffle$q$, $q$trufa$q$, $q$The chef adds a slice of truffle to the risotto.$q$, $q$O chef acrescenta uma fatia de trufa ao risoto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Spice$q$, $q$especiaria$q$, $q$She adds a rare spice to the traditional dish.$q$, $q$Ela acrescenta uma especiaria rara ao prato tradicional.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Saffron$q$, $q$açafrão$q$, $q$Saffron gives the rice its golden color.$q$, $q$Açafrão dá ao arroz a cor dourada dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cinnamon$q$, $q$canela$q$, $q$He sprinkles cinnamon over the hot coffee.$q$, $q$Ele espalha canela sobre o café quente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ginger$q$, $q$gengibre$q$, $q$The tea has a strong taste of fresh ginger.$q$, $q$O chá tem um sabor forte de gengibre fresco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nutmeg$q$, $q$noz-moscada$q$, $q$A pinch of nutmeg improves the pumpkin soup.$q$, $q$Uma pitada de noz-moscada melhora a sopa de abóbora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Clove$q$, $q$cravo-da-índia$q$, $q$She adds a clove to the simmering broth.$q$, $q$Ela acrescenta um cravo-da-índia ao caldo em fervura lenta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fennel$q$, $q$erva-doce$q$, $q$The salad has a hint of fresh fennel.$q$, $q$A salada tem um toque de erva-doce fresca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Oregano$q$, $q$orégano$q$, $q$He sprinkles oregano over the pizza.$q$, $q$Ele espalha orégano sobre a pizza.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Skim$q$, $q$folhear rapidamente$q$, $q$I skim the report before the meeting.$q$, $q$Eu leio rapidamente o relatório antes da reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scribble$q$, $q$rabiscar$q$, $q$I scribble a note on the back of the receipt.$q$, $q$Eu rabisco uma anotação no verso do recibo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Jot$q$, $q$anotar depressa$q$, $q$I jot down the address before I forget it.$q$, $q$Eu anoto depressa o endereço antes de esquecer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Proofread$q$, $q$revisar texto$q$, $q$I proofread the essay twice before submitting it.$q$, $q$Eu reviso o ensaio duas vezes antes de enviá-lo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Transcribe$q$, $q$transcrever$q$, $q$I transcribe the interview word for word.$q$, $q$Eu transcrevo a entrevista palavra por palavra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Type$q$, $q$digitar$q$, $q$I type the report on my laptop.$q$, $q$Eu digito o relatório no meu laptop.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Quote$q$, $q$citar trecho$q$, $q$I quote the professor directly in my essay.$q$, $q$Eu cito diretamente o professor no meu ensaio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Paraphrase$q$, $q$parafrasear$q$, $q$I paraphrase the article to avoid plagiarism.$q$, $q$Eu parafraseio o artigo para evitar plágio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Underline$q$, $q$sublinhar$q$, $q$I underline the key points in the textbook.$q$, $q$Eu sublinho os pontos principais no livro didático.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Annotate$q$, $q$anotar à margem$q$, $q$I annotate the margins with my own comments.$q$, $q$Eu anoto as margens com meus próprios comentários.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
