-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote7.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Coerce$q$, $q$coagir$q$, $q$The gang tries to coerce him into joining them.$q$, $q$A gangue tenta coagi-lo a se juntar a eles.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Intimidate$q$, $q$intimidar$q$, $q$His loud voice is meant to intimidate the new recruits.$q$, $q$A voz alta dele tem a intenção de intimidar os novos recrutas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bribe$q$, $q$subornar$q$, $q$The official refuses to bribe the inspector.$q$, $q$O funcionário se recusa a subornar o inspetor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blackmail$q$, $q$chantagear$q$, $q$Someone tries to blackmail the executive with old photos.$q$, $q$Alguém tenta chantagear o executivo com fotos antigas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Menace$q$, $q$ameaçar de mal$q$, $q$The stray dog does not menace anyone in the park.$q$, $q$O cachorro vira-lata não ameaça ninguém no parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Incite$q$, $q$incitar$q$, $q$The speech seems designed to incite unrest.$q$, $q$O discurso parece feito para incitar agitação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Entice$q$, $q$aliciar$q$, $q$The store uses discounts to entice new customers.$q$, $q$A loja usa descontos para aliciar novos clientes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lure$q$, $q$atrair com isca$q$, $q$Fishermen use bright bait to lure the fish.$q$, $q$Pescadores usam isca brilhante para atrair os peixes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dissuade$q$, $q$dissuadir$q$, $q$Nothing can dissuade her from taking the trip.$q$, $q$Nada consegue dissuadi-la de fazer a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Coax$q$, $q$persuadir com jeito$q$, $q$She manages, with patience, to coax the shy cat out from under the bed.$q$, $q$Ela consegue, com paciência, persuadir o gato tímido a sair de debaixo da cama.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Demolish$q$, $q$demolir$q$, $q$The city plans to demolish the old stadium.$q$, $q$A cidade planeja demolir o estádio antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Devastate$q$, $q$devastar$q$, $q$This kind of flood can devastate an entire village.$q$, $q$Esse tipo de enchente pode devastar uma vila inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Annihilate$q$, $q$aniquilar$q$, $q$The army threatens to annihilate the enemy forces.$q$, $q$O exército ameaça aniquilar as forças inimigas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Restore$q$, $q$restaurar$q$, $q$The museum works to restore the damaged painting.$q$, $q$O museu trabalha para restaurar a pintura danificada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mend$q$, $q$remendar tecido$q$, $q$She sits by the window to mend an old sweater.$q$, $q$Ela senta perto da janela para remendar um suéter velho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Patch$q$, $q$tapar buraco$q$, $q$He grabs some tape to patch the hole in the tent.$q$, $q$Ele pega fita para tapar o buraco na barraca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rebuild$q$, $q$reconstruir$q$, $q$The town works together to rebuild after the storm.$q$, $q$A cidade trabalha em conjunto para reconstruir depois da tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Shatter$q$, $q$despedaçar$q$, $q$I watch the glass fall and shatter on the floor.$q$, $q$Eu vejo o vidro cair e se despedaçar no chão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Erode$q$, $q$corroer aos poucos$q$, $q$The constant waves erode the cliff over decades.$q$, $q$As ondas constantes corroem o penhasco ao longo de décadas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ignite$q$, $q$incendiar$q$, $q$A single spark can ignite the dry grass.$q$, $q$Uma única faísca pode incendiar a grama seca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Possess$q$, $q$possuir$q$, $q$I possess a rare talent for painting.$q$, $q$Eu possuo um talento raro para pintura.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Grant$q$, $q$outorgar$q$, $q$The university decides to grant her a full scholarship.$q$, $q$A universidade decide outorgar a ela uma bolsa integral.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Donate$q$, $q$doar$q$, $q$They donate their old clothes to the shelter.$q$, $q$Eles doam as roupas velhas deles para o abrigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Confiscate$q$, $q$confiscar$q$, $q$I watch security confiscate the sharp object at the gate.$q$, $q$Eu vejo a segurança confiscar o objeto afiado no portão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Plunder$q$, $q$saquear$q$, $q$Pirates plunder the small coastal town.$q$, $q$Piratas saqueiam a pequena cidade litorânea.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Barter$q$, $q$trocar mercadorias$q$, $q$Villagers barter grain for tools at the market.$q$, $q$Aldeões trocam grãos por ferramentas no mercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Haggle$q$, $q$pechinchar$q$, $q$Tourists haggle over the price of the souvenir.$q$, $q$Turistas pechincham pelo preço da lembrancinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lease$q$, $q$arrendar$q$, $q$The company decides to lease the office space instead of buying it.$q$, $q$A empresa decide arrendar o espaço do escritório em vez de comprá-lo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Withhold$q$, $q$reter$q$, $q$The landlord agrees not to withhold the deposit.$q$, $q$O senhorio concorda em não reter o depósito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Allocate$q$, $q$destinar recursos$q$, $q$The city plans to allocate more funds to schools.$q$, $q$A cidade planeja destinar mais recursos às escolas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scarce$q$, $q$escasso$q$, $q$Clean water becomes scarce during the drought.$q$, $q$Água limpa se torna escassa durante a seca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Plentiful$q$, $q$abundante$q$, $q$Fish are plentiful in this part of the river.$q$, $q$Peixes são abundantes nesta parte do rio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Negligible$q$, $q$ínfimo$q$, $q$The difference in price is negligible this month.$q$, $q$A diferença de preço é ínfima este mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Considerable$q$, $q$considerável$q$, $q$The renovation costs a considerable amount of money.$q$, $q$A reforma custa uma quantia considerável de dinheiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Infinite$q$, $q$infinito$q$, $q$The universe seems infinite in every direction.$q$, $q$O universo parece infinito em todas as direções.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Minimal$q$, $q$mínimo$q$, $q$The changes to the design are minimal this time.$q$, $q$As mudanças no design são mínimas desta vez.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Excessive$q$, $q$excessivo$q$, $q$His spending seems excessive for a student budget.$q$, $q$Os gastos dele parecem excessivos para um orçamento de estudante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Moderate$q$, $q$moderado$q$, $q$She prefers a moderate amount of spice in her food.$q$, $q$Ela prefere uma quantidade moderada de tempero na comida dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sparse$q$, $q$esparso$q$, $q$Vegetation is sparse in this part of the desert.$q$, $q$A vegetação é esparsa nesta parte do deserto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dense$q$, $q$denso$q$, $q$The forest becomes very dense near the river.$q$, $q$A floresta fica muito densa perto do rio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Transition$q$, $q$transição$q$, $q$The company plans a smooth transition to the new system.$q$, $q$A empresa planeja uma transição tranquila para o novo sistema.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rupture$q$, $q$ruptura$q$, $q$The pipe suffers a sudden rupture underground.$q$, $q$O cano sofre uma ruptura repentina no subsolo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Catastrophe$q$, $q$catástrofe$q$, $q$The oil spill turns into an environmental catastrophe.$q$, $q$O vazamento de óleo se transforma numa catástrofe ambiental.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Outbreak$q$, $q$surto$q$, $q$Health officials respond quickly to the outbreak.$q$, $q$Autoridades de saúde respondem rapidamente ao surto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Exodus$q$, $q$êxodo$q$, $q$The war triggers a massive exodus from the region.$q$, $q$A guerra provoca um êxodo massivo da região.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Uprising$q$, $q$levante popular$q$, $q$The uprising spreads across several cities.$q$, $q$O levante popular se espalha por várias cidades.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Breakthrough$q$, $q$grande avanço$q$, $q$Researchers announce a major breakthrough in cancer treatment.$q$, $q$Pesquisadores anunciam um grande avanço no tratamento do câncer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stagnation$q$, $q$estagnação$q$, $q$The economy suffers years of stagnation.$q$, $q$A economia sofre anos de estagnação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rally$q$, $q$reação de mercado$q$, $q$The stock market shows a strong rally this week.$q$, $q$O mercado de ações mostra uma forte reação esta semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Upheaval$q$, $q$convulsão social$q$, $q$The country experiences a period of political upheaval.$q$, $q$O país vive um período de convulsão social e política.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Excursion$q$, $q$excursão$q$, $q$The school organizes an excursion to the museum.$q$, $q$A escola organiza uma excursão ao museu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cruise$q$, $q$cruzeiro marítimo$q$, $q$They book a cruise around the Mediterranean.$q$, $q$Eles reservam um cruzeiro pelo Mediterrâneo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Resort$q$, $q$balneário$q$, $q$The family spends a week at a beach resort.$q$, $q$A família passa uma semana num balneário à beira-mar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hostel$q$, $q$albergue$q$, $q$Backpackers often stay at a cheap hostel.$q$, $q$Mochileiros costumam ficar num albergue barato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lodge$q$, $q$pousada de campo$q$, $q$They rent a small lodge near the ski slopes.$q$, $q$Eles alugam uma pousada pequena perto das pistas de esqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tour$q$, $q$visita guiada$q$, $q$The guide leads a tour through the old city.$q$, $q$O guia conduz uma visita guiada pela cidade antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Layover$q$, $q$escala longa$q$, $q$Their flight includes a long layover in Lisbon.$q$, $q$O voo deles inclui uma escala longa em Lisboa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Backpacker$q$, $q$mochileiro$q$, $q$A young backpacker checks into the hostel.$q$, $q$Um mochileiro jovem se registra no albergue.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Landmark$q$, $q$ponto turístico$q$, $q$The tower is the city's most famous landmark.$q$, $q$A torre é o ponto turístico mais famoso da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Commuter$q$, $q$viajante diário$q$, $q$Every commuter waits for the same morning train.$q$, $q$Todo viajante diário espera pelo mesmo trem da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dissertation$q$, $q$dissertação$q$, $q$She defends her dissertation next month.$q$, $q$Ela defende a dissertação dela no próximo mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Advisor$q$, $q$orientador acadêmico$q$, $q$Her advisor reviews the thesis before submission.$q$, $q$O orientador acadêmico dela revisa a tese antes do envio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Syllabus$q$, $q$ementa$q$, $q$The professor hands out the syllabus on the first day.$q$, $q$O professor distribui a ementa no primeiro dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Doctorate$q$, $q$doutorado$q$, $q$He earns his doctorate after six years of research.$q$, $q$Ele obtém o doutorado dele depois de seis anos de pesquisa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scholar$q$, $q$acadêmico erudito$q$, $q$The scholar publishes a new book on ancient history.$q$, $q$O acadêmico erudito publica um livro novo sobre história antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fellow$q$, $q$bolsista de pesquisa$q$, $q$She becomes a research fellow at the university.$q$, $q$Ela se torna bolsista de pesquisa na universidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Panel$q$, $q$banca examinadora$q$, $q$The panel asks tough questions during the defense.$q$, $q$A banca examinadora faz perguntas difíceis durante a defesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Journal$q$, $q$periódico científico$q$, $q$The study appears in a respected scientific journal.$q$, $q$O estudo aparece num periódico científico respeitado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Citation$q$, $q$citação bibliográfica$q$, $q$Every claim in the paper needs a proper citation.$q$, $q$Toda alegação no artigo precisa de uma citação bibliográfica apropriada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Critique$q$, $q$resenha crítica$q$, $q$The professor writes a detailed critique of the essay.$q$, $q$O professor escreve uma resenha crítica detalhada do ensaio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gleaming$q$, $q$reluzente$q$, $q$The gleaming floor reflects the morning light.$q$, $q$O chão reluzente reflete a luz da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sparkling$q$, $q$cintilante$q$, $q$The sparkling water catches everyone's attention.$q$, $q$A água cintilante chama a atenção de todos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Opaque$q$, $q$opaco$q$, $q$The glass becomes opaque after years in the sun.$q$, $q$O vidro fica opaco depois de anos no sol.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Translucent$q$, $q$translúcido$q$, $q$The curtain lets in light while staying translucent.$q$, $q$A cortina deixa a luz entrar enquanto permanece translúcida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vivid$q$, $q$vívido$q$, $q$She paints the sunset in vivid colors.$q$, $q$Ela pinta o pôr do sol em cores vívidas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Opalescent$q$, $q$furta-cor$q$, $q$The shell has an opalescent shine under the light.$q$, $q$A concha tem um brilho furta-cor sob a luz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Radiant$q$, $q$resplandecente$q$, $q$The bride looks radiant on her wedding day.$q$, $q$A noiva parece resplandecente no dia do casamento dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Murky$q$, $q$turvo$q$, $q$The murky water hides the bottom of the lake.$q$, $q$A água turva esconde o fundo do lago.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Overcast$q$, $q$encoberto de nuvens$q$, $q$The sky stays overcast for most of the trip.$q$, $q$O céu permanece encoberto de nuvens durante a maior parte da viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dim$q$, $q$pouco iluminado$q$, $q$The room feels dim without the lamp.$q$, $q$O quarto parece pouco iluminado sem a lâmpada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Buzz$q$, $q$zumbido$q$, $q$The buzz of the bees fills the garden.$q$, $q$O zumbido das abelhas preenche o jardim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Creak$q$, $q$rangido$q$, $q$Every step causes a creak in the old floor.$q$, $q$Cada passo causa um rangido no chão velho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hiss$q$, $q$chiado$q$, $q$The snake lets out a warning hiss.$q$, $q$A cobra solta um chiado de aviso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chirp$q$, $q$gorjeio$q$, $q$The chirp of the birds wakes her up early.$q$, $q$O gorjeio dos pássaros a acorda cedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Howl$q$, $q$uivo$q$, $q$The wolf's howl echoes through the valley.$q$, $q$O uivo do lobo ecoa pelo vale.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Crack$q$, $q$estalo seco$q$, $q$A loud crack breaks the silence of the forest.$q$, $q$Um estalo seco alto quebra o silêncio da floresta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Resonance$q$, $q$ressonância$q$, $q$The singer's voice has a deep resonance in the hall.$q$, $q$A voz do cantor tem uma ressonância profunda no salão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hum$q$, $q$zunido constante$q$, $q$The hum of the engine fills the quiet garage.$q$, $q$O zunido do motor preenche a garagem silenciosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Jingle$q$, $q$tilintar$q$, $q$The jingle of her keys announces her arrival.$q$, $q$O tilintar das chaves dela anuncia a chegada dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Murmur$q$, $q$murmúrio$q$, $q$A soft murmur spreads through the crowd.$q$, $q$Um murmúrio suave se espalha pela multidão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Caress$q$, $q$acariciar$q$, $q$I gently caress the sleeping baby's cheek.$q$, $q$Eu acaricio suavemente a bochecha do bebê que dorme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lick$q$, $q$lamber$q$, $q$My dog likes to lick my hand every morning.$q$, $q$Meu cachorro gosta de lamber minha mão toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Palpate$q$, $q$apalpar$q$, $q$I palpate the patient's abdomen carefully.$q$, $q$Eu apalpo o abdômen do paciente com cuidado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stroke$q$, $q$afagar$q$, $q$I stroke the cat until it falls asleep.$q$, $q$Eu afago o gato até ele dormir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nudge$q$, $q$empurrar de leve$q$, $q$I nudge my friend to point out the mistake.$q$, $q$Eu empurro de leve meu amigo para apontar o erro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fumble$q$, $q$tatear$q$, $q$I fumble for the light switch in the dark.$q$, $q$Eu tateio pelo interruptor de luz no escuro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Compress$q$, $q$comprimir$q$, $q$I compress the wound with a clean cloth.$q$, $q$Eu comprimo o ferimento com um pano limpo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scrape$q$, $q$raspar$q$, $q$I scrape the old paint off the wall.$q$, $q$Eu raspo a tinta velha da parede.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scratch$q$, $q$arranhar$q$, $q$My cat likes to scratch the post instead of the sofa.$q$, $q$Meu gato gosta de arranhar o arranhador em vez do sofá.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tickle$q$, $q$fazer cócegas$q$, $q$I tickle the baby until he laughs.$q$, $q$Eu faço cócegas no bebê até ele rir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
