-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote6.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deposit$q$, $q$caução$q$, $q$The landlord asks for a deposit before signing the lease.$q$, $q$O senhorio pede uma caução antes de assinar o contrato de aluguel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Foreclosure$q$, $q$penhora$q$, $q$The bank begins foreclosure proceedings on the property.$q$, $q$O banco inicia o processo de penhora sobre o imóvel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Usury$q$, $q$usura$q$, $q$The old law strictly forbids usury on personal loans.$q$, $q$A lei antiga proíbe rigorosamente a usura em empréstimos pessoais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Insolvency$q$, $q$insolvência$q$, $q$The firm files for insolvency after years of losses.$q$, $q$A firma declara insolvência depois de anos de prejuízo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Arbitration$q$, $q$arbitragem$q$, $q$The two companies settle the dispute through arbitration.$q$, $q$As duas empresas resolvem a disputa por meio de arbitragem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Enforcement$q$, $q$execução forçada$q$, $q$Strict enforcement of the contract prevents future disputes.$q$, $q$A execução forçada rigorosa do contrato evita disputas futuras.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Termination$q$, $q$rescisão de contrato$q$, $q$The contract allows termination with thirty days' notice.$q$, $q$O contrato permite rescisão com aviso de trinta dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Liquidation$q$, $q$liquidação de empresa$q$, $q$Shareholders vote in favor of liquidation.$q$, $q$Os acionistas votam a favor da liquidação da empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Collateral$q$, $q$garantia colateral$q$, $q$The bank requires collateral to approve the loan.$q$, $q$O banco exige garantia colateral para aprovar o empréstimo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Guarantor$q$, $q$avalista$q$, $q$Her father agrees to act as guarantor for the loan.$q$, $q$O pai dela concorda em atuar como avalista do empréstimo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lethargy$q$, $q$letargia$q$, $q$A strange lethargy takes over him after lunch.$q$, $q$Uma letargia estranha toma conta dele depois do almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Apathy$q$, $q$apatia$q$, $q$Voter apathy leads to a record low turnout.$q$, $q$A apatia dos eleitores leva a um comparecimento recorde baixo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Craving$q$, $q$ânsia$q$, $q$She feels a sudden craving for something sweet.$q$, $q$Ela sente uma ânsia repentina por algo doce.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Jubilation$q$, $q$regozijo$q$, $q$Jubilation fills the stadium after the final goal.$q$, $q$Regozijo toma conta do estádio depois do gol final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Resignation$q$, $q$resignação$q$, $q$He accepts the outcome with quiet resignation.$q$, $q$Ele aceita o resultado com resignação silenciosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Distress$q$, $q$aflição$q$, $q$The captain signals distress after the engine fails.$q$, $q$O capitão sinaliza aflição depois que o motor falha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Remorse$q$, $q$remorso$q$, $q$She shows genuine remorse for the mistake.$q$, $q$Ela demonstra remorso genuíno pelo erro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hubris$q$, $q$arrogância excessiva$q$, $q$His hubris eventually leads to his downfall.$q$, $q$A arrogância excessiva dele acaba levando à queda dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Zeal$q$, $q$zelo$q$, $q$He pursues the project with remarkable zeal.$q$, $q$Ele persegue o projeto com um zelo notável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Contempt$q$, $q$desprezo$q$, $q$She looks at the proposal with open contempt.$q$, $q$Ela encara a proposta com desprezo aberto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Perennial$q$, $q$perene$q$, $q$Water shortage remains a perennial issue in this region.$q$, $q$A escassez de água continua sendo um problema perene nesta região.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fleeting$q$, $q$fugaz$q$, $q$Fame in this business can be fleeting.$q$, $q$A fama neste ramo pode ser fugaz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inexorable$q$, $q$inexorável$q$, $q$The company faces the inexorable decline of the industry.$q$, $q$A empresa enfrenta o declínio inexorável da indústria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Insidious$q$, $q$insidioso$q$, $q$The disease spreads in an insidious way.$q$, $q$A doença se espalha de forma insidiosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Laconic$q$, $q$lacônico$q$, $q$His laconic reply leaves everyone confused.$q$, $q$A resposta lacônica dele deixa todo mundo confuso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Verbose$q$, $q$prolixo$q$, $q$The report feels too verbose for a short summary.$q$, $q$O relatório parece prolixo demais para um resumo curto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Illusory$q$, $q$ilusório$q$, $q$The sudden growth turns out to be illusory.$q$, $q$O crescimento repentino acaba se revelando ilusório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Impassive$q$, $q$impassível$q$, $q$The judge remains impassive throughout the trial.$q$, $q$O juiz permanece impassível durante todo o julgamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Intrepid$q$, $q$intrépido$q$, $q$The intrepid climbers reach the summit before dawn.$q$, $q$Os alpinistas intrépidos alcançam o cume antes do amanhecer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nonchalant$q$, $q$displicente$q$, $q$He stays nonchalant even after the bad news.$q$, $q$Ele permanece displicente mesmo depois da má notícia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cardiology$q$, $q$cardiologia$q$, $q$She specializes in cardiology after medical school.$q$, $q$Ela se especializa em cardiologia depois da faculdade de medicina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Neurology$q$, $q$neurologia$q$, $q$He studies neurology to understand memory loss.$q$, $q$Ele estuda neurologia para entender a perda de memória.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Oncology$q$, $q$oncologia$q$, $q$The hospital opens a new oncology wing this year.$q$, $q$O hospital abre uma nova ala de oncologia este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pediatrics$q$, $q$pediatria$q$, $q$She chooses pediatrics because she loves working with children.$q$, $q$Ela escolhe pediatria porque adora trabalhar com crianças.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dermatology$q$, $q$dermatologia$q$, $q$He visits a dermatology clinic for the rash on his arm.$q$, $q$Ele visita uma clínica de dermatologia por causa da irritação no braço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Orthopedics$q$, $q$ortopedia$q$, $q$The clinic specializes in orthopedics and sports injuries.$q$, $q$A clínica se especializa em ortopedia e lesões esportivas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Psychiatry$q$, $q$psiquiatria$q$, $q$She studies psychiatry to help patients with anxiety.$q$, $q$Ela estuda psiquiatria para ajudar pacientes com ansiedade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Surgeon$q$, $q$cirurgião$q$, $q$The surgeon operates on the patient for six hours.$q$, $q$O cirurgião opera o paciente por seis horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Radiograph$q$, $q$radiografia$q$, $q$The radiograph reveals a small fracture in his wrist.$q$, $q$A radiografia revela uma fratura pequena no pulso dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Biopsy$q$, $q$biópsia$q$, $q$The doctor orders a biopsy to confirm the diagnosis.$q$, $q$O médico solicita uma biópsia para confirmar o diagnóstico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Orbit$q$, $q$órbita$q$, $q$The satellite enters orbit around the planet.$q$, $q$O satélite entra em órbita ao redor do planeta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Singularity$q$, $q$singularidade$q$, $q$Scientists debate the physics of a gravitational singularity.$q$, $q$Cientistas debatem a física de uma singularidade gravitacional.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Solstice$q$, $q$solstício$q$, $q$The village celebrates the summer solstice every year.$q$, $q$A vila comemora o solstício de verão todo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Constellation$q$, $q$constelação$q$, $q$He points to a bright constellation in the night sky.$q$, $q$Ele aponta para uma constelação brilhante no céu noturno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nebula$q$, $q$nebulosa$q$, $q$The telescope captures a stunning image of the nebula.$q$, $q$O telescópio captura uma imagem impressionante da nebulosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Telescope$q$, $q$telescópio$q$, $q$She looks at the stars through a small telescope.$q$, $q$Ela observa as estrelas através de um telescópio pequeno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Liftoff$q$, $q$lançamento de foguete$q$, $q$The crowd cheers moments before liftoff.$q$, $q$A multidão comemora instantes antes do lançamento do foguete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rocket$q$, $q$foguete$q$, $q$The rocket reaches orbit within minutes.$q$, $q$O foguete alcança a órbita em poucos minutos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Satellite$q$, $q$satélite$q$, $q$The company launches a new communications satellite.$q$, $q$A empresa lança um novo satélite de comunicações.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Atmosphere$q$, $q$atmosfera$q$, $q$The spacecraft burns up entering the atmosphere.$q$, $q$A nave espacial se incendeia ao entrar na atmosfera.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Eruption$q$, $q$erupção$q$, $q$The volcanic eruption forces thousands to evacuate.$q$, $q$A erupção vulcânica obriga milhares a evacuar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Silt$q$, $q$depósito de rio$q$, $q$Silt builds up along the riverbank every spring.$q$, $q$Sedimento se acumula ao longo da margem do rio toda primavera.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Grotto$q$, $q$gruta calcária$q$, $q$Tourists explore the limestone grotto by candlelight.$q$, $q$Turistas exploram a gruta calcária à luz de velas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Erosion$q$, $q$erosão$q$, $q$Coastal erosion threatens several homes this year.$q$, $q$A erosão costeira ameaça várias casas este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vent$q$, $q$boca de vulcão$q$, $q$Smoke rises steadily from the volcano's vent.$q$, $q$Fumaça sobe constantemente da boca do vulcão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stratum$q$, $q$camada rochosa$q$, $q$Geologists study each stratum of rock closely.$q$, $q$Geólogos estudam cada camada rochosa de perto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Limestone$q$, $q$calcário$q$, $q$The cathedral is built entirely from limestone.$q$, $q$A catedral é construída inteiramente de calcário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Granite$q$, $q$granito$q$, $q$The kitchen counter is made of polished granite.$q$, $q$A bancada da cozinha é feita de granito polido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Quake$q$, $q$abalo sísmico$q$, $q$A sudden quake shakes the entire building.$q$, $q$Um abalo sísmico repentino sacode o prédio inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fault$q$, $q$falha geológica$q$, $q$Scientists monitor the fault for signs of activity.$q$, $q$Cientistas monitoram a falha geológica em busca de sinais de atividade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Velvet$q$, $q$veludo$q$, $q$She wears a dress made of deep red velvet.$q$, $q$Ela usa um vestido feito de veludo vermelho escuro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Linen$q$, $q$linho$q$, $q$He prefers linen shirts during the summer.$q$, $q$Ele prefere camisas de linho durante o verão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Satin$q$, $q$cetim$q$, $q$The pillow is covered with smooth satin.$q$, $q$O travesseiro é coberto com cetim macio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ribbon$q$, $q$fita decorativa$q$, $q$She ties the gift with a bright red ribbon.$q$, $q$Ela amarra o presente com uma fita vermelha vistosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Embroidery$q$, $q$bordado$q$, $q$The dress features delicate floral embroidery.$q$, $q$O vestido apresenta um bordado floral delicado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cloak$q$, $q$manto$q$, $q$The traveler wears a heavy cloak against the cold.$q$, $q$O viajante usa um manto pesado contra o frio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tunic$q$, $q$túnica$q$, $q$The actor wears a simple tunic in the historical play.$q$, $q$O ator usa uma túnica simples na peça histórica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Corset$q$, $q$espartilho$q$, $q$The museum displays a Victorian corset from 1890.$q$, $q$O museu exibe um espartilho vitoriano de 1890.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Headband$q$, $q$faixa de cabeça$q$, $q$She wears a headband to keep her hair back.$q$, $q$Ela usa uma faixa de cabeça para prender o cabelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Shawl$q$, $q$xale$q$, $q$Her grandmother knits her a warm shawl.$q$, $q$A avó dela tricota um xale quente para ela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blacksmith$q$, $q$ferreiro$q$, $q$The blacksmith hammers the metal into shape.$q$, $q$O ferreiro martela o metal até dar forma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Weaver$q$, $q$tecelão$q$, $q$The weaver spends weeks finishing the rug.$q$, $q$O tecelão passa semanas terminando o tapete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Potter$q$, $q$oleiro$q$, $q$The potter shapes the clay on the wheel.$q$, $q$O oleiro molda o barro na roda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tailor$q$, $q$alfaiate$q$, $q$The tailor adjusts the suit before the wedding.$q$, $q$O alfaiate ajusta o terno antes do casamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cobbler$q$, $q$sapateiro$q$, $q$The cobbler repairs old shoes in his small shop.$q$, $q$O sapateiro conserta sapatos velhos na loja pequena dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Goldsmith$q$, $q$ourives$q$, $q$The goldsmith crafts a delicate ring for the couple.$q$, $q$O ourives fabrica um anel delicado para o casal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Miller$q$, $q$moleiro$q$, $q$The miller grinds the wheat into fine flour.$q$, $q$O moleiro mói o trigo até virar farinha fina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Brewer$q$, $q$cervejeiro$q$, $q$The local brewer launches a new craft beer.$q$, $q$O cervejeiro local lança uma cerveja artesanal nova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Archer$q$, $q$arqueiro$q$, $q$The archer hits the target three times in a row.$q$, $q$O arqueiro acerta o alvo três vezes seguidas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mason$q$, $q$pedreiro de alvenaria$q$, $q$The mason builds a solid wall in two days.$q$, $q$O pedreiro constrói uma parede sólida em dois dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Freight$q$, $q$frete$q$, $q$The company ships the freight by train.$q$, $q$A empresa transporta o frete de trem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cargo$q$, $q$carga de navio$q$, $q$The ship carries a full load of cargo.$q$, $q$O navio carrega uma carga completa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Warehouse$q$, $q$armazém$q$, $q$Workers store the boxes in a large warehouse.$q$, $q$Trabalhadores guardam as caixas num armazém grande.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Quay$q$, $q$cais$q$, $q$The boat docks at the quay before sunset.$q$, $q$O barco atraca no cais antes do pôr do sol.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Depot$q$, $q$entreposto$q$, $q$Trucks load supplies at the central depot.$q$, $q$Caminhões carregam suprimentos no entreposto central.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Route$q$, $q$rota$q$, $q$The driver takes a shorter route to avoid traffic.$q$, $q$O motorista pega uma rota mais curta para evitar trânsito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dispatch$q$, $q$despacho$q$, $q$The company sends the dispatch early this morning.$q$, $q$A empresa envia o despacho logo pela manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Convoy$q$, $q$comboio$q$, $q$A military convoy passes through the small town.$q$, $q$Um comboio militar passa pela cidade pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rail$q$, $q$trilho$q$, $q$The train stays firmly on the rail during the turn.$q$, $q$O trem permanece firme no trilho durante a curva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Locomotive$q$, $q$locomotiva$q$, $q$The old locomotive pulls twenty cars behind it.$q$, $q$A locomotiva antiga puxa vinte vagões atrás dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$List$q$, $q$listar$q$, $q$I meticulously list every task before the project begins.$q$, $q$Eu listo meticulosamente cada tarefa antes do projeto começar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Classify$q$, $q$classificar$q$, $q$I classify the documents according to their level of confidentiality.$q$, $q$Eu classifico os documentos de acordo com o nível de confidencialidade deles.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Compile$q$, $q$compilar$q$, $q$I compile the scattered findings into a coherent report.$q$, $q$Eu compilo os achados dispersos num relatório coerente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Archive$q$, $q$arquivar$q$, $q$I archive the outdated records to comply with company policy.$q$, $q$Eu arquivo os registros desatualizados para cumprir a política da empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sort$q$, $q$ordenar$q$, $q$I sort the applicants by qualification before the interview.$q$, $q$Eu ordeno os candidatos por qualificação antes da entrevista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Categorize$q$, $q$categorizar$q$, $q$I categorize the complaints by urgency and department.$q$, $q$Eu categorizo as reclamações por urgência e departamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cluster$q$, $q$agrupar$q$, $q$I cluster the data points to reveal a hidden pattern.$q$, $q$Eu agrupo os pontos de dados para revelar um padrão oculto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Filter$q$, $q$filtrar$q$, $q$I filter out the irrelevant data before the analysis.$q$, $q$Eu filtro os dados irrelevantes antes da análise.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Number$q$, $q$numerar$q$, $q$I number each clause in the contract for easy reference.$q$, $q$Eu numero cada cláusula do contrato para facilitar a referência.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tabulate$q$, $q$tabular$q$, $q$I tabulate the survey responses to identify emerging trends.$q$, $q$Eu tabulo as respostas da pesquisa para identificar tendências emergentes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
