-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote3.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Trial$q$, $q$teste científico$q$, $q$The team runs a trial before the product launch.$q$, $q$A equipe faz um teste antes do lançamento do produto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hypothesis$q$, $q$hipótese$q$, $q$The scientist tests her hypothesis carefully.$q$, $q$A cientista testa a hipótese dela com cuidado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Discovery$q$, $q$descoberta$q$, $q$This discovery changes modern medicine.$q$, $q$Esta descoberta muda a medicina moderna.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Laboratory$q$, $q$laboratório$q$, $q$They work in a small laboratory.$q$, $q$Eles trabalham num laboratório pequeno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Atom$q$, $q$átomo$q$, $q$An atom contains protons and electrons.$q$, $q$Um átomo contém prótons e elétrons.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gravity$q$, $q$gravidade$q$, $q$Gravity keeps our feet on the ground.$q$, $q$A gravidade mantém nossos pés no chão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Evolution$q$, $q$evolução$q$, $q$The book explains the theory of evolution.$q$, $q$O livro explica a teoria da evolução.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cell$q$, $q$célula$q$, $q$A cell is the basic unit of life.$q$, $q$Uma célula é a unidade básica da vida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Galaxy$q$, $q$galáxia$q$, $q$Our galaxy has billions of stars.$q$, $q$Nossa galáxia tem bilhões de estrelas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Formula$q$, $q$fórmula$q$, $q$She writes the formula on the board.$q$, $q$Ela escreve a fórmula no quadro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tournament$q$, $q$torneio$q$, $q$Our school wins the tournament this year.$q$, $q$Nossa escola vence o torneio este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Referee$q$, $q$árbitro$q$, $q$The referee stops the game.$q$, $q$O árbitro interrompe o jogo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fans$q$, $q$torcida$q$, $q$Thousands of fans fill the stadium.$q$, $q$Milhares de torcedores lotam o estádio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Penalty$q$, $q$pênalti$q$, $q$The team scores from a penalty.$q$, $q$O time marca a partir de um pênalti.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Whistle$q$, $q$apito$q$, $q$The coach blows the whistle to start practice.$q$, $q$O treinador apita para começar o treino.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jersey$q$, $q$uniforme esportivo$q$, $q$He wears his team's jersey with pride.$q$, $q$Ele usa o uniforme do time dele com orgulho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sprain$q$, $q$torção$q$, $q$She has a sprain in her ankle.$q$, $q$Ela tem uma torção no tornozelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Milestone$q$, $q$marco histórico$q$, $q$Winning the title is a big milestone.$q$, $q$Vencer o título é um grande marco histórico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Championship$q$, $q$campeonato$q$, $q$They compete in the national championship.$q$, $q$Eles competem no campeonato nacional.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Performance$q$, $q$desempenho$q$, $q$His performance improves every match.$q$, $q$O desempenho dele melhora a cada partida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Painting$q$, $q$pintura$q$, $q$This painting hangs in the museum.$q$, $q$Esta pintura fica exposta no museu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sculpture$q$, $q$escultura$q$, $q$The sculpture stands in the town square.$q$, $q$A escultura fica na praça da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Exhibition$q$, $q$exposição de arte$q$, $q$We visit an art exhibition downtown.$q$, $q$Nós visitamos uma exposição de arte no centro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gallery$q$, $q$galeria$q$, $q$The gallery shows local artists.$q$, $q$A galeria exibe artistas locais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Audience$q$, $q$plateia$q$, $q$The audience applauds at the end.$q$, $q$A plateia aplaude no final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rehearsal$q$, $q$ensaio de teatro$q$, $q$The actors have a rehearsal every evening.$q$, $q$Os atores têm um ensaio de teatro toda noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Screenplay$q$, $q$roteiro de filme$q$, $q$She writes the screenplay for the film.$q$, $q$Ela escreve o roteiro do filme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Scenery$q$, $q$cenário de teatro$q$, $q$The scenery on stage looks realistic.$q$, $q$O cenário de teatro parece realista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Heritage$q$, $q$patrimônio cultural$q$, $q$This building is part of our heritage.$q$, $q$Este prédio faz parte do nosso patrimônio cultural.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tradition$q$, $q$tradição$q$, $q$The festival is a family tradition.$q$, $q$O festival é uma tradição de família.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Melody$q$, $q$melodia$q$, $q$I remember the melody of that song.$q$, $q$Eu lembro a melodia daquela canção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rhythm$q$, $q$ritmo$q$, $q$The song has a fast rhythm.$q$, $q$A música tem um ritmo rápido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lyrics$q$, $q$letra de música$q$, $q$She writes the lyrics for a new song.$q$, $q$Ela escreve a letra de uma nova música.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Chorus$q$, $q$refrão$q$, $q$Everyone sings the chorus together.$q$, $q$Todo mundo canta o refrão junto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Guitar$q$, $q$violão$q$, $q$He plays the guitar at the party.$q$, $q$Ele toca violão na festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Drum$q$, $q$tambor$q$, $q$The drum sets the beat for the band.$q$, $q$O tambor marca o ritmo para a banda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Orchestra$q$, $q$orquestra$q$, $q$The orchestra performs a famous symphony.$q$, $q$A orquestra executa uma sinfonia famosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Concert$q$, $q$show ao vivo$q$, $q$We buy tickets for the concert tonight.$q$, $q$Nós compramos ingressos para o show desta noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Composer$q$, $q$compositor$q$, $q$The composer writes music for films.$q$, $q$O compositor escreve música para filmes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Chord$q$, $q$acorde$q$, $q$She practices a new chord on the piano.$q$, $q$Ela pratica um novo acorde no piano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Predator$q$, $q$predador$q$, $q$A predator hunts other animals for food.$q$, $q$Um predador caça outros animais para se alimentar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Prey$q$, $q$presa de caça$q$, $q$The lion looks for its prey at night.$q$, $q$O leão procura a presa dele à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Herd$q$, $q$rebanho$q$, $q$A herd of cows crosses the road.$q$, $q$Um rebanho de vacas atravessa a estrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Beehive$q$, $q$colmeia$q$, $q$The beehive produces a lot of honey.$q$, $q$A colmeia produz muito mel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cub$q$, $q$filhote de leão$q$, $q$The lion cub follows its mother closely.$q$, $q$O filhote de leão segue a mãe de perto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Flock$q$, $q$bando de aves$q$, $q$A flock of birds flies south for winter.$q$, $q$Um bando de aves voa para o sul no inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shoal$q$, $q$cardume$q$, $q$A shoal of fish swims near the boat.$q$, $q$Um cardume de peixes nada perto do barco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Swarm$q$, $q$enxame$q$, $q$A swarm of bees surrounds the tree.$q$, $q$Um enxame de abelhas cerca a árvore.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Claw$q$, $q$garra$q$, $q$The cat uses its claw to climb.$q$, $q$O gato usa a garra para escalar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hibernate$q$, $q$hibernar$q$, $q$Bears hibernate during the winter.$q$, $q$Ursos hibernam durante o inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Forecast$q$, $q$previsão do tempo$q$, $q$The forecast predicts rain tomorrow.$q$, $q$A previsão do tempo prevê chuva amanhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Drizzle$q$, $q$garoa$q$, $q$A light drizzle falls all morning.$q$, $q$Uma garoa leve cai a manhã toda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mist$q$, $q$nevoeiro$q$, $q$Mist covers the valley at dawn.$q$, $q$Uma neblina cobre o vale ao amanhecer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gale$q$, $q$ventania$q$, $q$A gale damages the roof of the house.$q$, $q$Uma ventania danifica o telhado da casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Heatwave$q$, $q$onda de calor$q$, $q$The heatwave lasts for a whole week.$q$, $q$A onda de calor dura uma semana inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Frost$q$, $q$geada$q$, $q$Frost covers the grass this morning.$q$, $q$A geada cobre a grama esta manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hail$q$, $q$granizo$q$, $q$Hail falls during the sudden storm.$q$, $q$Granizo cai durante a tempestade repentina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Humidity$q$, $q$umidade$q$, $q$The humidity makes the air feel heavy.$q$, $q$A umidade faz o ar parecer pesado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Flash$q$, $q$clarão$q$, $q$A flash of lightning lights up the sky.$q$, $q$Um clarão de raio ilumina o céu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Downpour$q$, $q$chuvarada$q$, $q$We get caught in a sudden downpour.$q$, $q$Nós ficamos pegos numa chuvarada repentina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Friendship$q$, $q$amizade$q$, $q$Their friendship lasts for many years.$q$, $q$A amizade deles dura muitos anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dating$q$, $q$namoro$q$, $q$They have been dating for six months.$q$, $q$Eles estão namorando há seis meses.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Divorce$q$, $q$divórcio$q$, $q$They finalize their divorce this year.$q$, $q$Eles finalizam o divórcio este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fiance$q$, $q$noivo$q$, $q$She introduces her fiance to the family.$q$, $q$Ela apresenta o noivo dela para a família.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Relative$q$, $q$parente$q$, $q$Every relative comes to the party.$q$, $q$Todo parente vem à festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Godfather$q$, $q$padrinho$q$, $q$He asks his brother to be the godfather.$q$, $q$Ele pede para o irmão ser o padrinho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stepmother$q$, $q$madrasta$q$, $q$Her stepmother treats her kindly.$q$, $q$A madrasta dela a trata com gentileza.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Widower$q$, $q$viúvo$q$, $q$The widower lives alone in the house.$q$, $q$O viúvo mora sozinho na casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Roommate$q$, $q$colega de quarto$q$, $q$My roommate always cleans the kitchen.$q$, $q$Meu colega de quarto sempre limpa a cozinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Acquaintance$q$, $q$conhecido$q$, $q$He is just an acquaintance from work.$q$, $q$Ele é só um conhecido do trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Routine$q$, $q$rotina$q$, $q$She follows the same routine every day.$q$, $q$Ela segue a mesma rotina todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Custom$q$, $q$costume$q$, $q$This custom comes from an old tradition.$q$, $q$Este costume vem de uma tradição antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Punctual$q$, $q$pontual$q$, $q$He is always punctual for meetings.$q$, $q$Ele é sempre pontual para as reuniões.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Insomnia$q$, $q$insônia$q$, $q$Insomnia keeps her awake all night.$q$, $q$A insônia a mantém acordada a noite toda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Doze$q$, $q$cochilar$q$, $q$He tends to doze off during long lectures.$q$, $q$Ele tende a cochilar durante palestras longas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Procrastinate$q$, $q$procrastinar$q$, $q$I tend to procrastinate before big exams.$q$, $q$Eu tendo a procrastinar antes de provas grandes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Organize$q$, $q$organizar$q$, $q$We organize the files by date.$q$, $q$Nós organizamos os arquivos por data.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Customary$q$, $q$costumeiro$q$, $q$It is customary to bring a gift.$q$, $q$É costumeiro trazer um presente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Discipline$q$, $q$disciplina$q$, $q$Discipline helps him finish his studies.$q$, $q$A disciplina o ajuda a terminar os estudos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Unwind$q$, $q$relaxar$q$, $q$I like to unwind with a book at night.$q$, $q$Eu gosto de relaxar com um livro à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Strive$q$, $q$esforçar-se$q$, $q$She continues to strive for excellence.$q$, $q$Ela continua se esforçando pela excelência.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Persevere$q$, $q$perseverar$q$, $q$He decides to persevere despite the setback.$q$, $q$Ele decide perseverar apesar do contratempo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Overcome$q$, $q$superar$q$, $q$They overcome many obstacles together.$q$, $q$Eles superam muitos obstáculos juntos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Confront$q$, $q$enfrentar$q$, $q$She decides to confront the problem directly.$q$, $q$Ela decide enfrentar o problema diretamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Devote$q$, $q$dedicar-se$q$, $q$I devote my time to volunteer work.$q$, $q$Eu dedico meu tempo a trabalho voluntário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Compete$q$, $q$competir$q$, $q$The two companies compete for the same market.$q$, $q$As duas empresas competem pelo mesmo mercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Practice$q$, $q$treinar$q$, $q$We practice every afternoon.$q$, $q$Nós treinamos toda tarde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Exercise$q$, $q$exercitar-se$q$, $q$We exercise together three times a week.$q$, $q$Nós nos exercitamos juntos três vezes por semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Surrender$q$, $q$render-se$q$, $q$The soldiers refuse to surrender.$q$, $q$Os soldados se recusam a se render.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Triumph$q$, $q$triunfar$q$, $q$Her hard work leads to a final triumph.$q$, $q$O trabalho duro dela leva a um triunfo final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vast$q$, $q$vasto$q$, $q$The desert covers a vast area.$q$, $q$O deserto cobre uma área vasta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gigantic$q$, $q$gigantesco$q$, $q$The company builds a gigantic new factory.$q$, $q$A empresa constrói uma fábrica nova gigantesca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Extreme$q$, $q$extremo$q$, $q$They experience extreme weather this year.$q$, $q$Eles enfrentam um clima extremo este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Slight$q$, $q$ligeiro$q$, $q$There is a slight change in the plan.$q$, $q$Há uma mudança ligeira no plano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Profound$q$, $q$profundo$q$, $q$The book leaves a profound impact on readers.$q$, $q$O livro deixa um impacto profundo nos leitores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Intense$q$, $q$intenso$q$, $q$The heat is intense during the afternoon.$q$, $q$O calor é intenso durante a tarde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Feeble$q$, $q$fraco$q$, $q$His voice sounds feeble after the illness.$q$, $q$A voz dele soa fraca depois da doença.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Powerful$q$, $q$poderoso$q$, $q$The engine produces a powerful sound.$q$, $q$O motor produz um som poderoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Delicate$q$, $q$delicado$q$, $q$This is a delicate situation.$q$, $q$Esta é uma situação delicada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sturdy$q$, $q$robusto$q$, $q$They build a sturdy fence around the yard.$q$, $q$Eles constroem uma cerca robusta ao redor do quintal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
