-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote10.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Forlorn$q$, $q$desamparado$q$, $q$The forlorn dog waits alone outside the empty house.$q$, $q$O cachorro desamparado espera sozinho do lado de fora da casa vazia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hospitable$q$, $q$hospitaleiro$q$, $q$The village is known for being especially hospitable to strangers.$q$, $q$A vila é conhecida por ser especialmente hospitaleira com estranhos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Supportive$q$, $q$solidário$q$, $q$Her family remains supportive throughout the difficult treatment.$q$, $q$A família dela permanece solidária durante todo o tratamento difícil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fraternal$q$, $q$fraterno$q$, $q$The two brothers share a strong fraternal bond.$q$, $q$Os dois irmãos compartilham um forte laço fraterno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Snobbish$q$, $q$esnobe$q$, $q$His snobbish attitude annoys most of his classmates.$q$, $q$A atitude esnobe dele irrita a maioria dos colegas de classe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Aloof$q$, $q$distante e frio$q$, $q$She stays aloof during the entire office party.$q$, $q$Ela fica distante e fria durante a festa inteira do escritório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Needy$q$, $q$carente$q$, $q$The charity focuses on helping needy families in winter.$q$, $q$A instituição de caridade foca em ajudar famílias carentes no inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subordinate$q$, $q$subordinado$q$, $q$His subordinate reports directly to him on this project.$q$, $q$O subordinado dele se reporta diretamente a ele neste projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Autonomous$q$, $q$autônomo$q$, $q$The region becomes fully autonomous after the treaty.$q$, $q$A região se torna totalmente autônoma depois do tratado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sociable$q$, $q$sociável$q$, $q$She is naturally sociable at every gathering.$q$, $q$Ela é naturalmente sociável em todo encontro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Generation$q$, $q$geração$q$, $q$This generation grows up with constant internet access.$q$, $q$Esta geração cresce com acesso constante à internet.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Contemporary$q$, $q$contemporâneo$q$, $q$The museum focuses on contemporary art from Brazil.$q$, $q$O museu foca em arte contemporânea do Brasil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prehistoric$q$, $q$pré-histórico$q$, $q$The cave contains prehistoric paintings on its walls.$q$, $q$A caverna contém pinturas pré-históricas nas paredes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Archaic$q$, $q$arcaico$q$, $q$The law still uses archaic language from centuries ago.$q$, $q$A lei ainda usa uma linguagem arcaica de séculos atrás.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Obsolete$q$, $q$obsoleto$q$, $q$The old software becomes obsolete within a few years.$q$, $q$O software antigo se torna obsoleto em poucos anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Timeless$q$, $q$atemporal$q$, $q$The novel explores timeless questions about love and loss.$q$, $q$O romance explora questões atemporais sobre amor e perda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Antique$q$, $q$antiguidade valiosa$q$, $q$She inherits a beautiful antique from her grandmother.$q$, $q$Ela herda uma antiguidade valiosa e linda da avó dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Primitive$q$, $q$primitivo$q$, $q$The tribe still uses primitive tools for farming.$q$, $q$A tribo ainda usa ferramentas primitivas para a agricultura.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Modernity$q$, $q$modernidade$q$, $q$The city blends tradition with striking modernity.$q$, $q$A cidade combina tradição com uma modernidade marcante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Epoch$q$, $q$época marcante$q$, $q$The invention marks the beginning of a new epoch.$q$, $q$A invenção marca o início de uma nova época marcante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Statute$q$, $q$estatuto$q$, $q$The new statute takes effect at the start of the year.$q$, $q$O novo estatuto entra em vigor no início do ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Constitution$q$, $q$constituição de um país$q$, $q$The country adopts a new constitution after the revolution.$q$, $q$O país adota uma nova constituição depois da revolução.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ordinance$q$, $q$regulamento municipal$q$, $q$The city passes an ordinance banning street vendors downtown.$q$, $q$A cidade aprova um regulamento municipal proibindo vendedores ambulantes no centro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Curfew$q$, $q$toque de recolher$q$, $q$The government imposes a curfew during the crisis.$q$, $q$O governo impõe um toque de recolher durante a crise.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Injunction$q$, $q$ordem judicial de proibição$q$, $q$The judge issues an injunction against the company.$q$, $q$O juiz emite uma ordem judicial de proibição contra a empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Misdemeanor$q$, $q$delito leve$q$, $q$He is charged with a minor misdemeanor for the incident.$q$, $q$Ele é acusado de um delito leve pelo incidente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Felony$q$, $q$crime grave$q$, $q$The court treats the crime as a serious felony.$q$, $q$O tribunal trata o crime como um crime grave sério.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Violation$q$, $q$contravenção$q$, $q$The driver receives a fine for the traffic violation.$q$, $q$O motorista recebe uma multa pela contravenção de trânsito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reprieve$q$, $q$suspensão de pena$q$, $q$The governor grants a last-minute reprieve to the prisoner.$q$, $q$O governador concede uma suspensão de pena de última hora ao prisioneiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Warrant$q$, $q$mandado judicial$q$, $q$Police obtain a warrant before searching the house.$q$, $q$A polícia obtém um mandado judicial antes de revistar a casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Methodology$q$, $q$metodologia$q$, $q$The paper explains the methodology behind the study.$q$, $q$O artigo explica a metodologia por trás do estudo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Criterion$q$, $q$critério de avaliação$q$, $q$Experience becomes the main criterion for the job.$q$, $q$Experiência se torna o principal critério de avaliação para o emprego.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Parameter$q$, $q$parâmetro$q$, $q$Researchers adjust one parameter at a time.$q$, $q$Pesquisadores ajustam um parâmetro de cada vez.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Indicator$q$, $q$indicador de desempenho$q$, $q$Sales growth serves as a key indicator of success.$q$, $q$O crescimento das vendas serve como um indicador chave de sucesso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sample$q$, $q$amostra de pesquisa$q$, $q$The study relies on a small sample of participants.$q$, $q$O estudo depende de uma amostra pequena de participantes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Margin$q$, $q$margem de erro$q$, $q$The survey has a small margin of error.$q$, $q$A pesquisa tem uma pequena margem de erro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Correlation$q$, $q$correlação$q$, $q$The data shows a strong correlation between the two factors.$q$, $q$Os dados mostram uma correlação forte entre os dois fatores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bias$q$, $q$viés$q$, $q$The report tries to avoid any bias in its conclusions.$q$, $q$O relatório tenta evitar qualquer viés nas conclusões.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Variance$q$, $q$variância$q$, $q$The results show a wide variance across groups.$q$, $q$Os resultados mostram uma variância grande entre os grupos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Benchmark$q$, $q$padrão de referência$q$, $q$The company sets a new benchmark for customer service.$q$, $q$A empresa estabelece um novo padrão de referência para o atendimento ao cliente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Extrapolate$q$, $q$extrapolar$q$, $q$I extrapolate future sales from last year's data.$q$, $q$Eu extrapolo as vendas futuras a partir dos dados do ano passado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Interpolate$q$, $q$interpolar$q$, $q$I interpolate the missing values in the graph.$q$, $q$Eu interpolo os valores ausentes no gráfico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Quantify$q$, $q$quantificar$q$, $q$I quantify the results before presenting them.$q$, $q$Eu quantifico os resultados antes de apresentá-los.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Estimate$q$, $q$estimar$q$, $q$I estimate the total cost of the renovation.$q$, $q$Eu estimo o custo total da reforma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Verify$q$, $q$verificar$q$, $q$I verify the data before publishing the report.$q$, $q$Eu verifico os dados antes de publicar o relatório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Validate$q$, $q$validar$q$, $q$I validate the results with a second test.$q$, $q$Eu valido os resultados com um segundo teste.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Calculate$q$, $q$calcular$q$, $q$I calculate the average score for the class.$q$, $q$Eu calculo a nota média da turma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Measure$q$, $q$medir$q$, $q$I measure the room before buying the furniture.$q$, $q$Eu meço o quarto antes de comprar os móveis.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Substantiate$q$, $q$comprovar com fatos$q$, $q$I substantiate my claim with solid evidence.$q$, $q$Eu comprovo minha alegação com provas sólidas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hypothesize$q$, $q$formular hipótese$q$, $q$I hypothesize that the change will improve results.$q$, $q$Eu formulo a hipótese de que a mudança vai melhorar os resultados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Flawless$q$, $q$impecável$q$, $q$Her performance on stage is absolutely flawless.$q$, $q$A apresentação dela no palco é absolutamente impecável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Faulty$q$, $q$defeituoso$q$, $q$The store replaces the faulty appliance for free.$q$, $q$A loja substitui o eletrodoméstico defeituoso de graça.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rustic$q$, $q$rústico$q$, $q$The cabin has a simple, rustic charm.$q$, $q$A cabana tem um charme simples e rústico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Refined$q$, $q$refinado$q$, $q$His refined taste is obvious in every detail of the house.$q$, $q$O gosto refinado dele é óbvio em cada detalhe da casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Crude$q$, $q$tosco$q$, $q$The early prototype looks crude compared to the final version.$q$, $q$O protótipo inicial parece tosco comparado à versão final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Durable$q$, $q$durável$q$, $q$The backpack is light but extremely durable.$q$, $q$A mochila é leve, mas extremamente durável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fragile$q$, $q$frágil$q$, $q$Handle the package carefully; it contains fragile items.$q$, $q$Manuseie o pacote com cuidado; ele contém itens frágeis.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Notorious$q$, $q$notório$q$, $q$The city is notorious for its heavy traffic.$q$, $q$A cidade é notória pelo trânsito pesado dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Renowned$q$, $q$célebre$q$, $q$She becomes a renowned scientist in her field.$q$, $q$Ela se torna uma cientista célebre na área dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Anonymous$q$, $q$anônimo$q$, $q$The donor chooses to remain anonymous.$q$, $q$O doador decide permanecer anônimo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Birth$q$, $q$nascimento$q$, $q$They celebrate the birth of their first child.$q$, $q$Eles celebram o nascimento do primeiro filho deles.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cradle$q$, $q$berço$q$, $q$The baby sleeps peacefully in the wooden cradle.$q$, $q$O bebê dorme tranquilamente no berço de madeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Childhood$q$, $q$infância$q$, $q$She spends her childhood in a small coastal town.$q$, $q$Ela passa a infância numa cidade litorânea pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Youth$q$, $q$juventude$q$, $q$He spends his youth traveling across South America.$q$, $q$Ele passa a juventude dele viajando pela América do Sul.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Longevity$q$, $q$longevidade$q$, $q$A healthy diet contributes to human longevity.$q$, $q$Uma dieta saudável contribui para a longevidade humana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mortality$q$, $q$mortalidade$q$, $q$The study examines mortality rates in rural areas.$q$, $q$O estudo examina as taxas de mortalidade em áreas rurais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lineage$q$, $q$linhagem$q$, $q$She traces her family's lineage back three centuries.$q$, $q$Ela rastreia a linhagem da família dela três séculos atrás.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Epitaph$q$, $q$epitáfio$q$, $q$The epitaph on the stone contains a short, kind message.$q$, $q$O epitáfio na pedra traz uma mensagem curta e gentil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Grave$q$, $q$sepultura$q$, $q$They visit his grave every year on his birthday.$q$, $q$Eles visitam a sepultura dele todo ano no aniversário dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Adulthood$q$, $q$vida adulta$q$, $q$She reflects on the responsibilities of adulthood.$q$, $q$Ela reflete sobre as responsabilidades da vida adulta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Compose$q$, $q$compor música$q$, $q$I compose a new song for the film.$q$, $q$Eu componho uma canção nova para o filme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rehearse$q$, $q$ensaiar peça$q$, $q$I rehearse the final scene twice before the show.$q$, $q$Eu ensaio a cena final duas vezes antes do show.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Improvise$q$, $q$improvisar$q$, $q$The actor has to improvise when he forgets his line.$q$, $q$O ator tem que improvisar quando esquece a fala dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chisel$q$, $q$cinzelar$q$, $q$I chisel the marble with great care.$q$, $q$Eu cinzelo o mármore com muito cuidado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sketch$q$, $q$esboçar$q$, $q$I sketch the building before painting it.$q$, $q$Eu esboço o prédio antes de pintá-lo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Portray$q$, $q$retratar$q$, $q$I portray the artist's difficult early years in my film.$q$, $q$Eu retrato os primeiros anos difíceis do artista no meu filme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Direct$q$, $q$dirigir filme$q$, $q$He decides to direct his first feature film this year.$q$, $q$Ele decide dirigir o primeiro longa-metragem dele este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Perform$q$, $q$atuar em cena$q$, $q$I perform the same role for the tenth time.$q$, $q$Eu atuo no mesmo papel pela décima vez.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Applaud$q$, $q$aplaudir$q$, $q$I applaud for several minutes after the show.$q$, $q$Eu aplaudo por vários minutos depois do show.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Boo$q$, $q$vaiar$q$, $q$Some fans boo when the referee makes the call.$q$, $q$Alguns torcedores vaiam quando o árbitro toma a decisão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Beaker$q$, $q$béquer$q$, $q$She pours the liquid carefully into the beaker.$q$, $q$Ela despeja o líquido com cuidado no béquer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Microscope$q$, $q$microscópio$q$, $q$Students examine the sample under a microscope.$q$, $q$Os alunos examinam a amostra num microscópio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pipette$q$, $q$pipeta$q$, $q$The technician uses a pipette to measure the solution.$q$, $q$O técnico usa uma pipeta para medir a solução.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Centrifuge$q$, $q$centrífuga$q$, $q$The lab spins the sample in a centrifuge.$q$, $q$O laboratório gira a amostra numa centrífuga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Substrate$q$, $q$substrato$q$, $q$The enzyme reacts quickly with the substrate.$q$, $q$A enzima reage rapidamente com o substrato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thermometer$q$, $q$termômetro$q$, $q$She checks the child's temperature with a thermometer.$q$, $q$Ela confere a temperatura da criança com um termômetro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Barometer$q$, $q$barômetro$q$, $q$The barometer predicts a sudden drop in pressure.$q$, $q$O barômetro prevê uma queda repentina na pressão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stopwatch$q$, $q$cronômetro$q$, $q$The coach uses a stopwatch to time each lap.$q$, $q$O treinador usa um cronômetro para marcar cada volta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Burner$q$, $q$bico de laboratório$q$, $q$The chemist adjusts the flame on the burner.$q$, $q$O químico ajusta a chama no bico de laboratório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Specimen$q$, $q$espécime$q$, $q$The biologist collects a specimen from the riverbank.$q$, $q$O biólogo coleta um espécime na margem do rio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Zenith$q$, $q$ponto mais alto$q$, $q$The sun reaches its zenith at noon.$q$, $q$O sol atinge o ponto mais alto ao meio-dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pinnacle$q$, $q$ápice$q$, $q$Winning the award marks the pinnacle of her career.$q$, $q$Ganhar o prêmio marca o ápice da carreira dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Summit$q$, $q$cume$q$, $q$They finally reach the summit after six hours of climbing.$q$, $q$Eles finalmente alcançam o cume depois de seis horas de escalada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Peak$q$, $q$pico$q$, $q$The mountain's peak stays covered in snow all year.$q$, $q$O pico da montanha permanece coberto de neve o ano todo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Slope$q$, $q$ladeira$q$, $q$Skiers race down the steep slope.$q$, $q$Esquiadores descem a ladeira íngreme correndo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Legitimate$q$, $q$legítimo$q$, $q$The company presents legitimate documents for the deal.$q$, $q$A empresa apresenta documentos legítimos para o acordo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Authentic$q$, $q$autêntico$q$, $q$This painting is confirmed to be authentic.$q$, $q$Esta pintura é confirmada como autêntica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pivot$q$, $q$ponto de virada$q$, $q$The interview becomes a pivot point in her career.$q$, $q$A entrevista se torna um ponto de virada na carreira dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Origin$q$, $q$origem$q$, $q$Scientists still debate the origin of the universe.$q$, $q$Cientistas ainda debatem a origem do universo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Magnificence$q$, $q$magnificência$q$, $q$Visitors marvel at the magnificence of the old palace.$q$, $q$Visitantes se maravilham com a magnificência do palácio antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
