-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote9.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Kilometer$q$, $q$quilômetro$q$, $q$The store is one kilometer from here.$q$, $q$A loja fica a um quilômetro daqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mile$q$, $q$milha$q$, $q$The airport is one mile away.$q$, $q$O aeroporto fica a uma milha de distância.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Inch$q$, $q$polegada$q$, $q$The new screen is one inch bigger.$q$, $q$A tela nova é uma polegada maior.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Liter$q$, $q$litro$q$, $q$I buy a liter of milk every day.$q$, $q$Eu compro um litro de leite todo dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gallon$q$, $q$galão$q$, $q$The tank holds one gallon of fuel.$q$, $q$O tanque comporta um galão de combustível.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pound$q$, $q$libra$q$, $q$This bag weighs about one pound.$q$, $q$Esta sacola pesa cerca de uma libra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ounce$q$, $q$onça de peso$q$, $q$Add one ounce of chocolate to the recipe.$q$, $q$Adicione uma onça de chocolate à receita.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dozen$q$, $q$dúzia$q$, $q$I buy a dozen eggs at the market.$q$, $q$Eu compro uma dúzia de ovos no mercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Centimeter$q$, $q$centímetro$q$, $q$Cut the ribbon down by one centimeter.$q$, $q$Corte a fita reduzindo um centímetro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Billion$q$, $q$bilhão$q$, $q$The company earns over a billion dollars.$q$, $q$A empresa ganha mais de um bilhão de dólares.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Triangle$q$, $q$triângulo$q$, $q$She draws a triangle on the paper.$q$, $q$Ela desenha um triângulo no papel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rectangle$q$, $q$retângulo$q$, $q$The garden has the shape of a rectangle.$q$, $q$O jardim tem a forma de um retângulo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cylinder$q$, $q$cilindro$q$, $q$The can has the shape of a cylinder.$q$, $q$A lata tem a forma de um cilindro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sphere$q$, $q$esfera$q$, $q$The ball is a perfect sphere.$q$, $q$A bola é uma esfera perfeita.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cube$q$, $q$cubo$q$, $q$He builds a tower using a cube.$q$, $q$Ele constrói uma torre usando um cubo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Curve$q$, $q$curva$q$, $q$The road has a sharp curve ahead.$q$, $q$A estrada tem uma curva fechada à frente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Beige$q$, $q$bege$q$, $q$She paints the wall a soft beige.$q$, $q$Ela pinta a parede de um bege suave.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Maroon$q$, $q$cor de vinho$q$, $q$He wears a maroon jacket to the party.$q$, $q$Ele usa uma jaqueta cor de vinho para a festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lilac$q$, $q$lilás$q$, $q$The dress comes in a light lilac color.$q$, $q$O vestido vem numa cor lilás clara.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Turquoise$q$, $q$turquesa$q$, $q$The water looks turquoise near the reef.$q$, $q$A água parece turquesa perto do recife.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cockroach$q$, $q$barata$q$, $q$A cockroach runs across the kitchen floor.$q$, $q$Uma barata corre pelo chão da cozinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Flea$q$, $q$pulga$q$, $q$The dog scratches because of a flea.$q$, $q$O cachorro se coça por causa de uma pulga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tick$q$, $q$carrapato$q$, $q$She finds a tick on the dog's fur.$q$, $q$Ela encontra um carrapato no pelo do cachorro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wasp$q$, $q$vespa$q$, $q$A wasp flies near the window.$q$, $q$Uma vespa voa perto da janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ladybug$q$, $q$joaninha$q$, $q$A ladybug lands on the leaf.$q$, $q$Uma joaninha pousa na folha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cricket$q$, $q$grilo$q$, $q$I hear a cricket outside my window.$q$, $q$Eu ouço um grilo do lado de fora da janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bat$q$, $q$morcego$q$, $q$A bat flies out of the old barn.$q$, $q$Um morcego voa para fora do celeiro velho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Slug$q$, $q$lesma$q$, $q$A slug moves slowly across the path.$q$, $q$Uma lesma se move devagar pela trilha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Snail$q$, $q$caracol$q$, $q$A snail leaves a trail on the leaf.$q$, $q$Um caracol deixa um rastro na folha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lizard$q$, $q$lagarto$q$, $q$A lizard runs up the garden wall.$q$, $q$Um lagarto corre pela parede do jardim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Eagle$q$, $q$águia$q$, $q$An eagle flies high above the mountains.$q$, $q$Uma águia voa alto acima das montanhas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hawk$q$, $q$falcão$q$, $q$A hawk circles above the field.$q$, $q$Um falcão sobrevoa em círculos o campo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Seagull$q$, $q$gaivota$q$, $q$A seagull follows the fishing boat.$q$, $q$Uma gaivota segue o barco de pesca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Swan$q$, $q$cisne$q$, $q$A swan glides across the lake.$q$, $q$Um cisne desliza pelo lago.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Peacock$q$, $q$pavão$q$, $q$The peacock opens its colorful tail.$q$, $q$O pavão abre a cauda colorida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Woodpecker$q$, $q$pica-pau$q$, $q$A woodpecker taps on the old tree.$q$, $q$Um pica-pau bica a árvore velha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hummingbird$q$, $q$beija-flor$q$, $q$A hummingbird visits the flower every day.$q$, $q$Um beija-flor visita a flor todo dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Crow$q$, $q$corvo$q$, $q$A crow lands on the fence.$q$, $q$Um corvo pousa na cerca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vulture$q$, $q$urubu$q$, $q$A vulture circles above the field.$q$, $q$Um urubu sobrevoa em círculos o campo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ostrich$q$, $q$avestruz$q$, $q$An ostrich runs faster than a horse.$q$, $q$Um avestruz corre mais rápido que um cavalo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Flute$q$, $q$flauta$q$, $q$She plays the flute in the school band.$q$, $q$Ela toca flauta na banda da escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Trumpet$q$, $q$trompete$q$, $q$He learns to play the trumpet this year.$q$, $q$Ele aprende a tocar trompete este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Saxophone$q$, $q$saxofone$q$, $q$The musician plays a smooth saxophone solo.$q$, $q$O músico toca um solo suave de saxofone.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Harp$q$, $q$harpa$q$, $q$She practices the harp every evening.$q$, $q$Ela pratica harpa toda noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Accordion$q$, $q$acordeão$q$, $q$He plays the accordion at family parties.$q$, $q$Ele toca acordeão nas festas de família.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Harmonica$q$, $q$gaita de boca$q$, $q$The old man plays a harmonica on the porch.$q$, $q$O senhor idoso toca gaita de boca na varanda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cymbals$q$, $q$pratos de bateria$q$, $q$The drummer crashes the cymbals at the end.$q$, $q$O baterista bate os pratos de bateria no final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tambourine$q$, $q$pandeiro$q$, $q$She shakes the tambourine during the song.$q$, $q$Ela sacode o pandeiro durante a música.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Organ$q$, $q$órgão$q$, $q$He plays the organ at the church.$q$, $q$Ele toca órgão na igreja.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cello$q$, $q$violoncelo$q$, $q$She practices the cello for the concert.$q$, $q$Ela pratica violoncelo para o show.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Veterinarian$q$, $q$veterinário$q$, $q$The veterinarian examines the sick dog.$q$, $q$O veterinário examina o cachorro doente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Architect$q$, $q$arquiteto$q$, $q$The architect designs the new library.$q$, $q$O arquiteto projeta a nova biblioteca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Journalist$q$, $q$jornalista$q$, $q$The journalist interviews the mayor.$q$, $q$O jornalista entrevista o prefeito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Carpenter$q$, $q$carpinteiro$q$, $q$The carpenter builds a wooden table.$q$, $q$O carpinteiro constrói uma mesa de madeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Electrician$q$, $q$eletricista$q$, $q$The electrician fixes the broken light.$q$, $q$O eletricista conserta a luz quebrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Librarian$q$, $q$bibliotecário$q$, $q$The librarian helps me find the book.$q$, $q$O bibliotecário me ajuda a encontrar o livro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Scientist$q$, $q$cientista$q$, $q$The scientist studies the effects of the vaccine.$q$, $q$O cientista estuda os efeitos da vacina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dancer$q$, $q$dançarino$q$, $q$She trains to become a professional dancer.$q$, $q$Ela treina para se tornar uma dançarina profissional.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Photographer$q$, $q$fotógrafo$q$, $q$The photographer captures the perfect sunset.$q$, $q$O fotógrafo captura o pôr do sol perfeito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fisherman$q$, $q$pescador$q$, $q$The fisherman returns early in the morning.$q$, $q$O pescador retorna cedo de manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Padlock$q$, $q$cadeado$q$, $q$He locks the gate with a padlock.$q$, $q$Ele tranca o portão com um cadeado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Chain$q$, $q$corrente de metal$q$, $q$A chain keeps the gate closed.$q$, $q$Uma corrente mantém o portão fechado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Compass$q$, $q$bússola$q$, $q$We use a compass to find north.$q$, $q$Nós usamos uma bússola para achar o norte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Magnifier$q$, $q$lupa$q$, $q$She reads the small print with a magnifier.$q$, $q$Ela lê a letra pequena com uma lupa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Binoculars$q$, $q$binóculo$q$, $q$He watches the birds with binoculars.$q$, $q$Ele observa os pássaros com um binóculo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Match$q$, $q$fósforo$q$, $q$I light the candle with a match.$q$, $q$Eu acendo a vela com um fósforo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lighter$q$, $q$isqueiro$q$, $q$He carries a lighter for the campfire.$q$, $q$Ele carrega um isqueiro para a fogueira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spring$q$, $q$mola$q$, $q$A broken spring makes the chair squeak.$q$, $q$Uma mola quebrada faz a cadeira ranger.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cog$q$, $q$engrenagem$q$, $q$A small cog turns inside the clock.$q$, $q$Uma engrenagem pequena gira dentro do relógio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hinge$q$, $q$dobradiça$q$, $q$The hinge on the door needs oil.$q$, $q$A dobradiça da porta precisa de óleo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Certificate$q$, $q$certidão$q$, $q$She receives a certificate after the course.$q$, $q$Ela recebe um certificado depois do curso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Form$q$, $q$formulário$q$, $q$I fill out the form at the office.$q$, $q$Eu preencho o formulário no escritório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Registration$q$, $q$cadastro$q$, $q$Registration for the event ends on Friday.$q$, $q$O cadastro para o evento termina na sexta-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Voucher$q$, $q$comprovante$q$, $q$I use a voucher to get a discount.$q$, $q$Eu uso um comprovante para ter um desconto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Warranty$q$, $q$garantia do produto$q$, $q$The laptop comes with a two-year warranty.$q$, $q$O laptop vem com garantia de dois anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tag$q$, $q$etiqueta de preço$q$, $q$Check the tag before buying the shirt.$q$, $q$Confira a etiqueta antes de comprar a camisa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Permit$q$, $q$alvará$q$, $q$You need a permit to build here.$q$, $q$Você precisa de um alvará para construir aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Visa$q$, $q$visto de viagem$q$, $q$I apply for a visa before the trip.$q$, $q$Eu solicito um visto antes da viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fee$q$, $q$taxa$q$, $q$The school charges a small fee for the trip.$q$, $q$A escola cobra uma pequena taxa pela viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Identity$q$, $q$carteira de identidade$q$, $q$Please show proof of your identity at the door.$q$, $q$Por favor, mostre um comprovante da sua identidade na porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Peel$q$, $q$descascar$q$, $q$I peel the potatoes for dinner.$q$, $q$Eu descasco as batatas para o jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Slice$q$, $q$fatiar$q$, $q$I slice the bread for breakfast.$q$, $q$Eu fatio o pão para o café da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Chop$q$, $q$picar$q$, $q$I chop the onion before cooking.$q$, $q$Eu pico a cebola antes de cozinhar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mash$q$, $q$amassar$q$, $q$I mash the potatoes with butter.$q$, $q$Eu amasso as batatas com manteiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Simmer$q$, $q$ferver em fogo baixo$q$, $q$I let the sauce simmer for ten minutes.$q$, $q$Eu deixo o molho ferver em fogo baixo por dez minutos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fry$q$, $q$fritar$q$, $q$I fry the eggs in a small pan.$q$, $q$Eu frito os ovos numa frigideira pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stir$q$, $q$mexer$q$, $q$I stir the soup so it doesn't stick.$q$, $q$Eu mexo a sopa para não grudar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Serve$q$, $q$servir$q$, $q$I serve dinner at seven o'clock.$q$, $q$Eu sirvo o jantar às sete horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Devour$q$, $q$devorar$q$, $q$I devour the pizza after the long game.$q$, $q$Eu devoro a pizza depois do jogo longo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sip$q$, $q$beber aos poucos$q$, $q$I sip my tea slowly by the window.$q$, $q$Eu bebo meu chá aos poucos perto da janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Marry$q$, $q$casar-se$q$, $q$They marry after five years together.$q$, $q$Eles se casam depois de cinco anos juntos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reside$q$, $q$residir$q$, $q$I reside in the north of the city.$q$, $q$Eu resido no norte da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Relocate$q$, $q$mudar de cidade$q$, $q$We relocate to a new city for work.$q$, $q$Nós nos mudamos para uma nova cidade por trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Migrate$q$, $q$migrar$q$, $q$Birds migrate south before winter.$q$, $q$Os pássaros migram para o sul antes do inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Inherit$q$, $q$herdar$q$, $q$I inherit the house from my grandmother.$q$, $q$Eu herdo a casa da minha avó.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Survive$q$, $q$sobreviver$q$, $q$Few plants survive the harsh winter.$q$, $q$Poucas plantas sobrevivem ao inverno rigoroso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gain$q$, $q$ganhar peso$q$, $q$I gain weight during the holidays.$q$, $q$Eu ganho peso durante as festas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Care$q$, $q$cuidar de alguém$q$, $q$I care for my elderly grandfather.$q$, $q$Eu cuido do meu avô idoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Raise$q$, $q$criar filhos$q$, $q$They raise three children in this house.$q$, $q$Eles criam três filhos nesta casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Engage$q$, $q$ficar noivo$q$, $q$They engage to marry after two years of dating.$q$, $q$Eles ficam noivos depois de dois anos de namoro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
