-- Frases-exemplo do Mental Lingo: lingo_exemplos_basico_lote5.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sandwich$q$, $q$sanduíche$q$, $q$I eat a sandwich for lunch.$q$, $q$Eu como um sanduíche no almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pan$q$, $q$frigideira$q$, $q$She cooks the eggs in a pan.$q$, $q$Ela cozinha os ovos numa frigideira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cream$q$, $q$creme$q$, $q$I put cream in my coffee.$q$, $q$Eu ponho creme no meu café.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Flour$q$, $q$farinha$q$, $q$She uses flour to make bread.$q$, $q$Ela usa farinha para fazer pão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Oil$q$, $q$óleo$q$, $q$I cook with olive oil.$q$, $q$Eu cozinho com óleo de oliva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pepper$q$, $q$pimenta$q$, $q$Add salt and pepper to the soup.$q$, $q$Adicione sal e pimenta na sopa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nut$q$, $q$noz$q$, $q$He eats a nut every morning.$q$, $q$Ele come uma noz toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Beer$q$, $q$cerveja$q$, $q$My father drinks a beer.$q$, $q$Meu pai bebe uma cerveja.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wine$q$, $q$vinho$q$, $q$They drink wine at dinner.$q$, $q$Eles bebem vinho no jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Meal$q$, $q$refeição$q$, $q$This is a healthy meal.$q$, $q$Esta é uma refeição saudável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Breakfast$q$, $q$café da manhã$q$, $q$I eat breakfast at seven.$q$, $q$Eu tomo café da manhã às sete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lunch$q$, $q$almoço$q$, $q$We have lunch at noon.$q$, $q$Nós almoçamos ao meio-dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Dinner$q$, $q$jantar$q$, $q$Dinner is ready.$q$, $q$O jantar está pronto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Snack$q$, $q$lanche$q$, $q$I have a snack after school.$q$, $q$Eu como um lanche depois da escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Menu$q$, $q$cardápio$q$, $q$Can I see the menu, please?$q$, $q$Posso ver o cardápio, por favor?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Oven$q$, $q$forno$q$, $q$The cake is in the oven.$q$, $q$O bolo está no forno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pot$q$, $q$panela$q$, $q$She cooks rice in a pot.$q$, $q$Ela cozinha arroz numa panela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bowl$q$, $q$tigela$q$, $q$I eat cereal from a bowl.$q$, $q$Eu como cereal numa tigela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Napkin$q$, $q$guardanapo$q$, $q$Please pass me a napkin.$q$, $q$Por favor, me passe um guardanapo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tray$q$, $q$bandeja$q$, $q$She carries the food on a tray.$q$, $q$Ela carrega a comida numa bandeja.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lesson$q$, $q$lição$q$, $q$Today's lesson is about animals.$q$, $q$A lição de hoje é sobre animais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Homework$q$, $q$dever de casa$q$, $q$I do my homework after school.$q$, $q$Eu faço meu dever de casa depois da escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Question$q$, $q$pergunta$q$, $q$The teacher asks a question.$q$, $q$O professor faz uma pergunta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Grade$q$, $q$nota$q$, $q$She got a good grade on the test.$q$, $q$Ela tirou uma boa nota na prova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Desk$q$, $q$carteira escolar$q$, $q$The book is on my desk.$q$, $q$O livro está na minha carteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Board$q$, $q$quadro$q$, $q$The teacher writes on the board.$q$, $q$O professor escreve no quadro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Dictionary$q$, $q$dicionário$q$, $q$I look up the word in a dictionary.$q$, $q$Eu procuro a palavra num dicionário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Notebook$q$, $q$caderno$q$, $q$I write in my notebook.$q$, $q$Eu escrevo no meu caderno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ruler$q$, $q$régua$q$, $q$Use a ruler to draw the line.$q$, $q$Use uma régua para desenhar a linha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Eraser$q$, $q$borracha$q$, $q$Can I borrow your eraser?$q$, $q$Posso pegar sua borracha emprestada?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Job$q$, $q$emprego$q$, $q$She has a good job.$q$, $q$Ela tem um bom emprego.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Salary$q$, $q$salário$q$, $q$His salary is not very high.$q$, $q$O salário dele não é muito alto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Buyer$q$, $q$comprador$q$, $q$The buyer likes the house.$q$, $q$O comprador gosta da casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Company$q$, $q$empresa$q$, $q$He works for a big company.$q$, $q$Ele trabalha para uma empresa grande.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Factory$q$, $q$fábrica$q$, $q$My uncle works at a factory.$q$, $q$Meu tio trabalha numa fábrica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Worker$q$, $q$trabalhador$q$, $q$The worker fixes the machine.$q$, $q$O trabalhador conserta a máquina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Farmer$q$, $q$agricultor$q$, $q$The farmer grows corn.$q$, $q$O agricultor planta milho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lawyer$q$, $q$advogado$q$, $q$She wants to be a lawyer.$q$, $q$Ela quer ser advogada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Waiter$q$, $q$garçom$q$, $q$The waiter brings the food.$q$, $q$O garçom traz a comida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Singer$q$, $q$cantor$q$, $q$My sister is a great singer.$q$, $q$Minha irmã é uma ótima cantora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Face$q$, $q$rosto$q$, $q$She has a beautiful face.$q$, $q$Ela tem um rosto bonito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lip$q$, $q$lábio$q$, $q$He has a cut on his lip.$q$, $q$Ele tem um corte no lábio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Chest$q$, $q$peito$q$, $q$The dog rests its head on his chest.$q$, $q$O cachorro descansa a cabeça no peito dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thumb$q$, $q$polegar$q$, $q$He hurt his thumb.$q$, $q$Ele machucou o polegar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Elbow$q$, $q$cotovelo$q$, $q$She has a scar on her elbow.$q$, $q$Ela tem uma cicatriz no cotovelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nail$q$, $q$unha$q$, $q$She paints her nail red.$q$, $q$Ela pinta a unha de vermelho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bone$q$, $q$osso$q$, $q$The dog buries a bone.$q$, $q$O cachorro enterra um osso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Blood$q$, $q$sangue$q$, $q$Blood is red.$q$, $q$Sangue é vermelho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Brain$q$, $q$cérebro$q$, $q$The brain controls the body.$q$, $q$O cérebro controla o corpo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tear$q$, $q$lágrima$q$, $q$A tear falls from her eye.$q$, $q$Uma lágrima cai do olho dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Jacket$q$, $q$jaqueta$q$, $q$He wears a jacket in winter.$q$, $q$Ele usa uma jaqueta no inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Scarf$q$, $q$cachecol$q$, $q$She wears a red scarf.$q$, $q$Ela usa um cachecol vermelho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Glove$q$, $q$luva$q$, $q$He wears a glove on his hand.$q$, $q$Ele usa uma luva na mão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Belt$q$, $q$cinto$q$, $q$He wears a black belt.$q$, $q$Ele usa um cinto preto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Boot$q$, $q$bota$q$, $q$She wears a boot in the rain.$q$, $q$Ela usa uma bota na chuva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pocket$q$, $q$bolso$q$, $q$I put my keys in my pocket.$q$, $q$Eu ponho minhas chaves no bolso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Button$q$, $q$botão de roupa$q$, $q$The button on my shirt is loose.$q$, $q$O botão da minha camisa está solto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ring$q$, $q$anel$q$, $q$She wears a gold ring.$q$, $q$Ela usa um anel de ouro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pajamas$q$, $q$pijama$q$, $q$I wear pajamas at night.$q$, $q$Eu uso pijama à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Necklace$q$, $q$colar$q$, $q$She wears a silver necklace.$q$, $q$Ela usa um colar de prata.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Roof$q$, $q$telhado$q$, $q$The roof is red.$q$, $q$O telhado é vermelho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bedroom$q$, $q$quarto$q$, $q$My bedroom is small.$q$, $q$Meu quarto é pequeno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Yard$q$, $q$quintal$q$, $q$The children play in the yard.$q$, $q$As crianças brincam no quintal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fence$q$, $q$cerca$q$, $q$The dog jumps over the fence.$q$, $q$O cachorro pula a cerca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Doorbell$q$, $q$campainha$q$, $q$Someone rings the doorbell.$q$, $q$Alguém toca a campainha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Drawer$q$, $q$gaveta$q$, $q$I keep my socks in the drawer.$q$, $q$Eu guardo minhas meias na gaveta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shelf$q$, $q$prateleira$q$, $q$The books are on the shelf.$q$, $q$Os livros estão na prateleira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Blanket$q$, $q$cobertor$q$, $q$I sleep with a warm blanket.$q$, $q$Eu durmo com um cobertor quente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Curtain$q$, $q$cortina$q$, $q$She opens the curtain in the morning.$q$, $q$Ela abre a cortina de manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Basement$q$, $q$porão$q$, $q$We keep old boxes in the basement.$q$, $q$Nós guardamos caixas velhas no porão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Truck$q$, $q$caminhão$q$, $q$The truck carries fruit.$q$, $q$O caminhão carrega frutas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Motorcycle$q$, $q$moto$q$, $q$He rides a motorcycle to work.$q$, $q$Ele vai de moto para o trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ship$q$, $q$navio$q$, $q$The ship crosses the ocean.$q$, $q$O navio atravessa o oceano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wheel$q$, $q$roda$q$, $q$The car has a flat wheel.$q$, $q$O carro está com uma roda furada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Engine$q$, $q$motor$q$, $q$The engine makes a strange noise.$q$, $q$O motor faz um barulho estranho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Traffic$q$, $q$trânsito$q$, $q$There is a lot of traffic today.$q$, $q$Há muito trânsito hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Passenger$q$, $q$passageiro$q$, $q$The passenger sits near the window.$q$, $q$O passageiro senta perto da janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Highway$q$, $q$rodovia$q$, $q$We drive on the highway.$q$, $q$Nós dirigimos na rodovia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Subway$q$, $q$metrô$q$, $q$I take the subway to school.$q$, $q$Eu pego o metrô para a escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Helmet$q$, $q$capacete$q$, $q$She wears a helmet on her bike.$q$, $q$Ela usa capacete na bicicleta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Grass$q$, $q$grama$q$, $q$The grass is green.$q$, $q$A grama é verde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Leaf$q$, $q$folha de árvore$q$, $q$A leaf falls from the tree.$q$, $q$Uma folha cai da árvore.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Rock$q$, $q$pedra$q$, $q$The children climb the rock.$q$, $q$As crianças escalam a pedra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sand$q$, $q$areia$q$, $q$The children play in the sand.$q$, $q$As crianças brincam na areia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lake$q$, $q$lago$q$, $q$We swim in the lake.$q$, $q$Nós nadamos no lago.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hill$q$, $q$colina$q$, $q$The house is on top of a hill.$q$, $q$A casa fica no topo de uma colina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Field$q$, $q$campo aberto$q$, $q$The cows are in the field.$q$, $q$As vacas estão no campo aberto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wave$q$, $q$onda$q$, $q$The wave is very big.$q$, $q$A onda é muito grande.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Rainbow$q$, $q$arco-íris$q$, $q$We see a rainbow after the rain.$q$, $q$Nós vemos um arco-íris depois da chuva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Smoke$q$, $q$fumaça$q$, $q$Smoke comes from the fire.$q$, $q$Fumaça sai do fogo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Donkey$q$, $q$burro$q$, $q$The donkey carries the bags.$q$, $q$O burro carrega as bolsas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Chick$q$, $q$pintinho$q$, $q$The chick follows the hen.$q$, $q$O pintinho segue a galinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Kid$q$, $q$cabrito$q$, $q$The goat has a small kid.$q$, $q$A cabra tem um cabrito pequeno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Turkey$q$, $q$peru$q$, $q$We eat turkey at the party.$q$, $q$Nós comemos peru na festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pigeon$q$, $q$pombo$q$, $q$A pigeon sits on the roof.$q$, $q$Um pombo pousa no telhado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Puppy$q$, $q$cachorrinho$q$, $q$The puppy plays with the ball.$q$, $q$O cachorrinho brinca com a bola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Kitten$q$, $q$gatinho$q$, $q$The kitten sleeps all day.$q$, $q$O gatinho dorme o dia todo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lamb$q$, $q$cordeiro$q$, $q$The lamb follows its mother.$q$, $q$O cordeiro segue a mãe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bull$q$, $q$touro$q$, $q$The bull is very strong.$q$, $q$O touro é muito forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Goose$q$, $q$ganso$q$, $q$The goose swims in the lake.$q$, $q$O ganso nada no lago.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
