-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote10.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Eyelash$q$, $q$cílio$q$, $q$A small piece of dust gets in her eyelash.$q$, $q$Um pedacinho de poeira entra no cílio dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Eyelid$q$, $q$pálpebra$q$, $q$His eyelid twitches when he is tired.$q$, $q$A pálpebra dele treme quando ele está cansado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Moustache$q$, $q$bigode$q$, $q$My uncle grows a moustache every winter.$q$, $q$Meu tio deixa crescer um bigode todo inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Beard$q$, $q$barba$q$, $q$He decides to grow a beard this year.$q$, $q$Ele decide deixar crescer a barba este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Freckle$q$, $q$sarda$q$, $q$She has a freckle on her cheek.$q$, $q$Ela tem uma sarda na bochecha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wrinkle$q$, $q$ruga$q$, $q$A wrinkle forms near her eyes when she smiles.$q$, $q$Uma ruga se forma perto dos olhos dela quando ela sorri.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Scar$q$, $q$cicatriz$q$, $q$He has a small scar on his arm.$q$, $q$Ele tem uma cicatriz pequena no braço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dimple$q$, $q$covinha$q$, $q$She has a dimple when she smiles.$q$, $q$Ela tem uma covinha quando sorri.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Palm$q$, $q$palma da mão$q$, $q$She holds the coin in her palm.$q$, $q$Ela segura a moeda na palma da mão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fist$q$, $q$punho fechado$q$, $q$He makes a fist to show his anger.$q$, $q$Ele fecha o punho para mostrar raiva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Toddler$q$, $q$criança pequena$q$, $q$The toddler takes his first steps today.$q$, $q$A criança pequena dá os primeiros passos hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Crew$q$, $q$tripulação$q$, $q$The crew prepares the ship for the trip.$q$, $q$A tripulação prepara o navio para a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Staff$q$, $q$equipe de funcionários$q$, $q$The staff meets every Monday morning.$q$, $q$A equipe de funcionários se reúne toda segunda de manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Foreigner$q$, $q$estrangeiro$q$, $q$She helps the foreigner find the train station.$q$, $q$Ela ajuda o estrangeiro a encontrar a estação de trem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Native$q$, $q$nativo$q$, $q$A native of the city shows us around.$q$, $q$Um nativo da cidade nos mostra os arredores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Visitor$q$, $q$visitante$q$, $q$Every visitor signs the guest book.$q$, $q$Todo visitante assina o livro de visitas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Host$q$, $q$anfitrião$q$, $q$The host welcomes us at the door.$q$, $q$O anfitrião nos recebe na porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Orphan$q$, $q$órfão$q$, $q$The orphan grows up in a small village.$q$, $q$O órfão cresce numa vila pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sibling$q$, $q$irmãos$q$, $q$Every sibling has a different personality.$q$, $q$Cada irmão ou irmã tem uma personalidade diferente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ally$q$, $q$aliado$q$, $q$She becomes an important ally during the project.$q$, $q$Ela se torna uma aliada importante durante o projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Blaze$q$, $q$incêndio$q$, $q$Firefighters control the blaze in two hours.$q$, $q$Os bombeiros controlam o incêndio em duas horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Extinguisher$q$, $q$extintor$q$, $q$There is a fire extinguisher in every room.$q$, $q$Há um extintor em cada sala.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Aid$q$, $q$primeiros socorros$q$, $q$She learns first aid at the community center.$q$, $q$Ela aprende primeiros socorros no centro comunitário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stretcher$q$, $q$maca$q$, $q$They carry the patient on a stretcher.$q$, $q$Eles carregam o paciente numa maca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Airlift$q$, $q$resgate aéreo$q$, $q$The team plans an airlift for the injured hikers.$q$, $q$A equipe planeja um resgate aéreo para os caminhantes feridos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Exit$q$, $q$saída de emergência$q$, $q$Follow the sign to the emergency exit.$q$, $q$Siga a placa para a saída de emergência.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lifejacket$q$, $q$colete salva-vidas$q$, $q$Every passenger wears a lifejacket on the boat.$q$, $q$Todo passageiro usa um colete salva-vidas no barco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Blackout$q$, $q$apagão$q$, $q$A blackout affects the whole neighborhood.$q$, $q$Um apagão afeta o bairro inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Evacuation$q$, $q$evacuação$q$, $q$The evacuation happens quickly and safely.$q$, $q$A evacuação acontece rápido e com segurança.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shelter$q$, $q$abrigo$q$, $q$They find shelter during the storm.$q$, $q$Eles encontram abrigo durante a tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Coal$q$, $q$carvão$q$, $q$The old factory burns coal for energy.$q$, $q$A fábrica antiga queima carvão para energia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Petroleum$q$, $q$petróleo bruto$q$, $q$The country exports a lot of petroleum.$q$, $q$O país exporta muito petróleo bruto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dam$q$, $q$barragem$q$, $q$The dam provides water for the whole city.$q$, $q$A barragem fornece água para a cidade inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mine$q$, $q$mina de minério$q$, $q$Workers dig deep into the mine.$q$, $q$Os trabalhadores cavam fundo na mina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ore$q$, $q$minério$q$, $q$They extract ore from the mountain.$q$, $q$Eles extraem minério da montanha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reservoir$q$, $q$reservatório$q$, $q$The reservoir supplies water during the dry season.$q$, $q$O reservatório fornece água durante a estação seca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Turbine$q$, $q$turbina$q$, $q$The turbine turns wind into electricity.$q$, $q$A turbina transforma vento em eletricidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Renewable$q$, $q$renovável$q$, $q$Solar power is a renewable source of energy.$q$, $q$Energia solar é uma fonte renovável de energia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hydroelectric$q$, $q$hidrelétrica$q$, $q$The hydroelectric plant powers three cities.$q$, $q$A hidrelétrica abastece três cidades.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Generator$q$, $q$gerador$q$, $q$We use a generator during the blackout.$q$, $q$Nós usamos um gerador durante o apagão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Follower$q$, $q$seguidor$q$, $q$She gains a new follower every day.$q$, $q$Ela ganha um seguidor novo todo dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Post$q$, $q$postagem$q$, $q$I share a post about my trip.$q$, $q$Eu compartilho uma postagem sobre minha viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Connection$q$, $q$conexão$q$, $q$The internet connection is very slow today.$q$, $q$A conexão de internet está muito lenta hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Screenshot$q$, $q$captura de tela$q$, $q$I take a screenshot of the message.$q$, $q$Eu tiro uma captura de tela da mensagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shortcut$q$, $q$atalho$q$, $q$I use a shortcut to save the file quickly.$q$, $q$Eu uso um atalho para salvar o arquivo rapidamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Feed$q$, $q$linha do tempo social$q$, $q$New photos appear on my feed every hour.$q$, $q$Fotos novas aparecem na minha linha do tempo a cada hora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Username$q$, $q$nome de usuário$q$, $q$Please enter your username and password.$q$, $q$Por favor, digite seu nome de usuário e senha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Notification$q$, $q$notificação$q$, $q$I get a notification about the meeting.$q$, $q$Eu recebo uma notificação sobre a reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bookmark$q$, $q$favorito do navegador$q$, $q$I save this article as a bookmark.$q$, $q$Eu salvo este artigo como favorito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wireless$q$, $q$sem fio$q$, $q$We connect to the wireless network in the office.$q$, $q$Nós conectamos à rede sem fio no escritório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sloppy$q$, $q$desleixado$q$, $q$His handwriting looks sloppy today.$q$, $q$A caligrafia dele parece desleixada hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shiny$q$, $q$brilhante$q$, $q$The car looks shiny after the wash.$q$, $q$O carro parece brilhante depois da lavagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dull$q$, $q$fosco$q$, $q$The old paint looks dull under the light.$q$, $q$A tinta velha parece fosca sob a luz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Colorful$q$, $q$colorido$q$, $q$She wears a colorful dress to the party.$q$, $q$Ela usa um vestido colorido para a festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Faded$q$, $q$desbotado$q$, $q$The old photo looks faded now.$q$, $q$A foto antiga parece desbotada agora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wrinkled$q$, $q$enrugado$q$, $q$My shirt looks wrinkled after the trip.$q$, $q$Minha camisa parece enrugada depois da viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stained$q$, $q$manchado$q$, $q$The tablecloth is stained with coffee.$q$, $q$A toalha de mesa está manchada de café.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Brittle$q$, $q$quebradiço$q$, $q$The dry leaves feel brittle in my hand.$q$, $q$As folhas secas parecem quebradiças na minha mão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sticky$q$, $q$pegajoso$q$, $q$My hands feel sticky after the candy.$q$, $q$Minhas mãos ficam pegajosas depois do doce.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Slippery$q$, $q$escorregadio$q$, $q$The floor is slippery after the rain.$q$, $q$O chão está escorregadio depois da chuva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Noun$q$, $q$substantivo$q$, $q$Use a noun to name the object in your sentence.$q$, $q$Use um substantivo para nomear o objeto na sua frase.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Syllable$q$, $q$sílaba$q$, $q$The last syllable of the word is stressed.$q$, $q$A última sílaba da palavra é acentuada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sentence$q$, $q$frase$q$, $q$She writes a short sentence on the board.$q$, $q$Ela escreve uma frase curta no quadro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Paragraph$q$, $q$parágrafo$q$, $q$Read the first paragraph carefully.$q$, $q$Leia o primeiro parágrafo com atenção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Comma$q$, $q$vírgula$q$, $q$Add a comma after the first word.$q$, $q$Adicione uma vírgula depois da primeira palavra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Quotation$q$, $q$aspas$q$, $q$Put the sentence in quotation marks.$q$, $q$Coloque a frase entre aspas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Synonym$q$, $q$sinônimo$q$, $q$Find a synonym for the word 'happy'.$q$, $q$Encontre um sinônimo para a palavra 'feliz'.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Antonym$q$, $q$antônimo$q$, $q$Can you think of an antonym for this word?$q$, $q$Você consegue pensar num antônimo para esta palavra?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vowel$q$, $q$vogal$q$, $q$This word starts with a vowel sound.$q$, $q$Esta palavra começa com um som de vogal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spelling$q$, $q$ortografia$q$, $q$I check the spelling before I send the email.$q$, $q$Eu confiro a ortografia antes de enviar o e-mail.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Recite$q$, $q$recitar$q$, $q$I recite the poem from memory.$q$, $q$Eu recito o poema de memória.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Narrate$q$, $q$narrar$q$, $q$I narrate the story to the children.$q$, $q$Eu narro a história para as crianças.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Describe$q$, $q$descrever$q$, $q$Please describe the man you saw.$q$, $q$Por favor, descreva o homem que você viu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Elaborate$q$, $q$explicar em detalhes$q$, $q$Can you elaborate on your last point?$q$, $q$Você pode explicar em detalhes seu último ponto?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Summarize$q$, $q$resumir$q$, $q$I summarize the chapter in three sentences.$q$, $q$Eu resumo o capítulo em três frases.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Translate$q$, $q$traduzir$q$, $q$I translate the letter into English.$q$, $q$Eu traduzo a carta para o inglês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pronounce$q$, $q$pronunciar$q$, $q$I struggle to pronounce this word.$q$, $q$Eu tenho dificuldade em pronunciar esta palavra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spell$q$, $q$soletrar$q$, $q$Can you spell your last name, please?$q$, $q$Você pode soletrar seu sobrenome, por favor?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Repeat$q$, $q$repetir$q$, $q$Please repeat the question slowly.$q$, $q$Por favor, repita a pergunta devagar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reply$q$, $q$responder de volta$q$, $q$I reply to her message right away.$q$, $q$Eu respondo à mensagem dela na hora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Press$q$, $q$apertar$q$, $q$I press the button to start the machine.$q$, $q$Eu aperto o botão para ligar a máquina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Trigger$q$, $q$acionar$q$, $q$A loud noise can trigger the alarm.$q$, $q$Um barulho alto pode acionar o alarme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Unplug$q$, $q$desconectar da tomada$q$, $q$I unplug the toaster after breakfast.$q$, $q$Eu desconecto a torradeira depois do café da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Connect$q$, $q$conectar$q$, $q$I connect my phone to the printer.$q$, $q$Eu conecto meu telefone à impressora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Install$q$, $q$instalar$q$, $q$I install the new update on my computer.$q$, $q$Eu instalo a nova atualização no meu computador.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Charge$q$, $q$carregar a bateria$q$, $q$I charge my phone before I leave home.$q$, $q$Eu carrego meu telefone antes de sair de casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Delete$q$, $q$apagar arquivo$q$, $q$I delete the old photos from my phone.$q$, $q$Eu apago as fotos antigas do meu telefone.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Copy$q$, $q$copiar$q$, $q$I copy the file to a new folder.$q$, $q$Eu copio o arquivo para uma pasta nova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Save$q$, $q$salvar economizando$q$, $q$I save the document before closing it.$q$, $q$Eu salvo o documento antes de fechá-lo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Browse$q$, $q$navegar na internet$q$, $q$I browse the internet for new recipes.$q$, $q$Eu navego na internet atrás de receitas novas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Can$q$, $q$lata$q$, $q$I open a can of soup for lunch.$q$, $q$Eu abro uma lata de sopa para o almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jar$q$, $q$pote de vidro$q$, $q$She keeps the sugar in a glass jar.$q$, $q$Ela guarda o açúcar num pote de vidro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Carton$q$, $q$caixa de papelão$q$, $q$I move the books in a carton.$q$, $q$Eu movo os livros numa caixa de papelão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Package$q$, $q$embalagem$q$, $q$The package arrives earlier than expected.$q$, $q$A embalagem chega mais cedo do que o esperado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lid$q$, $q$tampa$q$, $q$Close the lid tightly before shaking.$q$, $q$Feche a tampa com força antes de sacudir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cork$q$, $q$rolha$q$, $q$He removes the cork from the bottle.$q$, $q$Ele tira a rolha da garrafa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tape$q$, $q$fita adesiva$q$, $q$I fix the box with strong tape.$q$, $q$Eu conserto a caixa com fita adesiva forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$String$q$, $q$barbante$q$, $q$She ties the gift with a piece of string.$q$, $q$Ela amarra o presente com um pedaço de barbante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sponge$q$, $q$esponja$q$, $q$I clean the plate with a sponge.$q$, $q$Eu limpo o prato com uma esponja.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hamper$q$, $q$cesto de roupa$q$, $q$I put the dirty clothes in the hamper.$q$, $q$Eu ponho a roupa suja no cesto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
