-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote4.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Headline$q$, $q$manchete$q$, $q$The headline announces the election results.$q$, $q$A manchete anuncia os resultados da eleição.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reporter$q$, $q$repórter$q$, $q$The reporter interviews the mayor.$q$, $q$O repórter entrevista o prefeito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Interviewee$q$, $q$entrevistado$q$, $q$The interviewee answers each question calmly.$q$, $q$O entrevistado responde cada pergunta com calma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Broadcast$q$, $q$transmissão$q$, $q$The channel starts its evening broadcast.$q$, $q$O canal começa sua transmissão da noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Subscription$q$, $q$assinatura$q$, $q$I cancel my magazine subscription.$q$, $q$Eu cancelo minha assinatura da revista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Advertisement$q$, $q$propaganda$q$, $q$This advertisement appears during the show.$q$, $q$Esta propaganda aparece durante o programa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ratings$q$, $q$audiência$q$, $q$The show gets high ratings this week.$q$, $q$O programa tem audiência alta esta semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Censorship$q$, $q$censura$q$, $q$The film faces censorship in some countries.$q$, $q$O filme enfrenta censura em alguns países.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hoax$q$, $q$notícia falsa$q$, $q$The article turns out to be a hoax.$q$, $q$O artigo se revela uma notícia falsa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Source$q$, $q$fonte de informação$q$, $q$She checks the source before sharing the news.$q$, $q$Ela confere a fonte antes de compartilhar a notícia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Government$q$, $q$governo$q$, $q$The government announces a new policy.$q$, $q$O governo anuncia uma nova política.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Parliament$q$, $q$parlamento$q$, $q$Parliament votes on the new law tomorrow.$q$, $q$O parlamento vota a nova lei amanhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Elected$q$, $q$eleito$q$, $q$She is elected mayor of the city.$q$, $q$Ela é eleita prefeita da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ballot$q$, $q$cédula de votação$q$, $q$He drops his ballot into the box.$q$, $q$Ele coloca a cédula de votação na urna.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Campaign$q$, $q$campanha eleitoral$q$, $q$The campaign focuses on education.$q$, $q$A campanha eleitoral foca em educação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Coalition$q$, $q$coalizão$q$, $q$Two parties form a coalition after the election.$q$, $q$Dois partidos formam uma coalizão depois da eleição.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Income$q$, $q$renda$q$, $q$Her income increases after the promotion.$q$, $q$A renda dela aumenta depois da promoção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Amendment$q$, $q$emenda$q$, $q$The amendment changes an old rule.$q$, $q$A emenda muda uma regra antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Demonstration$q$, $q$manifestação$q$, $q$Thousands join the peaceful demonstration.$q$, $q$Milhares participam da manifestação pacífica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Strike$q$, $q$greve$q$, $q$Workers organize a strike over wages.$q$, $q$Os trabalhadores organizam uma greve por causa dos salários.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Inflation$q$, $q$inflação$q$, $q$Inflation raises the price of food.$q$, $q$A inflação aumenta o preço da comida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Unemployment$q$, $q$desemprego$q$, $q$Unemployment falls this quarter.$q$, $q$O desemprego cai neste trimestre.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Goods$q$, $q$mercadoria$q$, $q$The store sells imported goods.$q$, $q$A loja vende mercadorias importadas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Inventory$q$, $q$estoque$q$, $q$The shop checks its inventory every month.$q$, $q$A loja confere o estoque todo mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Boom$q$, $q$expansão econômica$q$, $q$The city experiences an economic boom.$q$, $q$A cidade vive uma expansão econômica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Recession$q$, $q$recessão$q$, $q$The country enters a recession this year.$q$, $q$O país entra em recessão este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stock$q$, $q$ação de empresa$q$, $q$He buys stock in a technology company.$q$, $q$Ele compra ação de uma empresa de tecnologia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wage$q$, $q$salário-base$q$, $q$The minimum wage increases next month.$q$, $q$O salário mínimo aumenta no próximo mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Consumer$q$, $q$consumidor$q$, $q$The consumer expects better quality.$q$, $q$O consumidor espera uma qualidade melhor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shortage$q$, $q$escassez$q$, $q$The region faces a water shortage.$q$, $q$A região enfrenta uma escassez de água.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Memory$q$, $q$memória$q$, $q$This song brings back a happy memory.$q$, $q$Esta música traz de volta uma memória feliz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Thought$q$, $q$pensamento$q$, $q$A sudden thought crosses her mind.$q$, $q$Um pensamento repentino cruza a mente dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Behavior$q$, $q$comportamento$q$, $q$His behavior changes after the trip.$q$, $q$O comportamento dele muda depois da viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Personality$q$, $q$personalidade$q$, $q$She has a very warm personality.$q$, $q$Ela tem uma personalidade muito calorosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Awareness$q$, $q$consciência$q$, $q$The campaign raises awareness about recycling.$q$, $q$A campanha aumenta a consciência sobre reciclagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pressure$q$, $q$pressão$q$, $q$She handles pressure well at work.$q$, $q$Ela lida bem com pressão no trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Motivation$q$, $q$motivação$q$, $q$His motivation grows after the success.$q$, $q$A motivação dele cresce depois do sucesso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Emotion$q$, $q$emoção$q$, $q$She hides her emotion during the interview.$q$, $q$Ela esconde a emoção durante a entrevista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Intuition$q$, $q$intuição$q$, $q$He trusts his intuition on big decisions.$q$, $q$Ele confia na intuição dele em decisões grandes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mindset$q$, $q$mentalidade$q$, $q$A positive mindset helps her succeed.$q$, $q$Uma mentalidade positiva ajuda ela a ter sucesso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Blender$q$, $q$liquidificador$q$, $q$She mixes the fruit in a blender.$q$, $q$Ela mistura a fruta num liquidificador.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sieve$q$, $q$peneira$q$, $q$He strains the flour through a sieve.$q$, $q$Ele passa a farinha por uma peneira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Grater$q$, $q$ralador$q$, $q$She uses a grater for the cheese.$q$, $q$Ela usa um ralador para o queijo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Corkscrew$q$, $q$saca-rolhas$q$, $q$He opens the bottle with a corkscrew.$q$, $q$Ele abre a garrafa com um saca-rolhas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ladle$q$, $q$concha$q$, $q$She serves the soup with a ladle.$q$, $q$Ela serve a sopa com uma concha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spatula$q$, $q$espátula$q$, $q$He flips the pancake with a spatula.$q$, $q$Ele vira a panqueca com uma espátula.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Apron$q$, $q$avental$q$, $q$She wears an apron while cooking.$q$, $q$Ela usa um avental enquanto cozinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mitt$q$, $q$luva de cozinha$q$, $q$He wears a mitt to take the pan out.$q$, $q$Ele usa uma luva de cozinha para tirar a panela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Whisk$q$, $q$batedor de claras$q$, $q$She uses a whisk to beat the eggs.$q$, $q$Ela usa um batedor para bater os ovos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Colander$q$, $q$escorredor$q$, $q$He drains the pasta in a colander.$q$, $q$Ele escorre a massa num escorredor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stapler$q$, $q$grampeador$q$, $q$She keeps a stapler on her desk.$q$, $q$Ela mantém um grampeador na mesa dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Paperclip$q$, $q$clipe de papel$q$, $q$He attaches the papers with a paperclip.$q$, $q$Ele prende os papéis com um clipe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Folder$q$, $q$pasta de arquivos$q$, $q$She keeps all the files in one folder.$q$, $q$Ela guarda todos os arquivos numa pasta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Clipboard$q$, $q$prancheta$q$, $q$The nurse carries a clipboard with notes.$q$, $q$A enfermeira carrega uma prancheta com anotações.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Calculator$q$, $q$calculadora$q$, $q$He uses a calculator during the exam.$q$, $q$Ele usa uma calculadora durante a prova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Planner$q$, $q$agenda de compromissos$q$, $q$She writes her tasks in a planner.$q$, $q$Ela escreve as tarefas dela numa agenda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Label$q$, $q$etiqueta$q$, $q$He puts a label on each box.$q$, $q$Ele coloca uma etiqueta em cada caixa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sharpener$q$, $q$apontador$q$, $q$She uses a sharpener for her pencil.$q$, $q$Ela usa um apontador para o lápis dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Swivel$q$, $q$cadeira giratória$q$, $q$The base of the chair can swivel.$q$, $q$A base da cadeira pode girar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Highlighter$q$, $q$marcador de texto$q$, $q$She marks the important words with a highlighter.$q$, $q$Ela marca as palavras importantes com um marcador.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Celebration$q$, $q$comemoração$q$, $q$The whole family joins the celebration.$q$, $q$A família toda participa da comemoração.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Invitation$q$, $q$convite$q$, $q$She sends the invitation two weeks early.$q$, $q$Ela envia o convite duas semanas antes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Costume$q$, $q$fantasia$q$, $q$He wears a funny costume to the party.$q$, $q$Ele usa uma fantasia engraçada na festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fireworks$q$, $q$fogos de artifício$q$, $q$The fireworks light up the whole sky.$q$, $q$Os fogos de artifício iluminam o céu inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cheers$q$, $q$brinde$q$, $q$They raise their glasses for cheers.$q$, $q$Eles levantam os copos para o brinde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Decoration$q$, $q$decoração$q$, $q$She adds colorful decoration to the room.$q$, $q$Ela acrescenta decoração colorida ao quarto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Confetti$q$, $q$confete$q$, $q$Confetti falls over the crowd.$q$, $q$Confete cai sobre a multidão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Souvenir$q$, $q$lembrancinha$q$, $q$He buys a small souvenir from the trip.$q$, $q$Ele compra uma lembrancinha da viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gala$q$, $q$jantar de gala$q$, $q$They attend a gala at the hotel.$q$, $q$Eles participam de um jantar de gala no hotel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ceremony$q$, $q$cerimônia$q$, $q$The ceremony starts at six o'clock.$q$, $q$A cerimônia começa às seis horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Faith$q$, $q$fé$q$, $q$She keeps her faith during hard times.$q$, $q$Ela mantém a fé durante tempos difíceis.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Compassion$q$, $q$compaixão$q$, $q$He treats every patient with compassion.$q$, $q$Ele trata cada paciente com compaixão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Duty$q$, $q$dever moral$q$, $q$It is his duty to protect his team.$q$, $q$É dever dele proteger a equipe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Honor$q$, $q$honra$q$, $q$She feels great honor to receive the award.$q$, $q$Ela sente grande honra em receber o prêmio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Justice$q$, $q$justiça$q$, $q$They demand justice for the victims.$q$, $q$Eles exigem justiça para as vítimas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Respect$q$, $q$respeito$q$, $q$Students show respect to their teachers.$q$, $q$Os alunos demonstram respeito pelos professores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Charity$q$, $q$caridade$q$, $q$The company donates money to charity.$q$, $q$A empresa doa dinheiro para caridade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vanity$q$, $q$vaidade$q$, $q$His vanity makes him hard to work with.$q$, $q$A vaidade dele dificulta trabalhar com ele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ethics$q$, $q$ética$q$, $q$The course teaches professional ethics.$q$, $q$O curso ensina ética profissional.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wisdom$q$, $q$sabedoria$q$, $q$She shares her wisdom with younger workers.$q$, $q$Ela compartilha sua sabedoria com trabalhadores mais jovens.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shape$q$, $q$moldar$q$, $q$Success can shape a person's confidence.$q$, $q$O sucesso pode moldar a confiança de uma pessoa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Replace$q$, $q$substituir$q$, $q$We replace the old machine with a new one.$q$, $q$Nós substituímos a máquina velha por uma nova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Conform$q$, $q$amoldar-se$q$, $q$It is hard for him to conform to strict rules.$q$, $q$É difícil para ele se amoldar a regras rígidas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Adjust$q$, $q$ajustar$q$, $q$I adjust my schedule for the trip.$q$, $q$Eu ajusto minha agenda para a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Exchange$q$, $q$trocar dinheiro$q$, $q$I exchange my dollars for euros.$q$, $q$Eu troco meus dólares por euros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Expand$q$, $q$ampliar$q$, $q$The company plans to expand next year.$q$, $q$A empresa planeja se expandir no próximo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shrink$q$, $q$encolher$q$, $q$The shirt starts to shrink after washing.$q$, $q$A camisa começa a encolher depois de lavada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Accelerate$q$, $q$acelerar$q$, $q$The car starts to accelerate on the highway.$q$, $q$O carro começa a acelerar na rodovia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Decelerate$q$, $q$desacelerar$q$, $q$The train begins to decelerate near the station.$q$, $q$O trem começa a desacelerar perto da estação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Evolve$q$, $q$evoluir$q$, $q$Technology continues to evolve every year.$q$, $q$A tecnologia continua a evoluir todo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spot$q$, $q$avistar$q$, $q$I spot my friend in the crowd.$q$, $q$Eu avisto meu amigo na multidão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Observe$q$, $q$observar$q$, $q$Scientists observe the animals closely.$q$, $q$Os cientistas observam os animais de perto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Realize$q$, $q$perceber$q$, $q$I realize my mistake too late.$q$, $q$Eu percebo meu erro tarde demais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Glimpse$q$, $q$vislumbrar$q$, $q$I glimpse the sea from the window.$q$, $q$Eu vislumbro o mar pela janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Distinguish$q$, $q$distinguir$q$, $q$It is hard to distinguish the twins.$q$, $q$É difícil distinguir os gêmeos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Suspect$q$, $q$suspeitar$q$, $q$The police suspect the neighbor.$q$, $q$A polícia suspeita do vizinho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Imagine$q$, $q$imaginar$q$, $q$I imagine a better future for everyone.$q$, $q$Eu imagino um futuro melhor para todos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Recall$q$, $q$relembrar$q$, $q$She tries to recall his name.$q$, $q$Ela tenta relembrar o nome dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Overlook$q$, $q$deixar passar despercebido$q$, $q$Don't overlook the small details.$q$, $q$Não deixe os pequenos detalhes passarem despercebidos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Predict$q$, $q$prever$q$, $q$Experts predict a mild winter this year.$q$, $q$Especialistas preveem um inverno ameno este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
