-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote8.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Concept$q$, $q$conceito$q$, $q$The teacher explains a new concept.$q$, $q$O professor explica um conceito novo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cause$q$, $q$causa$q$, $q$Doctors look for the cause of the illness.$q$, $q$Os médicos procuram a causa da doença.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Effect$q$, $q$efeito$q$, $q$The medicine has an immediate effect.$q$, $q$O remédio tem um efeito imediato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Consequence$q$, $q$consequência$q$, $q$Every choice has a consequence.$q$, $q$Toda escolha tem uma consequência.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Solution$q$, $q$solução$q$, $q$We find a simple solution to the problem.$q$, $q$Nós encontramos uma solução simples para o problema.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Opportunity$q$, $q$oportunidade$q$, $q$This job offers a great opportunity.$q$, $q$Este emprego oferece uma grande oportunidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Challenge$q$, $q$desafio difícil$q$, $q$Learning a new language is a real challenge.$q$, $q$Aprender um novo idioma é um desafio de verdade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Outcome$q$, $q$resultado final$q$, $q$The outcome of the match surprises everyone.$q$, $q$O resultado final da partida surpreende todo mundo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Purpose$q$, $q$propósito$q$, $q$The purpose of the meeting is clear.$q$, $q$O propósito da reunião é claro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Stage$q$, $q$etapa$q$, $q$We are at the first stage of the project.$q$, $q$Nós estamos na primeira etapa do projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Decade$q$, $q$década$q$, $q$The city changes a lot in a decade.$q$, $q$A cidade muda muito em uma década.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Millennium$q$, $q$milênio$q$, $q$The new millennium brings new technology.$q$, $q$O novo milênio traz tecnologia nova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fortnight$q$, $q$quinzena$q$, $q$We go on vacation for a fortnight.$q$, $q$Nós saímos de férias por uma quinzena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Twilight$q$, $q$crepúsculo$q$, $q$The sky turns orange at twilight.$q$, $q$O céu fica laranja no crepúsculo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dawn$q$, $q$amanhecer$q$, $q$We leave home before dawn.$q$, $q$Nós saímos de casa antes do amanhecer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dusk$q$, $q$entardecer$q$, $q$The birds sing loudly at dusk.$q$, $q$Os pássaros cantam alto ao entardecer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Eternity$q$, $q$eternidade$q$, $q$The wait feels like an eternity.$q$, $q$A espera parece uma eternidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lapse$q$, $q$lapso$q$, $q$A short lapse in attention causes the accident.$q$, $q$Um pequeno lapso de atenção causa o acidente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Timeline$q$, $q$cronograma$q$, $q$We follow a strict timeline for the project.$q$, $q$Nós seguimos um cronograma rígido para o projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Calendar$q$, $q$calendário$q$, $q$She marks the date on her calendar.$q$, $q$Ela marca a data no calendário dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spicy$q$, $q$picante$q$, $q$This curry is too spicy for me.$q$, $q$Este curry é muito picante para mim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fragrant$q$, $q$perfumado$q$, $q$The garden smells fragrant in spring.$q$, $q$O jardim tem um cheiro perfumado na primavera.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Smelly$q$, $q$fedido$q$, $q$The old shoes are very smelly.$q$, $q$Os sapatos velhos são muito fedidos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Crunchy$q$, $q$crocante$q$, $q$I like a crunchy salad with nuts.$q$, $q$Eu gosto de uma salada crocante com nozes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Creamy$q$, $q$cremoso$q$, $q$This soup is thick and creamy.$q$, $q$Esta sopa é grossa e cremosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Juicy$q$, $q$suculento$q$, $q$The peach is sweet and juicy.$q$, $q$O pêssego é doce e suculento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ripe$q$, $q$maduro$q$, $q$Choose a ripe banana for the smoothie.$q$, $q$Escolha uma banana madura para a vitamina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rotten$q$, $q$podre$q$, $q$The apple looks rotten inside.$q$, $q$A maçã parece podre por dentro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Greasy$q$, $q$gorduroso$q$, $q$This food is too greasy for dinner.$q$, $q$Esta comida é muito gordurosa para o jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tasty$q$, $q$saboroso$q$, $q$The homemade bread is very tasty.$q$, $q$O pão caseiro é muito saboroso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bracelet$q$, $q$pulseira$q$, $q$She wears a silver bracelet on her wrist.$q$, $q$Ela usa uma pulseira de prata no pulso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Earring$q$, $q$brinco$q$, $q$He gives her a gold earring for her birthday.$q$, $q$Ele dá um brinco de ouro para ela de aniversário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wristwatch$q$, $q$relógio de pulso$q$, $q$My grandfather gives me his old wristwatch.$q$, $q$Meu avô me dá o relógio de pulso antigo dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sunglasses$q$, $q$óculos de sol$q$, $q$She puts on sunglasses before leaving the house.$q$, $q$Ela coloca óculos de sol antes de sair de casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sandal$q$, $q$chinelo$q$, $q$I wear a sandal at the beach.$q$, $q$Eu uso um chinelo na praia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Footwear$q$, $q$calçado esportivo$q$, $q$This store sells comfortable footwear.$q$, $q$Esta loja vende calçado confortável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Purse$q$, $q$bolsa de mão$q$, $q$She keeps her keys in her purse.$q$, $q$Ela guarda as chaves na bolsa de mão dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Beret$q$, $q$boina$q$, $q$He wears a black beret in winter.$q$, $q$Ele usa uma boina preta no inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Handkerchief$q$, $q$lenço de bolso$q$, $q$My grandfather always carries a handkerchief.$q$, $q$Meu avô sempre carrega um lenço de bolso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vest$q$, $q$colete$q$, $q$She wears a vest over her shirt.$q$, $q$Ela usa um colete por cima da camisa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Seashell$q$, $q$concha do mar$q$, $q$The child collects a seashell on the beach.$q$, $q$A criança coleta uma concha do mar na praia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tide$q$, $q$maré$q$, $q$The tide comes in during the afternoon.$q$, $q$A maré sobe durante a tarde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reef$q$, $q$recife de coral$q$, $q$Divers explore the colorful reef.$q$, $q$Mergulhadores exploram o recife colorido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dolphin$q$, $q$golfinho$q$, $q$A dolphin jumps near the boat.$q$, $q$Um golfinho pula perto do barco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Octopus$q$, $q$polvo$q$, $q$The octopus hides among the rocks.$q$, $q$O polvo se esconde entre as pedras.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Crab$q$, $q$caranguejo$q$, $q$A crab walks sideways on the sand.$q$, $q$Um caranguejo anda de lado na areia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jellyfish$q$, $q$água-viva$q$, $q$A jellyfish floats near the shore.$q$, $q$Uma água-viva flutua perto da costa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Starfish$q$, $q$estrela-do-mar$q$, $q$We find a starfish in the shallow water.$q$, $q$Nós encontramos uma estrela-do-mar na água rasa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Seal$q$, $q$foca$q$, $q$A seal rests on the rocky shore.$q$, $q$Uma foca descansa na costa rochosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Penguin$q$, $q$pinguim$q$, $q$A penguin waddles across the ice.$q$, $q$Um pinguim se move desajeitado pelo gelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jungle$q$, $q$selva$q$, $q$The explorer walks through the thick jungle.$q$, $q$O explorador caminha pela selva densa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vine$q$, $q$trepadeira$q$, $q$A vine climbs up the old wall.$q$, $q$Uma trepadeira sobe pela parede velha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Moss$q$, $q$musgo$q$, $q$Moss covers the shaded rocks.$q$, $q$Musgo cobre as pedras sombreadas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jaguar$q$, $q$onça-pintada$q$, $q$A jaguar hunts near the river at night.$q$, $q$Uma onça-pintada caça perto do rio à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Alligator$q$, $q$jacaré$q$, $q$An alligator swims quietly in the swamp.$q$, $q$Um jacaré nada silenciosamente no pântano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Caterpillar$q$, $q$lagarta$q$, $q$A caterpillar eats the leaf slowly.$q$, $q$Uma lagarta come a folha devagar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Moth$q$, $q$mariposa$q$, $q$A moth flies around the porch light.$q$, $q$Uma mariposa voa em volta da luz da varanda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dragonfly$q$, $q$libélula$q$, $q$A dragonfly rests on the flower.$q$, $q$Uma libélula pousa na flor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Beetle$q$, $q$besouro$q$, $q$A beetle crawls across the path.$q$, $q$Um besouro rasteja pela trilha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Grasshopper$q$, $q$gafanhoto$q$, $q$A grasshopper jumps through the grass.$q$, $q$Um gafanhoto pula pela grama.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Advantage$q$, $q$vantagem$q$, $q$Speaking two languages gives him an advantage.$q$, $q$Falar dois idiomas dá a ele uma vantagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Drawback$q$, $q$desvantagem$q$, $q$The only drawback is the high price.$q$, $q$A única desvantagem é o preço alto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Benefit$q$, $q$benefício$q$, $q$Exercise gives you a big health benefit.$q$, $q$Exercício te dá um grande benefício para a saúde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Viewpoint$q$, $q$ponto de vista$q$, $q$I respect her viewpoint even if I disagree.$q$, $q$Eu respeito o ponto de vista dela mesmo discordando.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Concern$q$, $q$preocupação$q$, $q$Safety is our main concern.$q$, $q$Segurança é nossa principal preocupação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Proof$q$, $q$prova concreta$q$, $q$We need proof before accusing him.$q$, $q$Nós precisamos de prova concreta antes de acusá-lo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Assumption$q$, $q$suposição$q$, $q$Her plan is based on a wrong assumption.$q$, $q$O plano dela é baseado numa suposição errada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Belief$q$, $q$crença$q$, $q$It is his personal belief, not a fact.$q$, $q$É uma crença pessoal dele, não um fato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Priority$q$, $q$prioridade$q$, $q$Family is my top priority.$q$, $q$Família é minha principal prioridade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Trend$q$, $q$tendência$q$, $q$This color is a popular trend this year.$q$, $q$Esta cor é uma tendência popular este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Greet$q$, $q$cumprimentar$q$, $q$I greet my neighbors every morning.$q$, $q$Eu cumprimento meus vizinhos toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Introduce$q$, $q$apresentar alguém$q$, $q$Let me introduce you to my sister.$q$, $q$Deixe-me apresentar você à minha irmã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Thank$q$, $q$agradecer$q$, $q$I thank her for the kind gift.$q$, $q$Eu agradeço a ela pelo presente gentil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Comfort$q$, $q$consolar$q$, $q$I comfort my friend after the bad news.$q$, $q$Eu conforto meu amigo depois da má notícia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Quarrel$q$, $q$brigar$q$, $q$The brothers quarrel over the remote control.$q$, $q$Os irmãos brigam pelo controle remoto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Reconcile$q$, $q$reconciliar$q$, $q$They finally reconcile after the argument.$q$, $q$Eles finalmente se reconciliam depois da discussão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Argue$q$, $q$discutir$q$, $q$We argue about small things sometimes.$q$, $q$Nós discutimos sobre coisas pequenas às vezes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tease$q$, $q$zombar$q$, $q$My brother likes to tease me about my hair.$q$, $q$Meu irmão gosta de zombar do meu cabelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Provoke$q$, $q$provocar$q$, $q$He tries not to provoke his sister.$q$, $q$Ele tenta não provocar a irmã dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Collaborate$q$, $q$colaborar$q$, $q$The two teams collaborate on the new project.$q$, $q$As duas equipes colaboram no novo projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Similar$q$, $q$semelhante$q$, $q$Her opinion is similar to mine.$q$, $q$A opinião dela é semelhante à minha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Equal$q$, $q$igual em valor$q$, $q$Both offers seem equal in value.$q$, $q$As duas ofertas parecem iguais em valor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Opposite$q$, $q$oposto$q$, $q$His answer is the opposite of hers.$q$, $q$A resposta dele é o oposto da dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Typical$q$, $q$típico$q$, $q$This is a typical rainy day here.$q$, $q$Este é um dia de chuva típico aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Exact$q$, $q$exato$q$, $q$I don't know the exact time of the meeting.$q$, $q$Eu não sei a hora exata da reunião.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Approximate$q$, $q$aproximado$q$, $q$Give me an approximate price for the trip.$q$, $q$Me dê um preço aproximado para a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Entire$q$, $q$inteiro$q$, $q$She reads the entire book in one day.$q$, $q$Ela lê o livro inteiro em um dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Partial$q$, $q$parcial$q$, $q$We receive only a partial payment.$q$, $q$Nós recebemos só um pagamento parcial.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ordinary$q$, $q$comum de todo dia$q$, $q$It is just an ordinary weekday for us.$q$, $q$É só um dia de semana comum para nós.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Extra$q$, $q$adicional$q$, $q$Bring extra water for the hike.$q$, $q$Traga água adicional para a caminhada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Supervise$q$, $q$supervisionar$q$, $q$I supervise a team of ten people.$q$, $q$Eu supervisiono uma equipe de dez pessoas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Delegate$q$, $q$delegar$q$, $q$I delegate some tasks to my assistant.$q$, $q$Eu delego algumas tarefas ao meu assistente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Deliver$q$, $q$entregar$q$, $q$I deliver the report by Friday.$q$, $q$Eu entrego o relatório até sexta-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Attach$q$, $q$anexar$q$, $q$I attach the file to the email.$q$, $q$Eu anexo o arquivo ao e-mail.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Review$q$, $q$revisar$q$, $q$I review the contract before signing it.$q$, $q$Eu reviso o contrato antes de assiná-lo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Exhibit$q$, $q$mostrar em público$q$, $q$I exhibit my paintings downtown.$q$, $q$Eu mostro minhas pinturas em público no centro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Register$q$, $q$inscrever-se$q$, $q$I register for the course online.$q$, $q$Eu me inscrevo no curso online.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Apply$q$, $q$candidatar-se$q$, $q$I apply for the manager position.$q$, $q$Eu me candidato à vaga de gerente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Earn$q$, $q$ganhar dinheiro$q$, $q$I earn extra money on weekends.$q$, $q$Eu ganho dinheiro extra nos fins de semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Resign$q$, $q$renunciar$q$, $q$She decides to resign from her job.$q$, $q$Ela decide renunciar ao emprego dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
