-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote9.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chameleon$q$, $q$camaleão$q$, $q$The chameleon changes color to match the leaves.$q$, $q$O camaleão muda de cor para combinar com as folhas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hyena$q$, $q$hiena$q$, $q$A hyena scavenges near the edge of the savanna.$q$, $q$Uma hiena vasculha perto da borda da savana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chimpanzee$q$, $q$chimpanzé$q$, $q$A chimpanzee uses a stick to reach the fruit.$q$, $q$Um chimpanzé usa um graveto para alcançar a fruta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rhinoceros$q$, $q$rinoceronte$q$, $q$A rhinoceros grazes quietly near the waterhole.$q$, $q$Um rinoceronte pasta tranquilamente perto do poço d'água.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Kangaroo$q$, $q$canguru$q$, $q$A kangaroo hops across the open field.$q$, $q$Um canguru pula pelo campo aberto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lynx$q$, $q$lince$q$, $q$A lynx moves silently through the snow.$q$, $q$Um lince se move silenciosamente pela neve.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Otter$q$, $q$lontra$q$, $q$An otter plays in the cold mountain stream.$q$, $q$Uma lontra brinca no riacho frio da montanha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Badger$q$, $q$texugo$q$, $q$A badger digs a burrow under the old oak.$q$, $q$Um texugo cava uma toca embaixo do carvalho antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Beaver$q$, $q$castor$q$, $q$A beaver builds a dam across the stream.$q$, $q$Um castor constrói uma barragem no riacho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Armadillo$q$, $q$tatu$q$, $q$An armadillo curls into a ball for protection.$q$, $q$Um tatu se enrola numa bola para se proteger.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Toucan$q$, $q$tucano$q$, $q$A toucan perches on a branch near the river.$q$, $q$Um tucano pousa num galho perto do rio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Albatross$q$, $q$albatroz$q$, $q$An albatross glides over the ocean for hours.$q$, $q$Um albatroz plana sobre o oceano por horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Viper$q$, $q$víbora$q$, $q$A viper hides beneath the fallen leaves.$q$, $q$Uma víbora se esconde sob as folhas caídas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Crocodile$q$, $q$crocodilo$q$, $q$A crocodile waits silently near the riverbank.$q$, $q$Um crocodilo espera silenciosamente perto da margem do rio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Salamander$q$, $q$salamandra$q$, $q$A salamander hides under the wet rock.$q$, $q$Uma salamandra se esconde debaixo da pedra molhada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Heron$q$, $q$garça$q$, $q$A heron stands still in the shallow water.$q$, $q$Uma garça fica parada na água rasa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stork$q$, $q$cegonha$q$, $q$A stork builds its nest on the chimney.$q$, $q$Uma cegonha constrói o ninho dela na chaminé.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Partridge$q$, $q$perdiz$q$, $q$A partridge runs through the tall grass.$q$, $q$Uma perdiz corre pela grama alta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pheasant$q$, $q$faisão$q$, $q$A pheasant flies up suddenly from the bushes.$q$, $q$Um faisão voa repentinamente para cima dos arbustos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Quail$q$, $q$codorna$q$, $q$A quail nests quietly near the hedge.$q$, $q$Uma codorna faz ninho tranquilamente perto da cerca viva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tuna$q$, $q$atum$q$, $q$The boat returns with a large catch of tuna.$q$, $q$O barco retorna com uma grande pesca de atum.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cod$q$, $q$bacalhau$q$, $q$The restaurant serves fresh cod with lemon.$q$, $q$O restaurante serve bacalhau fresco com limão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stingray$q$, $q$arraia$q$, $q$A stingray glides silently along the sea floor.$q$, $q$Uma arraia desliza silenciosamente pelo fundo do mar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Eel$q$, $q$enguia$q$, $q$An eel slips between the rocks in the reef.$q$, $q$Uma enguia desliza entre as pedras no recife.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Squid$q$, $q$lula$q$, $q$A squid releases ink to escape the predator.$q$, $q$Uma lula solta tinta para escapar do predador.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Seahorse$q$, $q$cavalo-marinho$q$, $q$A tiny seahorse clings to the coral.$q$, $q$Um cavalo-marinho pequeno se agarra ao coral.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lobster$q$, $q$lagosta$q$, $q$The chef prepares a whole lobster for the table.$q$, $q$O chef prepara uma lagosta inteira para a mesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Oyster$q$, $q$ostra$q$, $q$She opens the oyster carefully with a small knife.$q$, $q$Ela abre a ostra com cuidado com uma faca pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mussel$q$, $q$mexilhão$q$, $q$The soup includes fresh mussel from the coast.$q$, $q$A sopa inclui mexilhão fresco da costa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Anchovy$q$, $q$anchova$q$, $q$A single anchovy adds a salty flavor to the sauce.$q$, $q$Uma única anchova acrescenta um sabor salgado ao molho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fern$q$, $q$samambaia$q$, $q$A fern grows in the shaded corner of the garden.$q$, $q$Uma samambaia cresce no canto sombreado do jardim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Orchid$q$, $q$orquídea$q$, $q$The orchid blooms only once a year.$q$, $q$A orquídea floresce só uma vez por ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sunflower$q$, $q$girassol$q$, $q$A tall sunflower turns toward the sun all day.$q$, $q$Um girassol alto se vira para o sol o dia todo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Willow$q$, $q$salgueiro$q$, $q$A willow bends gracefully over the pond.$q$, $q$Um salgueiro se curva graciosamente sobre a lagoa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Oak$q$, $q$carvalho$q$, $q$A giant oak shades the entire backyard.$q$, $q$Um carvalho gigante dá sombra ao quintal inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pine$q$, $q$pinheiro$q$, $q$The smell of pine fills the forest in winter.$q$, $q$O cheiro de pinheiro preenche a floresta no inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thorn$q$, $q$espinho de planta$q$, $q$A thorn scratches her hand while picking roses.$q$, $q$Um espinho arranha a mão dela enquanto colhe rosas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sprout$q$, $q$broto novo$q$, $q$A tiny sprout breaks through the soil.$q$, $q$Um broto pequeno rompe a terra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Wheat$q$, $q$trigo$q$, $q$Farmers harvest wheat before the first frost.$q$, $q$Agricultores colhem trigo antes da primeira geada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Barley$q$, $q$cevada$q$, $q$The field of barley stretches beyond the hill.$q$, $q$O campo de cevada se estende além da colina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Accountant$q$, $q$contador$q$, $q$The accountant reviews the company's records every month.$q$, $q$O contador revisa os registros da empresa todo mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Banker$q$, $q$banqueiro$q$, $q$The banker approves the loan after checking the documents.$q$, $q$O banqueiro aprova o empréstimo depois de conferir os documentos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Psychologist$q$, $q$psicólogo$q$, $q$She sees a psychologist once a week.$q$, $q$Ela consulta um psicólogo uma vez por semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pharmacist$q$, $q$farmacêutico$q$, $q$The pharmacist explains how to take the medicine.$q$, $q$O farmacêutico explica como tomar o remédio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Translator$q$, $q$tradutor$q$, $q$The translator works on a novel from French to English.$q$, $q$O tradutor trabalha num romance do francês para o inglês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Interpreter$q$, $q$intérprete$q$, $q$An interpreter helps the two leaders communicate.$q$, $q$Um intérprete ajuda os dois líderes a se comunicarem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gardener$q$, $q$jardineiro$q$, $q$The gardener trims the hedges every spring.$q$, $q$O jardineiro apara as cercas vivas toda primavera.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Janitor$q$, $q$zelador$q$, $q$The janitor locks the building every night.$q$, $q$O zelador tranca o prédio toda noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cashier$q$, $q$caixa de loja$q$, $q$The cashier counts the money at the end of the shift.$q$, $q$O caixa conta o dinheiro no fim do turno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chef$q$, $q$chef de cozinha$q$, $q$The chef designs a new menu for the summer.$q$, $q$O chef de cozinha cria um cardápio novo para o verão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Welder$q$, $q$soldador$q$, $q$The welder joins the two steel beams together.$q$, $q$O soldador une as duas vigas de aço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Miner$q$, $q$mineiro$q$, $q$The miner descends deep into the tunnel.$q$, $q$O mineiro desce fundo no túnel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Laborer$q$, $q$operário braçal$q$, $q$The laborer carries heavy bags all morning.$q$, $q$O operário braçal carrega sacos pesados a manhã toda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Trucker$q$, $q$caminhoneiro$q$, $q$The trucker drives across the country every week.$q$, $q$O caminhoneiro dirige pelo país toda semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Technician$q$, $q$técnico$q$, $q$A technician repairs the printer in the office.$q$, $q$Um técnico conserta a impressora no escritório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Appraiser$q$, $q$avaliador de bens$q$, $q$The appraiser values the house before the sale.$q$, $q$O avaliador de bens avalia a casa antes da venda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Joiner$q$, $q$marceneiro$q$, $q$The joiner builds a custom table for the client.$q$, $q$O marceneiro constrói uma mesa sob medida para o cliente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Painter$q$, $q$pintor de paredes$q$, $q$The painter finishes the living room in two days.$q$, $q$O pintor termina a sala em dois dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Glazier$q$, $q$vidraceiro$q$, $q$The glazier replaces the broken window pane.$q$, $q$O vidraceiro substitui o vidro quebrado da janela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Locksmith$q$, $q$chaveiro$q$, $q$The locksmith opens the door without a key.$q$, $q$O chaveiro abre a porta sem chave.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Marathon$q$, $q$maratona$q$, $q$She trains for months before running the marathon.$q$, $q$Ela treina por meses antes de correr a maratona.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fencing$q$, $q$esgrima$q$, $q$He takes up fencing as a new hobby.$q$, $q$Ele começa a praticar esgrima como um novo hobby.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rowing$q$, $q$remo esportivo$q$, $q$The team practices rowing early every morning.$q$, $q$O time pratica remo esportivo cedo toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Weightlifting$q$, $q$levantamento de peso$q$, $q$He focuses on weightlifting to build strength.$q$, $q$Ele foca em levantamento de peso para ganhar força.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Archery$q$, $q$tiro com arco$q$, $q$She takes archery lessons on Saturdays.$q$, $q$Ela faz aulas de tiro com arco aos sábados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Skating$q$, $q$patinação$q$, $q$The kids go skating at the new rink.$q$, $q$As crianças vão patinar na pista nova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Surfing$q$, $q$surfe$q$, $q$They spend the whole vacation surfing.$q$, $q$Eles passam as férias inteiras surfando.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gymnastics$q$, $q$ginástica$q$, $q$She competes in gymnastics at the national level.$q$, $q$Ela compete em ginástica em nível nacional.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dumbbell$q$, $q$halteres$q$, $q$He lifts a dumbbell in each hand.$q$, $q$Ele levanta um halter em cada mão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sprinter$q$, $q$corredor de velocidade$q$, $q$The sprinter breaks the record by a full second.$q$, $q$O corredor de velocidade quebra o recorde por um segundo inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nibble$q$, $q$mordiscar$q$, $q$I nibble on some crackers before dinner.$q$, $q$Eu mordisco alguns biscoitos antes do jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Slurp$q$, $q$sorver ruidosamente$q$, $q$I slurp my noodles a little too loudly.$q$, $q$Eu sorvo meu macarrão um pouco alto demais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gulp$q$, $q$engolir de uma vez$q$, $q$I gulp down my coffee before running out the door.$q$, $q$Eu engulo o café de uma vez antes de sair correndo pela porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Munch$q$, $q$mastigar ruidosamente$q$, $q$I munch on popcorn during the movie.$q$, $q$Eu mastigo pipoca ruidosamente durante o filme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Savor$q$, $q$degustar$q$, $q$I savor every bite of the homemade cake.$q$, $q$Eu degusto cada mordida do bolo caseiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Quench$q$, $q$matar a sede$q$, $q$I drink cold water to quench my thirst.$q$, $q$Eu bebo água gelada para matar a sede.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Drain$q$, $q$escorrer líquido$q$, $q$I drain the pasta before adding the sauce.$q$, $q$Eu escorro a massa antes de adicionar o molho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chill$q$, $q$esfriar$q$, $q$I chill the wine before the guests arrive.$q$, $q$Eu esfrio o vinho antes dos convidados chegarem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thaw$q$, $q$descongelar$q$, $q$I thaw the chicken overnight in the fridge.$q$, $q$Eu descongelo o frango durante a noite na geladeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Whip$q$, $q$bater claras$q$, $q$I whip the cream until it forms soft peaks.$q$, $q$Eu bato o creme de leite até formar picos macios.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Shrill$q$, $q$estridente$q$, $q$Her shrill voice carries across the entire room.$q$, $q$A voz estridente dela ecoa pela sala inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deafening$q$, $q$ensurdecedor$q$, $q$The concert music is absolutely deafening.$q$, $q$A música do show é absolutamente ensurdecedora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Velvety$q$, $q$aveludado$q$, $q$The wine has a smooth, velvety texture.$q$, $q$O vinho tem uma textura suave e aveludada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Acrid$q$, $q$acre$q$, $q$An acrid smell fills the air after the fire.$q$, $q$Um cheiro acre preenche o ar depois do incêndio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rancid$q$, $q$rançoso$q$, $q$The butter smells rancid after being left out.$q$, $q$A manteiga cheira rançosa depois de ficar fora da geladeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Moldy$q$, $q$mofado$q$, $q$I throw away the moldy bread immediately.$q$, $q$Eu jogo fora o pão mofado imediatamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Foul$q$, $q$fétido$q$, $q$A foul odor comes from the old fridge.$q$, $q$Um odor fétido vem da geladeira velha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Aromatic$q$, $q$aromático$q$, $q$The bakery fills the street with an aromatic smell.$q$, $q$A padaria enche a rua com um cheiro aromático.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Insipid$q$, $q$insípido$q$, $q$The soup tastes bland and insipid without salt.$q$, $q$A sopa fica sem graça e insípida sem sal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pungent$q$, $q$de cheiro forte$q$, $q$The cheese has a very pungent smell.$q$, $q$O queijo tem um cheiro muito forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Summon$q$, $q$intimar a comparecer$q$, $q$I summon the witness to testify in court.$q$, $q$Eu intimo a testemunha a depor no tribunal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Notify$q$, $q$notificar$q$, $q$I notify parents about the schedule change.$q$, $q$Eu notifico os pais sobre a mudança de horário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Convene$q$, $q$convocar reunião$q$, $q$I convene the committee to discuss the new policy.$q$, $q$Eu convoco o comitê para discutir a nova política.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Issue$q$, $q$emitir documento$q$, $q$I issue a new passport within two weeks.$q$, $q$Eu emito um novo passaporte em duas semanas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Certify$q$, $q$autenticar$q$, $q$I certify the financial report before submitting it.$q$, $q$Eu autentico o relatório financeiro antes de enviá-lo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cite$q$, $q$citar como referência$q$, $q$I cite an old case as precedent.$q$, $q$Eu cito um caso antigo como precedente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Authorize$q$, $q$autorizar$q$, $q$I authorize the extra spending for this project.$q$, $q$Eu autorizo o gasto extra para este projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Forbid$q$, $q$proibir$q$, $q$The rules forbid pets inside the building.$q$, $q$As regras proíbem animais de estimação dentro do prédio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Decree$q$, $q$determinar por decreto$q$, $q$The king moves to decree a national holiday to celebrate the victory.$q$, $q$O rei decide determinar por decreto um feriado nacional para celebrar a vitória.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Designate$q$, $q$designar$q$, $q$I designate a new leader for the project.$q$, $q$Eu designo um novo líder para o projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
