-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote1.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Meticulous$q$, $q$meticuloso$q$, $q$She keeps meticulous records of every transaction.$q$, $q$Ela mantém registros meticulosos de cada transação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ubiquitous$q$, $q$onipresente$q$, $q$Smartphones have become ubiquitous in modern life.$q$, $q$Smartphones se tornaram onipresentes na vida moderna.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ephemeral$q$, $q$efêmero$q$, $q$Fame in this industry is often ephemeral.$q$, $q$A fama nesta indústria costuma ser efêmera.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ingenious$q$, $q$engenhoso$q$, $q$Her ingenious solution saves the company time and money.$q$, $q$A solução engenhosa dela poupa tempo e dinheiro para a empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Astute$q$, $q$perspicaz$q$, $q$The astute investor spots the trend early.$q$, $q$O investidor perspicaz percebe a tendência cedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Persuasive$q$, $q$persuasivo$q$, $q$His persuasive argument convinces the entire board.$q$, $q$O argumento persuasivo dele convence o conselho inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subtle$q$, $q$sutil$q$, $q$There is a subtle difference between the two proposals.$q$, $q$Há uma diferença sutil entre as duas propostas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ambiguous$q$, $q$ambíguo$q$, $q$The instructions are too ambiguous to follow.$q$, $q$As instruções são ambíguas demais para seguir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pragmatic$q$, $q$pragmático$q$, $q$We need a pragmatic approach to solve this crisis.$q$, $q$Nós precisamos de uma abordagem pragmática para resolver esta crise.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reluctant$q$, $q$relutante$q$, $q$He is reluctant to change his original plan.$q$, $q$Ele está relutante em mudar o plano original dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Haughty$q$, $q$arrogante$q$, $q$Her haughty attitude alienates her colleagues.$q$, $q$A atitude arrogante dela afasta os colegas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hostile$q$, $q$hostil$q$, $q$The negotiations become increasingly hostile.$q$, $q$As negociações ficam cada vez mais hostis.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Relentless$q$, $q$implacável$q$, $q$The team faces relentless pressure to deliver results.$q$, $q$A equipe enfrenta pressão implacável para entregar resultados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vulnerable$q$, $q$vulnerável$q$, $q$The report exposes a vulnerable point in the system.$q$, $q$O relatório expõe um ponto vulnerável no sistema.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sarcastic$q$, $q$sarcástico$q$, $q$His sarcastic comment offends several people.$q$, $q$O comentário sarcástico dele ofende várias pessoas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Obstinate$q$, $q$obstinado$q$, $q$The obstinate committee refuses to reconsider the decision.$q$, $q$O comitê obstinado se recusa a reconsiderar a decisão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pretentious$q$, $q$pretensioso$q$, $q$Critics call the film pretentious and shallow.$q$, $q$Críticos chamam o filme de pretensioso e raso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cynical$q$, $q$cínico$q$, $q$She grows cynical after years in politics.$q$, $q$Ela se torna cínica depois de anos na política.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scornful$q$, $q$desdenhoso$q$, $q$His scornful tone undermines the whole discussion.$q$, $q$O tom desdenhoso dele prejudica a discussão inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gullible$q$, $q$crédulo$q$, $q$The scam only works on gullible investors.$q$, $q$O golpe só funciona com investidores crédulos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mitigate$q$, $q$mitigar$q$, $q$New regulations aim to mitigate the environmental damage.$q$, $q$Novas regulamentações visam mitigar o dano ambiental.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Exacerbate$q$, $q$exacerbar$q$, $q$This delay will only exacerbate the tension.$q$, $q$Este atraso só vai exacerbar a tensão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Elucidate$q$, $q$elucidar$q$, $q$I elucidate the theory with a clear example.$q$, $q$Eu elucido a teoria com um exemplo claro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Corroborate$q$, $q$corroborar$q$, $q$Two independent witnesses corroborate her account.$q$, $q$Duas testemunhas independentes corroboram o relato dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ratify$q$, $q$ratificar$q$, $q$Congress votes to ratify the international treaty.$q$, $q$O Congresso vota para ratificar o tratado internacional.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subjugate$q$, $q$subjugar$q$, $q$The empire attempts to subjugate the neighboring territories.$q$, $q$O império tenta subjugar os territórios vizinhos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dispel$q$, $q$dissipar$q$, $q$Her calm explanation helps dispel the rumors.$q$, $q$A explicação calma dela ajuda a dissipar os boatos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Extol$q$, $q$enaltecer$q$, $q$The critics extol the film's stunning cinematography.$q$, $q$Os críticos enaltecem a cinematografia impressionante do filme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rebuke$q$, $q$censurar$q$, $q$I rebuke the player for his careless mistake.$q$, $q$Eu censuro o jogador pelo erro descuidado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Suppress$q$, $q$reprimir$q$, $q$The government tries to suppress the growing protests.$q$, $q$O governo tenta reprimir os protestos crescentes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dispense$q$, $q$prescindir$q$, $q$We dispense with the usual paperwork in emergencies.$q$, $q$Nós prescindimos da papelada habitual em emergências.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Obtain$q$, $q$obter$q$, $q$I obtain permission to publish the confidential report.$q$, $q$Eu obtenho permissão para publicar o relatório confidencial.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Aspire$q$, $q$almejar$q$, $q$Many young engineers aspire to work at that company.$q$, $q$Muitos jovens engenheiros almejam trabalhar naquela empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Adhere$q$, $q$aderir$q$, $q$Employees must adhere to the new safety guidelines.$q$, $q$Os funcionários devem aderir às novas diretrizes de segurança.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Abdicate$q$, $q$abdicar$q$, $q$The king decides to abdicate the throne in favor of his son.$q$, $q$O rei decide abdicar do trono em favor do filho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Relegate$q$, $q$relegar$q$, $q$I relegate the task to a junior employee.$q$, $q$Eu relego a tarefa a um funcionário júnior.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Proliferate$q$, $q$proliferar$q$, $q$Misinformation continues to proliferate on social media.$q$, $q$A desinformação continua a proliferar nas redes sociais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Perpetuate$q$, $q$perpetuar$q$, $q$This policy will only perpetuate existing inequality.$q$, $q$Esta política só vai perpetuar a desigualdade já existente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Flaunt$q$, $q$ostentar$q$, $q$I never flaunt my success in front of others.$q$, $q$Eu nunca ostento meu sucesso na frente dos outros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Foster$q$, $q$fomentar$q$, $q$The program aims to foster creativity among students.$q$, $q$O programa visa fomentar a criatividade entre os alunos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Skepticism$q$, $q$ceticismo$q$, $q$Scientists greet the new claim with cautious skepticism.$q$, $q$Os cientistas recebem a nova alegação com ceticismo cauteloso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hypocrisy$q$, $q$hipocrisia$q$, $q$Voters resent the hypocrisy of the candidate's promises.$q$, $q$Os eleitores ressentem a hipocrisia das promessas do candidato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Integrity$q$, $q$integridade$q$, $q$She earns respect through her professional integrity.$q$, $q$Ela conquista respeito através da integridade profissional dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Privilege$q$, $q$privilégio$q$, $q$He acknowledges the privilege of his upbringing.$q$, $q$Ele reconhece o privilégio da criação dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prejudice$q$, $q$preconceito$q$, $q$The workshop addresses unconscious prejudice in hiring.$q$, $q$A oficina aborda o preconceito inconsciente nas contratações.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Yearning$q$, $q$anseio$q$, $q$A deep yearning for change drives the movement.$q$, $q$Um anseio profundo por mudança impulsiona o movimento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dissent$q$, $q$dissidência$q$, $q$The council allows open dissent during meetings.$q$, $q$O conselho permite divergência aberta durante as reuniões.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Expertise$q$, $q$perícia$q$, $q$Her expertise in tax law proves invaluable to the firm.$q$, $q$O conhecimento especializado dela em direito tributário se mostra inestimável para a firma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pitfall$q$, $q$armadilha oculta$q$, $q$The contract contains a hidden pitfall for new tenants.$q$, $q$O contrato contém uma armadilha oculta para novos inquilinos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Setback$q$, $q$percalço$q$, $q$The project suffers a major setback after the resignation.$q$, $q$O projeto sofre um grande percalço depois da renúncia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sovereignty$q$, $q$soberania$q$, $q$The nation fiercely defends its sovereignty.$q$, $q$A nação defende ferozmente sua soberania.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Legitimacy$q$, $q$legitimidade$q$, $q$Critics question the legitimacy of the election results.$q$, $q$Críticos questionam a legitimidade dos resultados da eleição.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bureaucracy$q$, $q$burocracia$q$, $q$Small businesses struggle with excessive bureaucracy.$q$, $q$Pequenas empresas enfrentam dificuldades com burocracia excessiva.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Diplomacy$q$, $q$diplomacia$q$, $q$The crisis is resolved through careful diplomacy.$q$, $q$A crise é resolvida por meio de diplomacia cuidadosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Hegemony$q$, $q$hegemonia$q$, $q$The book examines the hegemony of a single industry.$q$, $q$O livro examina a hegemonia de uma única indústria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Oligarchy$q$, $q$oligarquia$q$, $q$Analysts describe the country as a modern oligarchy.$q$, $q$Analistas descrevem o país como uma oligarquia moderna.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Referendum$q$, $q$plebiscito$q$, $q$The government schedules a referendum for next year.$q$, $q$O governo agenda um plebiscito para o próximo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bribery$q$, $q$suborno$q$, $q$The official faces charges of bribery and corruption.$q$, $q$O funcionário enfrenta acusações de suborno e corrupção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Census$q$, $q$censo$q$, $q$The national census takes place every ten years.$q$, $q$O censo nacional acontece a cada dez anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Amnesty$q$, $q$anistia$q$, $q$The government grants amnesty to political prisoners.$q$, $q$O governo concede anistia a presos políticos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Defendant$q$, $q$réu$q$, $q$The defendant pleads not guilty to the charges.$q$, $q$O réu se declara inocente das acusações.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prosecutor$q$, $q$promotor de justiça$q$, $q$The prosecutor presents new evidence in court.$q$, $q$O promotor de justiça apresenta novas provas no tribunal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Juror$q$, $q$jurado$q$, $q$Each juror must remain impartial throughout the trial.$q$, $q$Cada jurado deve permanecer imparcial durante todo o julgamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Testimony$q$, $q$depoimento$q$, $q$Her testimony proves crucial to the case.$q$, $q$O depoimento dela se mostra crucial para o caso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subpoena$q$, $q$intimação judicial$q$, $q$The court issues a subpoena for the missing documents.$q$, $q$O tribunal emite uma intimação judicial para os documentos ausentes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Compensation$q$, $q$indenização$q$, $q$The victims receive full compensation for their losses.$q$, $q$As vítimas recebem indenização integral pelas perdas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inheritance$q$, $q$herança$q$, $q$She uses her inheritance to start a business.$q$, $q$Ela usa a herança dela para abrir um negócio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Clause$q$, $q$cláusula$q$, $q$Read the clause carefully before signing the contract.$q$, $q$Leia a cláusula com atenção antes de assinar o contrato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Offense$q$, $q$infração$q$, $q$The company commits a serious offense under the new law.$q$, $q$A empresa comete uma infração grave sob a nova lei.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Litigation$q$, $q$litígio$q$, $q$The dispute leads to years of costly litigation.$q$, $q$A disputa leva a anos de litígio caro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Catalyst$q$, $q$catalisador$q$, $q$The scandal acts as a catalyst for reform.$q$, $q$O escândalo funciona como um catalisador para a reforma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Entropy$q$, $q$entropia$q$, $q$The system tends toward greater entropy over time.$q$, $q$O sistema tende a uma entropia maior com o tempo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mutation$q$, $q$mutação$q$, $q$A single mutation can change an entire species.$q$, $q$Uma única mutação pode mudar uma espécie inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ecosystem$q$, $q$ecossistema$q$, $q$Pollution disrupts the delicate ecosystem of the lake.$q$, $q$A poluição perturba o ecossistema delicado do lago.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Biodiversity$q$, $q$biodiversidade$q$, $q$The rainforest holds extraordinary biodiversity.$q$, $q$A floresta tropical abriga uma biodiversidade extraordinária.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Genome$q$, $q$genoma$q$, $q$Scientists map the entire human genome.$q$, $q$Cientistas mapeiam o genoma humano inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Symbiosis$q$, $q$simbiose$q$, $q$The two species live in perfect symbiosis.$q$, $q$As duas espécies vivem em perfeita simbiose.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Photon$q$, $q$fóton$q$, $q$A single photon can trigger the sensor.$q$, $q$Um único fóton pode acionar o sensor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Neutron$q$, $q$nêutron$q$, $q$A neutron has no electric charge.$q$, $q$Um nêutron não tem carga elétrica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Spectrum$q$, $q$espectro$q$, $q$The light splits into a visible spectrum of colors.$q$, $q$A luz se divide num espectro visível de cores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Monopoly$q$, $q$monopólio$q$, $q$The company holds a monopoly over the local market.$q$, $q$A empresa detém um monopólio sobre o mercado local.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Payout$q$, $q$lucro distribuído$q$, $q$Shareholders expect a generous payout this quarter.$q$, $q$Os acionistas esperam um lucro distribuído generoso neste trimestre.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mortgage$q$, $q$hipoteca$q$, $q$They finally pay off their mortgage after twenty years.$q$, $q$Eles finalmente quitam a hipoteca depois de vinte anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bankruptcy$q$, $q$falência$q$, $q$The airline files for bankruptcy after the crisis.$q$, $q$A companhia aérea declara falência depois da crise.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Subsidy$q$, $q$subsídio$q$, $q$The government offers a subsidy for renewable energy.$q$, $q$O governo oferece um subsídio para energia renovável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tariff$q$, $q$tarifa alfandegária$q$, $q$The new tariff raises the price of imported steel.$q$, $q$A nova tarifa alfandegária aumenta o preço do aço importado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Heir$q$, $q$herdeiro$q$, $q$She names her nephew as the sole heir.$q$, $q$Ela nomeia o sobrinho dela como único herdeiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Assets$q$, $q$patrimônio$q$, $q$The company sells its assets to pay off debt.$q$, $q$A empresa vende o patrimônio dela para quitar dívidas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Acquisition$q$, $q$aquisição$q$, $q$The acquisition doubles the company's market share.$q$, $q$A aquisição dobra a fatia de mercado da empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Merger$q$, $q$fusão de empresas$q$, $q$Shareholders approve the merger between the two firms.$q$, $q$Os acionistas aprovam a fusão entre as duas empresas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Refute$q$, $q$refutar$q$, $q$I refute the claim with new data.$q$, $q$Eu refuto a alegação com dados novos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Allude$q$, $q$aludir$q$, $q$I allude to a scandal without naming anyone.$q$, $q$Eu aludo a um escândalo sem nomear ninguém.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Postulate$q$, $q$postular$q$, $q$I postulate a link between diet and disease.$q$, $q$Eu postulo uma ligação entre dieta e doença.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Contend$q$, $q$arguir$q$, $q$Lawyers contend that the evidence is insufficient.$q$, $q$Os advogados sustentam que a prova é insuficiente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Speculate$q$, $q$especular$q$, $q$Analysts speculate about the company's next move.$q$, $q$Analistas especulam sobre a próxima ação da empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Emphasize$q$, $q$enfatizar$q$, $q$I emphasize the need for urgent action.$q$, $q$Eu enfatizo a necessidade de ação urgente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Illustrate$q$, $q$ilustrar$q$, $q$I illustrate my point with a simple chart.$q$, $q$Eu ilustro meu ponto com um gráfico simples.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Justify$q$, $q$justificar$q$, $q$He struggles to justify the sudden change in policy.$q$, $q$Ele tem dificuldade em justificar a mudança repentina na política.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dispute$q$, $q$contestar$q$, $q$I dispute the company's official numbers.$q$, $q$Eu contesto os números oficiais da empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Retract$q$, $q$retratar-se$q$, $q$I retract my false statement immediately.$q$, $q$Eu me retrato da minha declaração falsa imediatamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
