-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote6.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Robbery$q$, $q$roubo com ameaça$q$, $q$Police investigate the robbery at the bank.$q$, $q$A polícia investiga o roubo no banco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Theft$q$, $q$furto$q$, $q$The store reports a theft last night.$q$, $q$A loja relata um furto ontem à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Victim$q$, $q$vítima$q$, $q$The victim describes the man to the police.$q$, $q$A vítima descreve o homem para a polícia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Prison$q$, $q$prisão$q$, $q$He spends five years in prison.$q$, $q$Ele passa cinco anos na prisão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Investigation$q$, $q$investigação$q$, $q$The investigation lasts several months.$q$, $q$A investigação dura vários meses.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Accusation$q$, $q$acusação$q$, $q$She denies the accusation completely.$q$, $q$Ela nega a acusação completamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Criminal$q$, $q$criminoso$q$, $q$The criminal escapes through the back door.$q$, $q$O criminoso escapa pela porta dos fundos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Surveillance$q$, $q$vigilância$q$, $q$The mall uses surveillance cameras everywhere.$q$, $q$O shopping usa câmeras de vigilância em todo lugar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Danger$q$, $q$perigo$q$, $q$The sign warns of danger ahead.$q$, $q$A placa avisa sobre perigo à frente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Threat$q$, $q$ameaça$q$, $q$The company takes the threat seriously.$q$, $q$A empresa leva a ameaça a sério.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Overtime$q$, $q$horas extras$q$, $q$I work overtime to finish the project.$q$, $q$Eu trabalho horas extras para terminar o projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dismissal$q$, $q$demissão$q$, $q$His dismissal surprises everyone in the office.$q$, $q$A demissão dele surpreende todo mundo no escritório.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jobless$q$, $q$desempregado$q$, $q$He remains jobless for six months.$q$, $q$Ele fica desempregado por seis meses.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Target$q$, $q$meta a atingir$q$, $q$Our team meets the sales target this month.$q$, $q$Nossa equipe alcança a meta de vendas este mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Foreman$q$, $q$chefe de seção$q$, $q$The foreman checks the work every morning.$q$, $q$O chefe de seção confere o trabalho toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Badge$q$, $q$crachá$q$, $q$Every visitor wears a badge in the building.$q$, $q$Todo visitante usa um crachá no prédio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shift$q$, $q$turno de trabalho$q$, $q$I work the night shift this week.$q$, $q$Eu trabalho no turno da noite esta semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vacancy$q$, $q$vaga de emprego$q$, $q$The company announces a new vacancy today.$q$, $q$A empresa anuncia uma nova vaga de emprego hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Training$q$, $q$treinamento$q$, $q$New employees receive training in the first week.$q$, $q$Novos funcionários recebem treinamento na primeira semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Payroll$q$, $q$folha de pagamento$q$, $q$The payroll goes out on the last Friday of the month.$q$, $q$A folha de pagamento sai na última sexta do mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pumpkin$q$, $q$abóbora$q$, $q$She bakes a pumpkin pie for Thanksgiving.$q$, $q$Ela assa uma torta de abóbora para o Dia de Ação de Graças.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Eggplant$q$, $q$berinjela$q$, $q$He grills eggplant with olive oil.$q$, $q$Ele grelha berinjela com azeite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cucumber$q$, $q$pepino$q$, $q$I add cucumber to the salad.$q$, $q$Eu adiciono pepino na salada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spinach$q$, $q$espinafre$q$, $q$She cooks spinach with garlic.$q$, $q$Ela cozinha espinafre com alho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cauliflower$q$, $q$couve-flor$q$, $q$We roast cauliflower for dinner.$q$, $q$Nós assamos couve-flor para o jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Avocado$q$, $q$abacate$q$, $q$I spread avocado on my toast.$q$, $q$Eu passo abacate na minha torrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Almond$q$, $q$amêndoa$q$, $q$She snacks on an almond during the afternoon.$q$, $q$Ela belisca uma amêndoa durante a tarde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Peanut$q$, $q$amendoim$q$, $q$He is allergic to peanut butter.$q$, $q$Ele é alérgico a manteiga de amendoim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Chickpea$q$, $q$grão-de-bico$q$, $q$This soup has one chickpea in every spoon.$q$, $q$Esta sopa tem um grão-de-bico em cada colher.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Raspberry$q$, $q$framboesa$q$, $q$She adds a fresh raspberry to her yogurt.$q$, $q$Ela acrescenta uma framboesa fresca ao iogurte dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Broth$q$, $q$caldo$q$, $q$The chef prepares a chicken broth.$q$, $q$O chef prepara um caldo de galinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Muffin$q$, $q$bolinho doce$q$, $q$I buy a blueberry muffin for breakfast.$q$, $q$Eu compro um bolinho de mirtilo no café da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pudding$q$, $q$pudim$q$, $q$She makes chocolate pudding for dessert.$q$, $q$Ela faz pudim de chocolate de sobremesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Porridge$q$, $q$mingau$q$, $q$He eats porridge every winter morning.$q$, $q$Ele come mingau toda manhã de inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Oats$q$, $q$aveia$q$, $q$I mix oats with milk and fruit.$q$, $q$Eu misturo aveia com leite e fruta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mayonnaise$q$, $q$maionese$q$, $q$She spreads mayonnaise on the sandwich.$q$, $q$Ela passa maionese no sanduíche.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mustard$q$, $q$mostarda$q$, $q$He puts mustard on his hot dog.$q$, $q$Ele põe mostarda no cachorro-quente dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vinegar$q$, $q$vinagre$q$, $q$A little vinegar improves the salad dressing.$q$, $q$Um pouco de vinagre melhora o molho da salada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Yeast$q$, $q$fermento$q$, $q$The bread needs yeast to rise.$q$, $q$O pão precisa de fermento para crescer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tart$q$, $q$torta doce$q$, $q$She bakes a lemon tart for the party.$q$, $q$Ela assa uma torta de limão para a festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Liver$q$, $q$fígado$q$, $q$The doctor checks his liver function.$q$, $q$O médico verifica a função do fígado dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Kidney$q$, $q$rim$q$, $q$Drinking water helps the kidney work well.$q$, $q$Beber água ajuda o rim a funcionar bem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Intestine$q$, $q$intestino$q$, $q$The small intestine absorbs most nutrients.$q$, $q$O intestino delgado absorve a maioria dos nutrientes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Vein$q$, $q$veia$q$, $q$The nurse finds a vein quickly.$q$, $q$A enfermeira encontra uma veia rapidamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Artery$q$, $q$artéria$q$, $q$The artery carries blood from the heart.$q$, $q$A artéria carrega sangue do coração.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spine$q$, $q$coluna vertebral$q$, $q$Sitting badly can hurt your spine.$q$, $q$Sentar mal pode machucar a coluna vertebral.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Skull$q$, $q$crânio$q$, $q$The helmet protects the skull during a fall.$q$, $q$O capacete protege o crânio durante uma queda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rib$q$, $q$costela$q$, $q$He breaks a rib playing rugby.$q$, $q$Ele quebra uma costela jogando rugby.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hip$q$, $q$quadril$q$, $q$She has surgery on her hip.$q$, $q$Ela faz cirurgia no quadril dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Jaw$q$, $q$mandíbula$q$, $q$His jaw hurts after the dentist visit.$q$, $q$A mandíbula dele dói depois da visita ao dentista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hairbrush$q$, $q$escova de cabelo$q$, $q$She keeps a hairbrush in her bag.$q$, $q$Ela mantém uma escova de cabelo na bolsa dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dryer$q$, $q$secador de cabelo$q$, $q$I use a dryer after washing my hair.$q$, $q$Eu uso um secador depois de lavar o cabelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Razor$q$, $q$navalha$q$, $q$He shaves with a new razor.$q$, $q$Ele se barbeia com uma navalha nova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Deodorant$q$, $q$desodorante$q$, $q$She applies deodorant every morning.$q$, $q$Ela aplica desodorante toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tweezers$q$, $q$pinça$q$, $q$I use tweezers to remove the splinter.$q$, $q$Eu uso uma pinça para tirar a farpa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Makeup$q$, $q$maquiagem$q$, $q$She wears light makeup to work.$q$, $q$Ela usa maquiagem leve para o trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sunscreen$q$, $q$protetor solar$q$, $q$Apply sunscreen before going to the beach.$q$, $q$Passe protetor solar antes de ir à praia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Moisturizer$q$, $q$hidratante$q$, $q$He uses moisturizer after shaving.$q$, $q$Ele usa hidratante depois de se barbear.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Washcloth$q$, $q$toalhinha de rosto$q$, $q$She washes her face with a washcloth.$q$, $q$Ela lava o rosto com uma toalhinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lotion$q$, $q$loção$q$, $q$I put lotion on my dry hands.$q$, $q$Eu passo loção nas minhas mãos secas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Seatbelt$q$, $q$cinto de segurança$q$, $q$Please fasten your seatbelt before we start.$q$, $q$Por favor, afivele o cinto de segurança antes de partirmos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Toll$q$, $q$pedágio$q$, $q$We pay the toll before entering the highway.$q$, $q$Nós pagamos o pedágio antes de entrar na rodovia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Lane$q$, $q$faixa de rolagem$q$, $q$Stay in your lane on the highway.$q$, $q$Fique na sua faixa na rodovia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Brake$q$, $q$freio$q$, $q$She presses the brake at the red light.$q$, $q$Ela pisa no freio no semáforo vermelho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tire$q$, $q$pneu$q$, $q$He changes a flat tire on the road.$q$, $q$Ele troca um pneu furado na estrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Gear$q$, $q$marcha do carro$q$, $q$I shift into a lower gear on the hill.$q$, $q$Eu troco para uma marcha mais baixa na subida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tank$q$, $q$tanque de combustível$q$, $q$The tank is almost empty.$q$, $q$O tanque está quase vazio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$License$q$, $q$carteira de motorista$q$, $q$She gets her driver's license this month.$q$, $q$Ela tira a carteira de motorista dela este mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Accident$q$, $q$acidente de trânsito$q$, $q$The accident happens near the intersection.$q$, $q$O acidente acontece perto do cruzamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ferry$q$, $q$balsa$q$, $q$We take the ferry across the river.$q$, $q$Nós pegamos a balsa para atravessar o rio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Envy$q$, $q$inveja$q$, $q$He feels envy when his friend gets promoted.$q$, $q$Ele sente inveja quando o amigo dele é promovido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Grudge$q$, $q$rancor$q$, $q$She holds a grudge against her old boss.$q$, $q$Ela guarda rancor do antigo chefe dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Longing$q$, $q$saudade$q$, $q$A deep longing for home fills her heart.$q$, $q$Uma saudade profunda de casa preenche o coração dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Guilt$q$, $q$culpa$q$, $q$He feels guilt about the broken promise.$q$, $q$Ele sente culpa pela promessa quebrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sorrow$q$, $q$tristeza profunda$q$, $q$Sorrow fills the room after the news.$q$, $q$Tristeza profunda toma conta da sala depois da notícia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Delight$q$, $q$deleite$q$, $q$She smiles with delight at the surprise.$q$, $q$Ela sorri com deleite diante da surpresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dread$q$, $q$pavor$q$, $q$He feels dread before the exam results.$q$, $q$Ele sente pavor antes do resultado da prova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bliss$q$, $q$êxtase$q$, $q$They enjoy a moment of pure bliss.$q$, $q$Eles aproveitam um momento de puro êxtase.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Boredom$q$, $q$tédio$q$, $q$Boredom takes over during the long meeting.$q$, $q$O tédio toma conta durante a reunião longa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Enthusiasm$q$, $q$entusiasmo$q$, $q$She talks about the project with great enthusiasm.$q$, $q$Ela fala sobre o projeto com grande entusiasmo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tidy$q$, $q$arrumar$q$, $q$I tidy my room before guests arrive.$q$, $q$Eu arrumo meu quarto antes dos convidados chegarem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mop$q$, $q$passar esfregão$q$, $q$I mop the kitchen floor every Saturday.$q$, $q$Eu passo esfregão no chão da cozinha todo sábado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sew$q$, $q$costurar$q$, $q$My grandmother taught me how to sew.$q$, $q$Minha avó me ensinou a costurar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Knit$q$, $q$tricotar$q$, $q$She learns to knit a scarf this winter.$q$, $q$Ela aprende a tricotar um cachecol neste inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Embroider$q$, $q$bordar$q$, $q$I embroider flowers on the pillow.$q$, $q$Eu bordo flores no travesseiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Harvest$q$, $q$colher a plantação$q$, $q$Farmers harvest the corn in September.$q$, $q$Os agricultores colhem o milho em setembro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sow$q$, $q$semear$q$, $q$They sow seeds early in the spring.$q$, $q$Eles semeiam sementes no início da primavera.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Weave$q$, $q$tecer$q$, $q$I weave a basket from dry leaves.$q$, $q$Eu teço uma cesta com folhas secas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dye$q$, $q$tingir$q$, $q$I dye my old shirt a bright blue.$q$, $q$Eu tingo minha camisa velha de azul vivo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Polish$q$, $q$polir$q$, $q$I polish my shoes before the interview.$q$, $q$Eu lustro meus sapatos antes da entrevista.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Doubt$q$, $q$duvidar$q$, $q$I doubt the plan will work.$q$, $q$Eu duvido que o plano vá funcionar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Assume$q$, $q$supor$q$, $q$We assume the meeting starts at nine.$q$, $q$Nós supomos que a reunião começa às nove.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Conclude$q$, $q$concluir$q$, $q$I conclude the report with a strong recommendation.$q$, $q$Eu concluo o relatório com uma recomendação forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Deduce$q$, $q$deduzir$q$, $q$I deduce the answer from the clues.$q$, $q$Eu deduzo a resposta a partir das pistas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Analyze$q$, $q$analisar$q$, $q$We analyze the data before deciding.$q$, $q$Nós analisamos os dados antes de decidir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Assess$q$, $q$avaliar$q$, $q$I assess each student's progress.$q$, $q$Eu avalio o progresso de cada aluno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Meditate$q$, $q$meditar$q$, $q$I meditate for ten minutes every morning.$q$, $q$Eu medito por dez minutos toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Memorize$q$, $q$memorizar$q$, $q$I memorize the poem for class.$q$, $q$Eu memorizo o poema para a aula.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Focus$q$, $q$concentrar-se$q$, $q$I focus on one task at a time.$q$, $q$Eu me concentro em uma tarefa de cada vez.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wonder$q$, $q$indagar$q$, $q$I wonder why the flight is delayed.$q$, $q$Eu me indago por que o voo está atrasado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
