-- Frases-exemplo do Mental Lingo: lingo_exemplos_basico_lote9.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bath$q$, $q$banho$q$, $q$I take a bath every night.$q$, $q$Eu tomo banho toda noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nap$q$, $q$soneca$q$, $q$The baby takes a nap.$q$, $q$O bebê tira uma soneca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Chore$q$, $q$tarefa doméstica$q$, $q$Washing dishes is my chore.$q$, $q$Lavar louça é minha tarefa doméstica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Trash$q$, $q$lixo$q$, $q$I take out the trash.$q$, $q$Eu tiro o lixo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Laundry$q$, $q$roupa suja$q$, $q$I do the laundry on Sunday.$q$, $q$Eu lavo a roupa suja no domingo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Dishes$q$, $q$louça$q$, $q$I wash the dishes after dinner.$q$, $q$Eu lavo a louça depois do jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Vacation$q$, $q$férias$q$, $q$We go to the beach on vacation.$q$, $q$Nós vamos à praia nas férias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Habit$q$, $q$hábito$q$, $q$Reading is a good habit.$q$, $q$Ler é um bom hábito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Schedule$q$, $q$agenda$q$, $q$My schedule is very busy today.$q$, $q$Minha agenda está muito cheia hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Appointment$q$, $q$consulta marcada$q$, $q$I have an appointment at three.$q$, $q$Eu tenho uma consulta marcada às três.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Keyboard$q$, $q$teclado de computador$q$, $q$I type on the keyboard.$q$, $q$Eu digito no teclado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Battery$q$, $q$bateria$q$, $q$My phone battery is low.$q$, $q$A bateria do meu telefone está baixa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Charger$q$, $q$carregador$q$, $q$I forgot my charger at home.$q$, $q$Eu esqueci meu carregador em casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cable$q$, $q$cabo$q$, $q$The cable is too short.$q$, $q$O cabo é muito curto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$File$q$, $q$arquivo$q$, $q$I save the file on my computer.$q$, $q$Eu salvo o arquivo no meu computador.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Signal$q$, $q$sinal$q$, $q$There is no signal here.$q$, $q$Não há sinal aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Machine$q$, $q$máquina$q$, $q$This machine is very old.$q$, $q$Esta máquina é muito velha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Website$q$, $q$site$q$, $q$I visit this website every day.$q$, $q$Eu visito este site todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Printer$q$, $q$impressora$q$, $q$The printer is out of paper.$q$, $q$A impressora está sem papel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Speaker$q$, $q$caixa de som$q$, $q$I connect my phone to the speaker.$q$, $q$Eu conecto meu telefone à caixa de som.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hurry$q$, $q$apressar-se$q$, $q$I hurry to catch the bus.$q$, $q$Eu me apresso para pegar o ônibus.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Enjoy$q$, $q$aproveitar$q$, $q$I enjoy sunny days.$q$, $q$Eu aproveito os dias ensolarados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Accept$q$, $q$aceitar$q$, $q$I accept your apology.$q$, $q$Eu aceito suas desculpas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hate$q$, $q$odiar$q$, $q$I hate waking up early.$q$, $q$Eu odeio acordar cedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Miss$q$, $q$sentir falta$q$, $q$I miss my family.$q$, $q$Eu sinto falta da minha família.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Notice$q$, $q$notar$q$, $q$I notice a change in her.$q$, $q$Eu noto uma mudança nela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Happen$q$, $q$acontecer$q$, $q$Accidents happen sometimes.$q$, $q$Acidentes acontecem às vezes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Guess$q$, $q$adivinhar$q$, $q$I guess the answer.$q$, $q$Eu adivinho a resposta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wish$q$, $q$desejar$q$, $q$I wish you good luck.$q$, $q$Eu desejo boa sorte a você.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pretend$q$, $q$fingir$q$, $q$I pretend to be asleep.$q$, $q$Eu finjo estar dormindo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Catch$q$, $q$agarrar$q$, $q$I catch the ball.$q$, $q$Eu agarro a bola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Rescue$q$, $q$resgatar$q$, $q$Firefighters rescue the cat.$q$, $q$Os bombeiros resgatam o gato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Escape$q$, $q$escapar$q$, $q$The bird tries to escape.$q$, $q$O pássaro tenta escapar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Chase$q$, $q$perseguir$q$, $q$The dog and cat chase each other.$q$, $q$O cachorro e o gato se perseguem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fight$q$, $q$lutar$q$, $q$The brothers fight over the toy.$q$, $q$Os irmãos lutam pelo brinquedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Guide$q$, $q$guiar$q$, $q$I guide the tourists.$q$, $q$Eu guio os turistas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lead$q$, $q$liderar$q$, $q$I lead the team.$q$, $q$Eu lidero o time.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Trust$q$, $q$confiar$q$, $q$I trust my best friend.$q$, $q$Eu confio no meu melhor amigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Treat$q$, $q$tratar$q$, $q$I treat everyone with respect.$q$, $q$Eu trato todos com respeito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Search$q$, $q$procurar$q$, $q$I search for my keys.$q$, $q$Eu procuro minhas chaves.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Rare$q$, $q$raro$q$, $q$This bird is very rare.$q$, $q$Este pássaro é muito raro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Common$q$, $q$comum$q$, $q$This mistake is very common.$q$, $q$Este erro é muito comum.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ancient$q$, $q$antigo$q$, $q$The castle is very ancient.$q$, $q$O castelo é muito antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Current$q$, $q$atual$q$, $q$This is my current job.$q$, $q$Este é meu emprego atual.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fresh$q$, $q$fresco de comida$q$, $q$The bread is fresh.$q$, $q$O pão está fresco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Raw$q$, $q$cru$q$, $q$I don't like raw fish.$q$, $q$Eu não gosto de peixe cru.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Gentle$q$, $q$suave$q$, $q$She has a gentle voice.$q$, $q$Ela tem uma voz suave.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Generous$q$, $q$generoso$q$, $q$He is a generous man.$q$, $q$Ele é um homem generoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Smart$q$, $q$inteligente$q$, $q$She is a very smart girl.$q$, $q$Ela é uma menina muito inteligente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Silly$q$, $q$bobo$q$, $q$That is a silly question.$q$, $q$Essa é uma pergunta boba.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Some$q$, $q$algum$q$, $q$I want some water.$q$, $q$Eu quero um pouco de água.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Any$q$, $q$qualquer$q$, $q$Do you have any money?$q$, $q$Você tem algum dinheiro?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Many$q$, $q$muitos$q$, $q$She has many friends.$q$, $q$Ela tem muitos amigos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Much$q$, $q$muito em quantidade$q$, $q$I don't have much time.$q$, $q$Eu não tenho muito tempo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Few$q$, $q$poucos$q$, $q$I have few books here.$q$, $q$Eu tenho poucos livros aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Little$q$, $q$pouco$q$, $q$There is little sugar left.$q$, $q$Há pouco açúcar restante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$More$q$, $q$mais$q$, $q$I want more coffee.$q$, $q$Eu quero mais café.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Less$q$, $q$menos$q$, $q$Eat less sugar.$q$, $q$Coma menos açúcar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Most$q$, $q$a maioria$q$, $q$Most people like music.$q$, $q$A maioria das pessoas gosta de música.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Each$q$, $q$cada um$q$, $q$Each student has a book.$q$, $q$Cada aluno tem um livro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$This$q$, $q$este$q$, $q$This is my house.$q$, $q$Esta é minha casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$That$q$, $q$aquele$q$, $q$That is my car.$q$, $q$Aquele é meu carro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$These$q$, $q$estes$q$, $q$These shoes are new.$q$, $q$Estes sapatos são novos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Those$q$, $q$aqueles$q$, $q$Those flowers are beautiful.$q$, $q$Aquelas flores são bonitas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$He$q$, $q$ele$q$, $q$He is my brother.$q$, $q$Ele é meu irmão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$She$q$, $q$ela$q$, $q$She is my sister.$q$, $q$Ela é minha irmã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$We$q$, $q$nós$q$, $q$We are friends.$q$, $q$Nós somos amigos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$They$q$, $q$eles$q$, $q$They live in Brazil.$q$, $q$Eles moram no Brasil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$It$q$, $q$isso$q$, $q$It is a nice day.$q$, $q$Isso é um dia agradável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Our$q$, $q$nosso$q$, $q$Our house is small.$q$, $q$Nossa casa é pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$For$q$, $q$para alguém$q$, $q$This gift is for you.$q$, $q$Este presente é para você.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$From$q$, $q$vindo de$q$, $q$She is from Brazil.$q$, $q$Ela é do Brasil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Into$q$, $q$dentro de$q$, $q$The cat jumps into the box.$q$, $q$O gato pula dentro da caixa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Through$q$, $q$através de$q$, $q$We walk through the park.$q$, $q$Nós caminhamos através do parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Around$q$, $q$ao redor de$q$, $q$We walk around the lake.$q$, $q$Nós caminhamos ao redor do lago.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Until$q$, $q$até um momento$q$, $q$I wait until five o'clock.$q$, $q$Eu espero até as cinco horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$During$q$, $q$durante$q$, $q$She sleeps during the trip.$q$, $q$Ela dorme durante a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$After$q$, $q$depois de$q$, $q$We eat cake after dinner.$q$, $q$Nós comemos bolo depois do jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$If$q$, $q$se condicional$q$, $q$If it rains, we stay home.$q$, $q$Se chover, nós ficamos em casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$While$q$, $q$enquanto$q$, $q$I read while I wait.$q$, $q$Eu leio enquanto espero.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Soda$q$, $q$refrigerante$q$, $q$I drink soda at the party.$q$, $q$Eu bebo refrigerante na festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sauce$q$, $q$molho$q$, $q$She adds sauce to the pasta.$q$, $q$Ela adiciona molho na massa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Jam$q$, $q$geleia$q$, $q$I put jam on my toast.$q$, $q$Eu ponho geleia na minha torrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Toast$q$, $q$torrada$q$, $q$I eat toast for breakfast.$q$, $q$Eu como torrada no café da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sausage$q$, $q$salsicha$q$, $q$We grill sausage on Sunday.$q$, $q$Nós grelhamos salsicha no domingo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ham$q$, $q$presunto$q$, $q$I make a sandwich with ham.$q$, $q$Eu faço um sanduíche com presunto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shrimp$q$, $q$camarão$q$, $q$She cooks shrimp for dinner.$q$, $q$Ela cozinha camarão para o jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Steak$q$, $q$bife$q$, $q$He orders a steak.$q$, $q$Ele pede um bife.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pie$q$, $q$torta$q$, $q$We bake an apple pie.$q$, $q$Nós assamos uma torta de maçã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pancake$q$, $q$panqueca$q$, $q$I make pancake on Sunday.$q$, $q$Eu faço panqueca no domingo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Surprise$q$, $q$surpresa$q$, $q$This is a big surprise for me.$q$, $q$Esta é uma grande surpresa para mim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Joy$q$, $q$alegria$q$, $q$Her eyes are full of joy.$q$, $q$Os olhos dela estão cheios de alegria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pride$q$, $q$orgulho$q$, $q$He feels pride in his work.$q$, $q$Ele sente orgulho do trabalho dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shame$q$, $q$vergonha$q$, $q$She feels shame about the mistake.$q$, $q$Ela sente vergonha do erro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Luck$q$, $q$sorte$q$, $q$I wish you luck.$q$, $q$Eu te desejo sorte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fun$q$, $q$diversão$q$, $q$The party was a lot of fun.$q$, $q$A festa foi muito divertida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Courage$q$, $q$coragem$q$, $q$It takes courage to try again.$q$, $q$É preciso coragem para tentar de novo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Truth$q$, $q$verdade$q$, $q$Tell me the truth, please.$q$, $q$Me conte a verdade, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Secret$q$, $q$segredo$q$, $q$This is our little secret.$q$, $q$Este é o nosso pequeno segredo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Reason$q$, $q$razão$q$, $q$I have a good reason to stay.$q$, $q$Eu tenho uma boa razão para ficar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
