-- Frases-exemplo do Mental Lingo: lingo_exemplos_basico_lote4.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Beans$q$, $q$feijão$q$, $q$I eat beans and rice.$q$, $q$Eu como feijão e arroz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Butter$q$, $q$manteiga$q$, $q$She puts butter on the bread.$q$, $q$Ela põe manteiga no pão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Honey$q$, $q$mel$q$, $q$I like tea with honey.$q$, $q$Eu gosto de chá com mel.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pineapple$q$, $q$abacaxi$q$, $q$The pineapple is sweet.$q$, $q$O abacaxi é doce.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Carrot$q$, $q$cenoura$q$, $q$The rabbit eats a carrot.$q$, $q$O coelho come uma cenoura.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lettuce$q$, $q$alface$q$, $q$I put lettuce in the salad.$q$, $q$Eu ponho alface na salada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cookie$q$, $q$biscoito$q$, $q$The child eats a cookie.$q$, $q$A criança come um biscoito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Candy$q$, $q$bala$q$, $q$She gives candy to the kids.$q$, $q$Ela dá bala para as crianças.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Onion$q$, $q$cebola$q$, $q$He cuts the onion.$q$, $q$Ele corta a cebola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Garlic$q$, $q$alho$q$, $q$I add garlic to the soup.$q$, $q$Eu ponho alho na sopa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bottle$q$, $q$garrafa$q$, $q$I fill the bottle with water.$q$, $q$Eu encho a garrafa com água.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Plate$q$, $q$prato$q$, $q$She puts food on the plate.$q$, $q$Ela põe comida no prato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Spoon$q$, $q$colher$q$, $q$I eat soup with a spoon.$q$, $q$Eu como sopa com colher.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fork$q$, $q$garfo$q$, $q$Use a fork, please.$q$, $q$Use um garfo, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cup$q$, $q$xícara$q$, $q$I drink coffee from a cup.$q$, $q$Eu bebo café numa xícara.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Towel$q$, $q$toalha$q$, $q$Give me a towel, please.$q$, $q$Me dê uma toalha, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Soap$q$, $q$sabão$q$, $q$Wash your hands with soap.$q$, $q$Lave as mãos com sabão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Brush$q$, $q$escova$q$, $q$I clean my hair with a brush.$q$, $q$Eu limpo meu cabelo com uma escova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Umbrella$q$, $q$guarda-chuva$q$, $q$Take an umbrella, it will rain.$q$, $q$Leve um guarda-chuva, vai chover.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Candle$q$, $q$vela$q$, $q$She lights a candle.$q$, $q$Ela acende uma vela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Farm$q$, $q$fazenda$q$, $q$My grandfather has a farm.$q$, $q$Meu avô tem uma fazenda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Library$q$, $q$biblioteca$q$, $q$I study at the library.$q$, $q$Eu estudo na biblioteca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pharmacy$q$, $q$farmácia$q$, $q$I buy medicine at the pharmacy.$q$, $q$Eu compro remédio na farmácia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bakery$q$, $q$padaria$q$, $q$We buy bread at the bakery.$q$, $q$Nós compramos pão na padaria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Corner$q$, $q$esquina$q$, $q$The store is on the corner.$q$, $q$A loja fica na esquina.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Building$q$, $q$prédio$q$, $q$They work in a tall building.$q$, $q$Eles trabalham num prédio alto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Square$q$, $q$praça$q$, $q$People meet at the square.$q$, $q$As pessoas se encontram na praça.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Gate$q$, $q$portão$q$, $q$Close the gate, please.$q$, $q$Feche o portão, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tower$q$, $q$torre$q$, $q$The tower is very tall.$q$, $q$A torre é muito alta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Village$q$, $q$vila$q$, $q$They live in a small village.$q$, $q$Eles vivem numa vila pequena.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sister$q$, $q$irmã$q$, $q$My sister is a doctor.$q$, $q$Minha irmã é médica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Parents$q$, $q$pais$q$, $q$My parents live in São Paulo.$q$, $q$Meus pais moram em São Paulo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$King$q$, $q$rei$q$, $q$The king lives in a castle.$q$, $q$O rei mora num castelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Queen$q$, $q$rainha$q$, $q$The queen wears a crown.$q$, $q$A rainha usa uma coroa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Person$q$, $q$pessoa$q$, $q$She is a kind person.$q$, $q$Ela é uma pessoa gentil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$People$q$, $q$pessoas$q$, $q$Many people are here today.$q$, $q$Muitas pessoas estão aqui hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Guest$q$, $q$convidado$q$, $q$We have a guest for dinner.$q$, $q$Nós temos um convidado para o jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Stranger$q$, $q$estranho$q$, $q$Don't talk to a stranger.$q$, $q$Não fale com um estranho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Twin$q$, $q$gêmeo$q$, $q$My twin looks just like me.$q$, $q$Meu gêmeo se parece comigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Family$q$, $q$família$q$, $q$I love my family.$q$, $q$Eu amo minha família.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wash$q$, $q$lavar$q$, $q$I wash my hands before lunch.$q$, $q$Eu lavo as mãos antes do almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cut$q$, $q$cortar$q$, $q$Be careful, do not cut your finger.$q$, $q$Cuidado, não corte o dedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Break$q$, $q$quebrar$q$, $q$Do not break the glass.$q$, $q$Não quebre o copo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Carry$q$, $q$carregar$q$, $q$I carry the bag to school.$q$, $q$Eu carrego a bolsa para a escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Push$q$, $q$empurrar$q$, $q$Push the door to open it.$q$, $q$Empurre a porta para abrir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pull$q$, $q$puxar$q$, $q$Pull the chair closer.$q$, $q$Puxe a cadeira mais perto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Throw$q$, $q$arremessar$q$, $q$Throw the ball to me.$q$, $q$Jogue a bola para mim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Call$q$, $q$chamar$q$, $q$Call me tonight, please.$q$, $q$Me ligue hoje à noite, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ask$q$, $q$perguntar$q$, $q$Ask your teacher for help.$q$, $q$Peça ajuda ao seu professor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pay$q$, $q$pagar$q$, $q$I pay for the coffee.$q$, $q$Eu pago pelo café.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Answer$q$, $q$responder$q$, $q$Please answer my question.$q$, $q$Por favor, responda minha pergunta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Watch$q$, $q$assistir$q$, $q$We watch the sunset together.$q$, $q$Nós assistimos ao pôr do sol juntos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Listen$q$, $q$escutar$q$, $q$Listen to me, please.$q$, $q$Me escute, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Look$q$, $q$olhar$q$, $q$Look at the beautiful sky.$q$, $q$Olhe para o céu bonito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Find$q$, $q$encontrar$q$, $q$I can't find my keys.$q$, $q$Eu não consigo encontrar minhas chaves.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lose$q$, $q$perder$q$, $q$Don't lose your ticket.$q$, $q$Não perca seu bilhete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Win$q$, $q$ganhar$q$, $q$Our team will win the game.$q$, $q$Nosso time vai ganhar o jogo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Send$q$, $q$enviar$q$, $q$I send a message to my friend.$q$, $q$Eu envio uma mensagem para meu amigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Young$q$, $q$jovem$q$, $q$She is very young.$q$, $q$Ela é muito jovem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Kind$q$, $q$gentil$q$, $q$He is always kind to me.$q$, $q$Ele é sempre gentil comigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nice$q$, $q$legal$q$, $q$This is a nice house.$q$, $q$Esta é uma casa legal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Empty$q$, $q$vazio$q$, $q$The box is empty.$q$, $q$A caixa está vazia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wide$q$, $q$largo$q$, $q$The street is very wide.$q$, $q$A rua é muito larga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Deep$q$, $q$fundo$q$, $q$The river is very deep here.$q$, $q$O rio é muito fundo aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Safe$q$, $q$seguro$q$, $q$This place is safe for children.$q$, $q$Este lugar é seguro para crianças.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Free$q$, $q$livre$q$, $q$The tickets are free today.$q$, $q$Os bilhetes são grátis hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Dangerous$q$, $q$perigoso$q$, $q$It is dangerous to swim here.$q$, $q$É perigoso nadar aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Funny$q$, $q$engraçado$q$, $q$The movie is very funny.$q$, $q$O filme é muito engraçado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$In$q$, $q$em$q$, $q$The keys are in the bag.$q$, $q$As chaves estão na bolsa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$On$q$, $q$sobre$q$, $q$The book is on the table.$q$, $q$O livro está sobre a mesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Under$q$, $q$embaixo$q$, $q$The cat is under the bed.$q$, $q$O gato está embaixo da cama.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$With$q$, $q$com$q$, $q$I go to school with my sister.$q$, $q$Eu vou à escola com minha irmã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Without$q$, $q$sem$q$, $q$She left without saying goodbye.$q$, $q$Ela saiu sem se despedir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$But$q$, $q$mas$q$, $q$I want to go, but I am tired.$q$, $q$Eu quero ir, mas estou cansado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Or$q$, $q$ou$q$, $q$Do you want tea or coffee?$q$, $q$Você quer chá ou café?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Between$q$, $q$entre$q$, $q$The park is between two streets.$q$, $q$O parque fica entre duas ruas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Behind$q$, $q$atrás$q$, $q$The dog is behind the door.$q$, $q$O cachorro está atrás da porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Above$q$, $q$acima$q$, $q$The plane flies above the clouds.$q$, $q$O avião voa acima das nuvens.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Monday$q$, $q$segunda-feira$q$, $q$I start work on Monday.$q$, $q$Eu começo a trabalhar na segunda-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tuesday$q$, $q$terça-feira$q$, $q$We have class on Tuesday.$q$, $q$Nós temos aula na terça-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wednesday$q$, $q$quarta-feira$q$, $q$She visits us on Wednesday.$q$, $q$Ela nos visita na quarta-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thursday$q$, $q$quinta-feira$q$, $q$The meeting is on Thursday.$q$, $q$A reunião é na quinta-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Friday$q$, $q$sexta-feira$q$, $q$I love Friday nights.$q$, $q$Eu adoro as noites de sexta-feira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Saturday$q$, $q$sábado$q$, $q$We go to the market on Saturday.$q$, $q$Nós vamos ao mercado no sábado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sunday$q$, $q$domingo$q$, $q$We rest on Sunday.$q$, $q$Nós descansamos no domingo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Weekend$q$, $q$fim de semana$q$, $q$I visit my parents on the weekend.$q$, $q$Eu visito meus pais no fim de semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Birthday$q$, $q$aniversário$q$, $q$Today is my birthday.$q$, $q$Hoje é meu aniversário.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Holiday$q$, $q$feriado$q$, $q$Next Monday is a holiday.$q$, $q$A próxima segunda-feira é feriado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$January$q$, $q$janeiro$q$, $q$My birthday is in January.$q$, $q$Meu aniversário é em janeiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$February$q$, $q$fevereiro$q$, $q$It is very hot in February.$q$, $q$Faz muito calor em fevereiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$March$q$, $q$março$q$, $q$Classes start in March.$q$, $q$As aulas começam em março.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$April$q$, $q$abril$q$, $q$It often rains in April.$q$, $q$Chove com frequência em abril.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$May$q$, $q$maio$q$, $q$Flowers bloom in May.$q$, $q$As flores desabrocham em maio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$June$q$, $q$junho$q$, $q$We have a party in June.$q$, $q$Nós temos uma festa em junho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$July$q$, $q$julho$q$, $q$School vacation is in July.$q$, $q$As férias escolares são em julho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$August$q$, $q$agosto$q$, $q$It is very cold in August.$q$, $q$Faz muito frio em agosto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$September$q$, $q$setembro$q$, $q$Spring starts in September.$q$, $q$A primavera começa em setembro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$October$q$, $q$outubro$q$, $q$My father's birthday is in October.$q$, $q$O aniversário do meu pai é em outubro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$November$q$, $q$novembro$q$, $q$We plan a trip for November.$q$, $q$Nós planejamos uma viagem para novembro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$December$q$, $q$dezembro$q$, $q$Christmas is in December.$q$, $q$O Natal é em dezembro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
