-- Frases-exemplo do Mental Lingo: lingo_exemplos_basico_lote10.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Stomach$q$, $q$estômago$q$, $q$My stomach hurts a little.$q$, $q$Meu estômago dói um pouco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lung$q$, $q$pulmão$q$, $q$The lung helps us breathe.$q$, $q$O pulmão nos ajuda a respirar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Muscle$q$, $q$músculo$q$, $q$He has a strong muscle.$q$, $q$Ele tem um músculo forte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Throat$q$, $q$garganta$q$, $q$I have a sore throat.$q$, $q$Eu estou com a garganta doendo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Chin$q$, $q$queixo$q$, $q$She has a small chin.$q$, $q$Ela tem um queixo pequeno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cheek$q$, $q$bochecha$q$, $q$The baby has a round cheek.$q$, $q$O bebê tem uma bochecha redonda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Eyebrow$q$, $q$sobrancelha$q$, $q$He raises his eyebrow.$q$, $q$Ele levanta a sobrancelha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wrist$q$, $q$pulso$q$, $q$She hurts her wrist.$q$, $q$Ela machuca o pulso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ankle$q$, $q$tornozelo$q$, $q$I twist my ankle.$q$, $q$Eu torço o tornozelo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Toe$q$, $q$dedo do pé$q$, $q$He hurts his toe.$q$, $q$Ele machuca o dedo do pé.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Branch$q$, $q$galho$q$, $q$A bird sits on the branch.$q$, $q$Um pássaro pousa no galho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Root$q$, $q$raiz$q$, $q$The tree has a deep root.$q$, $q$A árvore tem uma raiz profunda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bush$q$, $q$arbusto$q$, $q$The cat hides in the bush.$q$, $q$O gato se esconde no arbusto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Petal$q$, $q$pétala$q$, $q$A petal falls from the flower.$q$, $q$Uma pétala cai da flor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cliff$q$, $q$penhasco$q$, $q$The house is near the cliff.$q$, $q$A casa fica perto do penhasco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pond$q$, $q$lagoa$q$, $q$Ducks swim in the pond.$q$, $q$Patos nadam na lagoa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Stream$q$, $q$riacho$q$, $q$We drink water from the stream.$q$, $q$Nós bebemos água do riacho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Log$q$, $q$tronco$q$, $q$We sit on a log.$q$, $q$Nós sentamos num tronco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bay$q$, $q$baía$q$, $q$The boats stay in the bay.$q$, $q$Os barcos ficam na baía.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Waterfall$q$, $q$cachoeira$q$, $q$We swim near the waterfall.$q$, $q$Nós nadamos perto da cachoeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sidewalk$q$, $q$calçada$q$, $q$We walk on the sidewalk.$q$, $q$Nós caminhamos na calçada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fountain$q$, $q$fonte de praça$q$, $q$Children play near the fountain.$q$, $q$As crianças brincam perto da fonte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Statue$q$, $q$estátua$q$, $q$There is a statue in the park.$q$, $q$Há uma estátua no parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Palace$q$, $q$palácio$q$, $q$The king lives in a palace.$q$, $q$O rei mora num palácio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Castle$q$, $q$castelo$q$, $q$We visit an old castle.$q$, $q$Nós visitamos um castelo antigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mail$q$, $q$correio$q$, $q$I check the mail every day.$q$, $q$Eu confiro o correio todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Crowd$q$, $q$multidão$q$, $q$There is a big crowd at the concert.$q$, $q$Há uma multidão grande no show.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Downtown$q$, $q$centro da cidade$q$, $q$We work downtown.$q$, $q$Nós trabalhamos no centro da cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Elevator$q$, $q$elevador$q$, $q$We take the elevator to the fifth floor.$q$, $q$Nós pegamos o elevador até o quinto andar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Court$q$, $q$tribunal$q$, $q$The judge works at the court.$q$, $q$O juiz trabalha no tribunal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shine$q$, $q$brilhar$q$, $q$The sun starts to shine.$q$, $q$O sol começa a brilhar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Blow$q$, $q$soprar$q$, $q$The wind starts to blow.$q$, $q$O vento começa a soprar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shake$q$, $q$sacudir$q$, $q$I shake the bottle before I open it.$q$, $q$Eu sacudo a garrafa antes de abrir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Roll$q$, $q$rolar$q$, $q$I roll the ball to my dog.$q$, $q$Eu rolo a bola para meu cachorro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pass$q$, $q$passar por$q$, $q$I pass by the school every day.$q$, $q$Eu passo pela escola todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Join$q$, $q$juntar-se$q$, $q$I join my friends at the park.$q$, $q$Eu me junto aos meus amigos no parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Touch$q$, $q$tocar com a mão$q$, $q$Please don't touch the paint.$q$, $q$Por favor, não toque na tinta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Taste$q$, $q$provar comida$q$, $q$I taste the soup before dinner.$q$, $q$Eu provo a sopa antes do jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Smell$q$, $q$cheirar$q$, $q$I smell fresh bread.$q$, $q$Eu cheiro pão fresco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Feel$q$, $q$sentir$q$, $q$I feel happy today.$q$, $q$Eu me sinto feliz hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bite$q$, $q$morder$q$, $q$The dog likes to bite the ball.$q$, $q$O cachorro gosta de morder a bola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Chew$q$, $q$mastigar$q$, $q$I chew my food slowly.$q$, $q$Eu mastigo minha comida devagar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Swallow$q$, $q$engolir$q$, $q$I swallow the pill with water.$q$, $q$Eu engulo o comprimido com água.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Yawn$q$, $q$bocejar$q$, $q$I yawn when I am tired.$q$, $q$Eu bocejo quando estou cansado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sneeze$q$, $q$espirrar$q$, $q$I sneeze because of the dust.$q$, $q$Eu espirro por causa da poeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sweep$q$, $q$varrer$q$, $q$I sweep the kitchen floor.$q$, $q$Eu varro o chão da cozinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tie$q$, $q$amarrar$q$, $q$I tie my shoes before running.$q$, $q$Eu amarro meus sapatos antes de correr.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hang$q$, $q$pendurar$q$, $q$I hang my coat on the door.$q$, $q$Eu penduro meu casaco na porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Dig$q$, $q$cavar$q$, $q$The dog likes to dig in the yard.$q$, $q$O cachorro gosta de cavar no quintal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wipe$q$, $q$enxugar$q$, $q$I wipe the table after lunch.$q$, $q$Eu enxugo a mesa depois do almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wild$q$, $q$selvagem$q$, $q$The wild animals live in the forest.$q$, $q$Os animais selvagens vivem na floresta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cute$q$, $q$fofo$q$, $q$The puppy is very cute.$q$, $q$O cachorrinho é muito fofo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Warm$q$, $q$morno$q$, $q$The water is warm.$q$, $q$A água está morna.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tiny$q$, $q$minúsculo$q$, $q$The kitten is very tiny.$q$, $q$O gatinho é muito minúsculo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Huge$q$, $q$enorme$q$, $q$The house is huge.$q$, $q$A casa é enorme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Giant$q$, $q$gigante$q$, $q$There is a giant tree in the park.$q$, $q$Há uma árvore gigante no parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Narrow$q$, $q$estreito$q$, $q$The street is very narrow.$q$, $q$A rua é muito estreita.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bored$q$, $q$entediado$q$, $q$I feel bored at home.$q$, $q$Eu me sinto entediado em casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Curious$q$, $q$curioso$q$, $q$The child is very curious.$q$, $q$A criança é muito curiosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Careful$q$, $q$cuidadoso$q$, $q$Please be careful on the stairs.$q$, $q$Por favor, seja cuidadoso na escada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Daily$q$, $q$diário$q$, $q$I read the news daily.$q$, $q$Eu leio as notícias diariamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Weekly$q$, $q$semanal$q$, $q$We have a weekly meeting.$q$, $q$Nós temos uma reunião semanal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Monthly$q$, $q$mensal$q$, $q$I pay my rent monthly.$q$, $q$Eu pago meu aluguel mensalmente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Century$q$, $q$século$q$, $q$This building is one century old.$q$, $q$Este prédio tem um século de idade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Age$q$, $q$idade$q$, $q$What is your age?$q$, $q$Qual é a sua idade?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Once$q$, $q$uma vez$q$, $q$I visit Paris once.$q$, $q$Eu visito Paris uma vez.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Twice$q$, $q$duas vezes$q$, $q$I go to the gym twice a week.$q$, $q$Eu vou à academia duas vezes por semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pair$q$, $q$par$q$, $q$I buy a pair of shoes.$q$, $q$Eu compro um par de sapatos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Couple$q$, $q$casal$q$, $q$A couple walks in the park.$q$, $q$Um casal caminha no parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Group$q$, $q$grupo$q$, $q$We study in a group.$q$, $q$Nós estudamos em grupo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hello$q$, $q$olá$q$, $q$Hello, how are you?$q$, $q$Olá, como você está?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hi$q$, $q$oi$q$, $q$Hi, nice to meet you.$q$, $q$Oi, prazer em conhecer você.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Goodbye$q$, $q$tchau$q$, $q$She says goodbye and leaves.$q$, $q$Ela diz tchau e vai embora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Welcome$q$, $q$bem-vindo$q$, $q$Welcome to my house.$q$, $q$Bem-vindo à minha casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sorry$q$, $q$desculpe$q$, $q$I am sorry for being late.$q$, $q$Eu peço desculpa por chegar atrasado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Okay$q$, $q$tudo bem ok$q$, $q$Is everything okay with you?$q$, $q$Está tudo bem com você?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fine$q$, $q$bem de saúde$q$, $q$I am fine, thank you.$q$, $q$Eu estou bem, obrigado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Well$q$, $q$bem$q$, $q$She sings very well.$q$, $q$Ela canta muito bem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pardon$q$, $q$perdão$q$, $q$Pardon me, what did you say?$q$, $q$Perdão, o que você disse?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sir$q$, $q$senhor$q$, $q$Excuse me, sir.$q$, $q$Com licença, senhor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Rule$q$, $q$regra$q$, $q$This is an important rule.$q$, $q$Esta é uma regra importante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Law$q$, $q$lei$q$, $q$Everyone must follow the law.$q$, $q$Todos devem seguir a lei.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Freedom$q$, $q$liberdade$q$, $q$Freedom is very important.$q$, $q$Liberdade é muito importante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$War$q$, $q$guerra$q$, $q$The war ends after many years.$q$, $q$A guerra termina depois de muitos anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Life$q$, $q$vida$q$, $q$I love my life.$q$, $q$Eu amo minha vida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fact$q$, $q$fato$q$, $q$This is an interesting fact.$q$, $q$Este é um fato interessante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Choice$q$, $q$escolha$q$, $q$You have a difficult choice.$q$, $q$Você tem uma escolha difícil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Risk$q$, $q$risco$q$, $q$This is a big risk.$q$, $q$Este é um grande risco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Success$q$, $q$sucesso$q$, $q$Her success makes us proud.$q$, $q$O sucesso dela nos deixa orgulhosos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mistake$q$, $q$erro$q$, $q$Everyone makes a mistake sometimes.$q$, $q$Todo mundo comete um erro às vezes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Toy$q$, $q$brinquedo$q$, $q$The child plays with a toy.$q$, $q$A criança brinca com um brinquedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Doll$q$, $q$boneca$q$, $q$She has a beautiful doll.$q$, $q$Ela tem uma boneca linda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Kite$q$, $q$pipa$q$, $q$The boy flies a kite.$q$, $q$O menino empina uma pipa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Balloon$q$, $q$balão de festa$q$, $q$The children play with a balloon.$q$, $q$As crianças brincam com um balão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Trophy$q$, $q$troféu$q$, $q$The team wins a trophy.$q$, $q$O time ganha um troféu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lock$q$, $q$fechadura$q$, $q$I put a lock on the door.$q$, $q$Eu ponho uma fechadura na porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mask$q$, $q$máscara$q$, $q$She wears a mask at the party.$q$, $q$Ela usa uma máscara na festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Flashlight$q$, $q$lanterna$q$, $q$I use a flashlight at night.$q$, $q$Eu uso uma lanterna à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Stamp$q$, $q$selo postal$q$, $q$I put a stamp on the letter.$q$, $q$Eu ponho um selo na carta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tent$q$, $q$barraca de camping$q$, $q$We sleep in a tent.$q$, $q$Nós dormimos numa barraca de camping.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
