-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote5.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Effervescent$q$, $q$efervescente$q$, $q$Her effervescent personality lights up every room.$q$, $q$A personalidade efervescente dela ilumina todo ambiente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Poignant$q$, $q$pungente$q$, $q$The film ends with a poignant scene about loss.$q$, $q$O filme termina com uma cena pungente sobre perda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Mellifluous$q$, $q$melífluo$q$, $q$His mellifluous voice makes the story more engaging.$q$, $q$A voz melíflua dele torna a história mais envolvente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Impetus$q$, $q$ímpeto$q$, $q$The award gives her the impetus to finish the novel.$q$, $q$O prêmio dá a ela o ímpeto para terminar o romance.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Selfless$q$, $q$abnegado$q$, $q$Her selfless act saves the whole family.$q$, $q$O ato abnegado dela salva a família inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lucid$q$, $q$lúcido$q$, $q$He remains lucid despite the high fever.$q$, $q$Ele permanece lúcido apesar da febre alta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Circumspect$q$, $q$circunspecto$q$, $q$She stays circumspect when discussing the merger.$q$, $q$Ela permanece circunspecta ao discutir a fusão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Masterful$q$, $q$magistral$q$, $q$The chef prepares a masterful three-course meal.$q$, $q$O chef prepara uma refeição magistral de três pratos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Unusual$q$, $q$insólito$q$, $q$The detective notices something unusual about the case.$q$, $q$O detetive percebe algo insólito sobre o caso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Candid$q$, $q$franco$q$, $q$She gives a candid answer about the company's struggles.$q$, $q$Ela dá uma resposta franca sobre as dificuldades da empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Courtesy$q$, $q$cortesia$q$, $q$He greets every guest with great courtesy.$q$, $q$Ele cumprimenta cada convidado com grande cortesia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Decorum$q$, $q$decoro$q$, $q$The judge expects strict decorum in the courtroom.$q$, $q$O juiz espera decoro rigoroso no tribunal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Modesty$q$, $q$recato$q$, $q$She speaks about her success with surprising modesty.$q$, $q$Ela fala sobre o sucesso dela com surpreendente recato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reverence$q$, $q$reverência$q$, $q$Visitors show reverence inside the old cathedral.$q$, $q$Os visitantes demonstram reverência dentro da catedral antiga.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pomp$q$, $q$pompa$q$, $q$The ceremony unfolds with great pomp and tradition.$q$, $q$A cerimônia se desenrola com muita pompa e tradição.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Solemnity$q$, $q$solenidade$q$, $q$The funeral proceeds with quiet solemnity.$q$, $q$O funeral prossegue com solenidade silenciosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Etiquette$q$, $q$etiqueta social$q$, $q$The book explains proper business etiquette.$q$, $q$O livro explica a etiqueta social apropriada nos negócios.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ceremonial$q$, $q$cerimonial$q$, $q$The mayor performs the ceremonial opening of the bridge.$q$, $q$O prefeito realiza a abertura cerimonial da ponte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Convention$q$, $q$convenção social$q$, $q$Wearing black to a funeral is a common convention.$q$, $q$Usar preto num funeral é uma convenção social comum.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Grace$q$, $q$elegância no trato$q$, $q$She accepts the criticism with remarkable grace.$q$, $q$Ela aceita a crítica com uma elegância notável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Avarice$q$, $q$avareza$q$, $q$His avarice eventually costs him his closest friends.$q$, $q$A avareza dele acaba lhe custando os amigos mais próximos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gluttony$q$, $q$gula$q$, $q$The holiday feast tempts even those who avoid gluttony.$q$, $q$O banquete de feriado tenta até quem evita a gula.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sloth$q$, $q$preguiça extrema$q$, $q$Sloth prevents him from finishing any of his projects.$q$, $q$A preguiça extrema o impede de terminar qualquer projeto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Arrogance$q$, $q$soberba$q$, $q$His arrogance alienates most of his coworkers.$q$, $q$A soberba dele afasta a maioria dos colegas de trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Temperance$q$, $q$temperança$q$, $q$She practices temperance when it comes to spending.$q$, $q$Ela pratica temperança quando se trata de gastos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prudence$q$, $q$prudência$q$, $q$Financial prudence helps them survive the crisis.$q$, $q$A prudência financeira ajuda eles a sobreviver à crise.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Diligence$q$, $q$diligência$q$, $q$Her diligence at work earns her a quick promotion.$q$, $q$A diligência dela no trabalho rende uma promoção rápida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thrift$q$, $q$frugalidade$q$, $q$Years of thrift allow them to buy their first house.$q$, $q$Anos de frugalidade permitem que eles comprem a primeira casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Loyalty$q$, $q$lealdade$q$, $q$The employees show great loyalty to the company.$q$, $q$Os funcionários demonstram grande lealdade à empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Clemency$q$, $q$clemência$q$, $q$The judge shows clemency due to his young age.$q$, $q$O juiz demonstra clemência por causa da idade jovem dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Anthropology$q$, $q$antropologia$q$, $q$She studies anthropology to understand ancient cultures.$q$, $q$Ela estuda antropologia para entender culturas antigas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sociology$q$, $q$sociologia$q$, $q$His research focuses on the sociology of small towns.$q$, $q$A pesquisa dele foca na sociologia de cidades pequenas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Demography$q$, $q$demografia$q$, $q$The shift in demography affects local schools.$q$, $q$A mudança na demografia afeta as escolas locais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ethnicity$q$, $q$etnia$q$, $q$The survey asks about age, income, and ethnicity.$q$, $q$A pesquisa pergunta sobre idade, renda e etnia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Migration$q$, $q$migração$q$, $q$Economic hardship drives the migration to the city.$q$, $q$A dificuldade econômica impulsiona a migração para a cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Urbanization$q$, $q$urbanização$q$, $q$Rapid urbanization changes the region's landscape.$q$, $q$A urbanização rápida muda a paisagem da região.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inequality$q$, $q$desigualdade$q$, $q$The report highlights growing income inequality.$q$, $q$O relatório destaca a desigualdade de renda crescente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Poverty$q$, $q$pobreza$q$, $q$The program aims to reduce poverty in rural areas.$q$, $q$O programa visa reduzir a pobreza em áreas rurais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Norm$q$, $q$norma social$q$, $q$Working from home becomes the new norm.$q$, $q$Trabalhar de casa se torna a nova norma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Blemish$q$, $q$mancha na reputação$q$, $q$The scandal leaves a lasting blemish on his career.$q$, $q$O escândalo deixa uma mancha duradoura na carreira dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Syllogism$q$, $q$silogismo$q$, $q$The professor explains the classic syllogism in class.$q$, $q$O professor explica o silogismo clássico na aula.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fallacy$q$, $q$falácia$q$, $q$His argument contains a common logical fallacy.$q$, $q$O argumento dele contém uma falácia lógica comum.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Deduction$q$, $q$dedução$q$, $q$She reaches her conclusion through careful deduction.$q$, $q$Ela chega à conclusão dela através de uma dedução cuidadosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Induction$q$, $q$indução$q$, $q$The theory develops through years of induction from data.$q$, $q$A teoria se desenvolve através de anos de indução a partir de dados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dialectic$q$, $q$dialética$q$, $q$Their debate follows a classic dialectic structure.$q$, $q$O debate deles segue uma estrutura dialética clássica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Empiricism$q$, $q$empirismo$q$, $q$The scientist follows strict empiricism in her research.$q$, $q$A cientista segue um empirismo rigoroso na pesquisa dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ontology$q$, $q$ontologia$q$, $q$The course introduces basic questions of ontology.$q$, $q$O curso apresenta questões básicas de ontologia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Epistemology$q$, $q$epistemologia$q$, $q$The lecture explores epistemology and the limits of knowledge.$q$, $q$A palestra explora a epistemologia e os limites do conhecimento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Utilitarianism$q$, $q$utilitarismo$q$, $q$The professor compares utilitarianism with other ethical theories.$q$, $q$O professor compara o utilitarismo com outras teorias éticas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Nihilism$q$, $q$niilismo$q$, $q$The novel explores a character's descent into nihilism.$q$, $q$O romance explora a queda de um personagem no niilismo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dialect$q$, $q$dialeto$q$, $q$She speaks a dialect specific to her home region.$q$, $q$Ela fala um dialeto específico da região dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Accent$q$, $q$sotaque$q$, $q$His accent reveals that he grew up abroad.$q$, $q$O sotaque dele revela que ele cresceu no exterior.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Slang$q$, $q$gíria$q$, $q$Teenagers create new slang every year.$q$, $q$Adolescentes criam gírias novas todo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Jargon$q$, $q$jargão$q$, $q$The manual is full of technical jargon.$q$, $q$O manual está cheio de jargão técnico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Coinage$q$, $q$palavra recém-criada$q$, $q$'Selfie' started as an internet coinage.$q$, $q$'Selfie' começou como uma criação recente da internet.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Etymology$q$, $q$etimologia$q$, $q$The professor traces the etymology of the word.$q$, $q$O professor rastreia a etimologia da palavra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Semantics$q$, $q$semântica$q$, $q$They argue over semantics instead of the real issue.$q$, $q$Eles discutem sobre semântica em vez do problema real.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Syntax$q$, $q$sintaxe$q$, $q$The sentence breaks the basic rules of syntax.$q$, $q$A frase quebra as regras básicas de sintaxe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Affix$q$, $q$afixo$q$, $q$An affix changes the meaning of the root word.$q$, $q$Um afixo muda o sentido da palavra raiz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Suffix$q$, $q$sufixo$q$, $q$Adding a suffix turns the verb into a noun.$q$, $q$Adicionar um sufixo transforma o verbo em substantivo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Equation$q$, $q$equação$q$, $q$She solves the equation on the whiteboard.$q$, $q$Ela resolve a equação no quadro branco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Variable$q$, $q$variável$q$, $q$The experiment changes only one variable at a time.$q$, $q$O experimento muda só uma variável de cada vez.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Coefficient$q$, $q$coeficiente$q$, $q$The coefficient determines the strength of the effect.$q$, $q$O coeficiente determina a força do efeito.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Probability$q$, $q$probabilidade$q$, $q$The probability of rain increases this weekend.$q$, $q$A probabilidade de chuva aumenta neste fim de semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Theorem$q$, $q$teorema$q$, $q$Students prove the theorem step by step.$q$, $q$Os alunos provam o teorema passo a passo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Geometry$q$, $q$geometria$q$, $q$She studies geometry to design the new building.$q$, $q$Ela estuda geometria para projetar o prédio novo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Calculus$q$, $q$cálculo diferencial$q$, $q$He struggles with calculus during his first semester.$q$, $q$Ele tem dificuldade com cálculo diferencial no primeiro semestre dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Logarithm$q$, $q$logaritmo$q$, $q$The formula uses a logarithm to simplify the calculation.$q$, $q$A fórmula usa um logaritmo para simplificar o cálculo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Matrix$q$, $q$matriz$q$, $q$The program stores the data in a large matrix.$q$, $q$O programa armazena os dados numa matriz grande.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vector$q$, $q$vetor$q$, $q$Each vector represents direction and speed.$q$, $q$Cada vetor representa direção e velocidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Substance$q$, $q$substância pura$q$, $q$The lab identifies the pure substance quickly.$q$, $q$O laboratório identifica a substância pura rapidamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Molecule$q$, $q$molécula$q$, $q$A single water molecule contains two hydrogen atoms.$q$, $q$Uma única molécula de água contém dois átomos de hidrogênio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reaction$q$, $q$reação química$q$, $q$The chemical reaction releases a lot of heat.$q$, $q$A reação química libera muito calor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Acid$q$, $q$ácido$q$, $q$The acid dissolves the metal within minutes.$q$, $q$O ácido dissolve o metal em poucos minutos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Alkaline$q$, $q$alcalino$q$, $q$Soap usually has an alkaline pH level.$q$, $q$Sabão geralmente tem um nível de pH alcalino.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Corrosion$q$, $q$corrosão$q$, $q$Rust is a common form of metal corrosion.$q$, $q$Ferrugem é uma forma comum de corrosão de metal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Thinner$q$, $q$diluente$q$, $q$She mixes the paint with a bit of thinner.$q$, $q$Ela mistura a tinta com um pouco de diluente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Polymer$q$, $q$polímero$q$, $q$This bottle is made from a strong polymer.$q$, $q$Esta garrafa é feita de um polímero resistente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Alloy$q$, $q$liga metálica$q$, $q$Bronze is an alloy of copper and tin.$q$, $q$Bronze é uma liga de cobre e estanho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Crystal$q$, $q$cristal$q$, $q$A single crystal forms slowly inside the cave.$q$, $q$Um único cristal se forma lentamente dentro da caverna.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Instinct$q$, $q$instinto$q$, $q$Her instinct tells her something is wrong.$q$, $q$O instinto dela diz que algo está errado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Camouflage$q$, $q$camuflagem$q$, $q$The lizard uses camouflage to hide from predators.$q$, $q$O lagarto usa camuflagem para se esconder de predadores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Invasive$q$, $q$espécie invasora$q$, $q$The invasive species threatens the local fish population.$q$, $q$A espécie invasora ameaça a população local de peixes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Adaptation$q$, $q$adaptação$q$, $q$This adaptation helps the bird survive in the cold.$q$, $q$Esta adaptação ajuda o pássaro a sobreviver no frio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Selection$q$, $q$seleção natural$q$, $q$Natural selection favors the strongest traits.$q$, $q$A seleção natural favorece as características mais fortes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Commensalism$q$, $q$comensalismo$q$, $q$Commensalism benefits one species without harming the other.$q$, $q$O comensalismo beneficia uma espécie sem prejudicar a outra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Parasite$q$, $q$parasita$q$, $q$The parasite lives inside its host for years.$q$, $q$O parasita vive dentro do hospedeiro dele por anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Offspring$q$, $q$prole$q$, $q$The bird protects its offspring from the storm.$q$, $q$O pássaro protege a prole dele da tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Fossil$q$, $q$fóssil$q$, $q$Scientists discover a rare fossil in the desert.$q$, $q$Cientistas descobrem um fóssil raro no deserto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Extinct$q$, $q$extinto$q$, $q$This species has been extinct for centuries.$q$, $q$Esta espécie está extinta há séculos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Devise$q$, $q$idealizar$q$, $q$Engineers devise a new method to save energy.$q$, $q$Engenheiros idealizam um novo método para economizar energia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Conceive$q$, $q$conceber uma ideia$q$, $q$I conceive the idea during a long walk.$q$, $q$Eu concebo a ideia durante uma caminhada longa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Carve$q$, $q$esculpir$q$, $q$I carve a small figure out of wood.$q$, $q$Eu esculpo uma figura pequena em madeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Forge$q$, $q$forjar$q$, $q$I forge a simple tool from raw metal.$q$, $q$Eu forjo uma ferramenta simples a partir de metal bruto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Assemble$q$, $q$montar peças$q$, $q$Workers assemble the parts on the factory line.$q$, $q$Trabalhadores montam as peças na linha da fábrica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dismantle$q$, $q$desmontar$q$, $q$They dismantle the old machine for parts.$q$, $q$Eles desmontam a máquina velha para aproveitar peças.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Refine$q$, $q$aprimorar$q$, $q$The team continues to refine the design each month.$q$, $q$A equipe continua a aprimorar o design a cada mês.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Manufacture$q$, $q$fabricar$q$, $q$The factory begins to manufacture electric cars.$q$, $q$A fábrica começa a fabricar carros elétricos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Calibrate$q$, $q$calibrar$q$, $q$Technicians calibrate the machine before every use.$q$, $q$Técnicos calibram a máquina antes de cada uso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Optimize$q$, $q$otimizar$q$, $q$Engineers optimize the engine for better fuel efficiency.$q$, $q$Engenheiros otimizam o motor para melhor eficiência de combustível.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
