-- Frases-exemplo do Mental Lingo: lingo_exemplos_avancado_lote2.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Melancholy$q$, $q$melancolia$q$, $q$A quiet melancholy settles over the empty house.$q$, $q$Uma melancolia silenciosa toma conta da casa vazia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Euphoria$q$, $q$euforia$q$, $q$A wave of euphoria sweeps through the crowd at the final goal.$q$, $q$Uma onda de euforia percorre a multidão no gol final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Apprehension$q$, $q$apreensão$q$, $q$She feels a growing apprehension before the surgery.$q$, $q$Ela sente uma apreensão crescente antes da cirurgia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Indignation$q$, $q$indignação$q$, $q$His indignation grows as the meeting drags on unfairly.$q$, $q$A indignação dele cresce à medida que a reunião se arrasta injustamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Anguish$q$, $q$angústia$q$, $q$The mother's anguish is visible on her face.$q$, $q$A angústia da mãe é visível no rosto dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Desolation$q$, $q$desolação$q$, $q$A sense of desolation fills the abandoned town.$q$, $q$Uma sensação de desolação preenche a cidade abandonada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Serenity$q$, $q$serenidade$q$, $q$I find serenity walking along the empty beach.$q$, $q$Eu encontro serenidade caminhando pela praia vazia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dismay$q$, $q$consternação$q$, $q$I watch the news with growing dismay.$q$, $q$Eu assisto às notícias com consternação crescente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Elation$q$, $q$exaltação$q$, $q$I feel pure elation when I hear the good news.$q$, $q$Eu sinto puro júbilo ao ouvir a boa notícia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bewilderment$q$, $q$perplexidade$q$, $q$I stare at the strange instructions in complete bewilderment.$q$, $q$Eu encaro as instruções estranhas em total perplexidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Magnanimous$q$, $q$magnânimo$q$, $q$The winner is magnanimous in victory.$q$, $q$O vencedor é magnânimo na vitória.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Altruistic$q$, $q$altruísta$q$, $q$Her altruistic nature leads her to volunteer every weekend.$q$, $q$A natureza altruísta dela a leva a fazer trabalho voluntário todo fim de semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Overbearing$q$, $q$prepotente$q$, $q$His overbearing manner intimidates the new employees.$q$, $q$O jeito prepotente dele intimida os novos funcionários.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Industrious$q$, $q$aplicado$q$, $q$The industrious student finishes every assignment early.$q$, $q$O aluno aplicado termina toda tarefa cedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Outgoing$q$, $q$extrovertido$q$, $q$Her outgoing personality makes her popular at parties.$q$, $q$A personalidade extrovertida dela a torna popular nas festas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reserved$q$, $q$introvertido$q$, $q$He remains reserved even among close friends.$q$, $q$Ele permanece discreto mesmo entre amigos próximos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Impulsive$q$, $q$impulsivo$q$, $q$His impulsive decisions often cost him money.$q$, $q$As decisões impulsivas dele frequentemente custam dinheiro a ele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Tenacious$q$, $q$tenaz$q$, $q$Her tenacious spirit helps her overcome every obstacle.$q$, $q$O espírito tenaz dela a ajuda a superar cada obstáculo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reticent$q$, $q$calado$q$, $q$He stays reticent about his personal life.$q$, $q$Ele permanece calado sobre a vida pessoal dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cunning$q$, $q$astuto$q$, $q$The cunning fox tricks the farmer twice.$q$, $q$A raposa astuta engana o fazendeiro duas vezes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lurk$q$, $q$espreitar$q$, $q$I lurk near the door, waiting for the right moment.$q$, $q$Eu espreito perto da porta, esperando o momento certo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sneak$q$, $q$esgueirar-se$q$, $q$I sneak out of the meeting during the break.$q$, $q$Eu me esgueiro para fora da reunião durante o intervalo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Cling$q$, $q$agarrar-se$q$, $q$I cling to the railing as the boat rocks.$q$, $q$Eu me agarro ao corrimão enquanto o barco balança.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rummage$q$, $q$vasculhar$q$, $q$I rummage through the drawer looking for my keys.$q$, $q$Eu vasculho a gaveta procurando minhas chaves.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Trudge$q$, $q$caminhar com esforço$q$, $q$I trudge through the snow toward the station.$q$, $q$Eu caminho com esforço pela neve em direção à estação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Jolt$q$, $q$sacudir bruscamente$q$, $q$I jolt awake at the sound of the alarm.$q$, $q$Eu acordo com um sacudir brusco ao som do alarme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Brandish$q$, $q$brandir$q$, $q$I brandish the umbrella like a sword in the storm.$q$, $q$Eu brando o guarda-chuva como uma espada na tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Seize$q$, $q$arrebatar$q$, $q$I seize the opportunity before anyone else notices it.$q$, $q$Eu arrebato a oportunidade antes que qualquer outro perceba.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lunge$q$, $q$investir contra$q$, $q$I lunge forward to catch the falling glass.$q$, $q$Eu investo para frente para pegar o copo que cai.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dodge$q$, $q$esquivar-se$q$, $q$I dodge the question and change the subject.$q$, $q$Eu me esquivo da pergunta e mudo de assunto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Desolate$q$, $q$desolado$q$, $q$The desolate landscape stretches for miles.$q$, $q$A paisagem desolada se estende por quilômetros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Picturesque$q$, $q$pitoresco$q$, $q$The picturesque village attracts tourists all year.$q$, $q$A vila pitoresca atrai turistas o ano todo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Gloomy$q$, $q$sombrio$q$, $q$The sky turns gloomy just before the storm.$q$, $q$O céu fica sombrio pouco antes da tempestade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Secluded$q$, $q$isolado$q$, $q$They find a secluded cabin deep in the woods.$q$, $q$Eles encontram uma cabana isolada no meio da floresta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lavish$q$, $q$suntuoso$q$, $q$The hotel offers a lavish breakfast every morning.$q$, $q$O hotel oferece um café da manhã suntuoso toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Dilapidated$q$, $q$decadente$q$, $q$The dilapidated building stands empty for years.$q$, $q$O prédio decadente fica vazio por anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Labyrinthine$q$, $q$labiríntico$q$, $q$The old city has labyrinthine streets that confuse visitors.$q$, $q$A cidade antiga tem ruas labirínticas que confundem os visitantes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Majestic$q$, $q$majestoso$q$, $q$The majestic mountains rise above the valley.$q$, $q$As montanhas majestosas se erguem acima do vale.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Barren$q$, $q$árido$q$, $q$Nothing grows on the barren hillside.$q$, $q$Nada cresce na encosta árida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Lush$q$, $q$exuberante$q$, $q$Lush vegetation covers the entire hillside.$q$, $q$Vegetação exuberante cobre a encosta inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sensationalist$q$, $q$sensacionalista$q$, $q$The sensationalist headline exaggerates the actual story.$q$, $q$A manchete sensacionalista exagera a história real.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Impartial$q$, $q$imparcial$q$, $q$The judge remains impartial throughout the case.$q$, $q$O juiz permanece imparcial durante todo o caso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Slander$q$, $q$difamação$q$, $q$The company sues the reporter for slander.$q$, $q$A empresa processa o repórter por difamação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Rhetoric$q$, $q$retórica$q$, $q$His speech relies heavily on empty rhetoric.$q$, $q$O discurso dele se apoia muito em retórica vazia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Manipulation$q$, $q$manipulação$q$, $q$The email is a clear attempt at manipulation.$q$, $q$O e-mail é uma tentativa clara de manipulação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Disseminate$q$, $q$disseminar$q$, $q$The agency works to disseminate accurate information quickly.$q$, $q$A agência trabalha para disseminar informação precisa rapidamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Plagiarism$q$, $q$plágio$q$, $q$The university expels the student for plagiarism.$q$, $q$A universidade expulsa o aluno por plágio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chronicle$q$, $q$crônica histórica$q$, $q$The chronicle describes the events of that turbulent year.$q$, $q$A crônica descreve os eventos daquele ano turbulento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Essay$q$, $q$ensaio$q$, $q$I write an essay about climate change for class.$q$, $q$Eu escrevo um ensaio sobre mudança climática para a aula.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Pamphlet$q$, $q$panfleto$q$, $q$Volunteers hand out a pamphlet at the entrance.$q$, $q$Voluntários distribuem um panfleto na entrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Diagnosis$q$, $q$diagnóstico$q$, $q$The doctor confirms the diagnosis after several tests.$q$, $q$O médico confirma o diagnóstico depois de vários exames.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prognosis$q$, $q$prognóstico$q$, $q$The prognosis improves after the new treatment.$q$, $q$O prognóstico melhora depois do novo tratamento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Chronic$q$, $q$crônico$q$, $q$She suffers from a chronic back condition.$q$, $q$Ela sofre de uma condição crônica nas costas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Infection$q$, $q$infecção$q$, $q$The wound develops a serious infection.$q$, $q$O ferimento desenvolve uma infecção séria.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Immunity$q$, $q$imunidade$q$, $q$The vaccine builds immunity against the virus.$q$, $q$A vacina cria imunidade contra o vírus.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inflammation$q$, $q$inflamação$q$, $q$The medicine reduces the inflammation quickly.$q$, $q$O remédio reduz a inflamação rapidamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sedative$q$, $q$sedativo$q$, $q$The doctor prescribes a mild sedative before the procedure.$q$, $q$O médico prescreve um sedativo leve antes do procedimento.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Therapy$q$, $q$terapia$q$, $q$She attends therapy once a week.$q$, $q$Ela vai à terapia uma vez por semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Anesthesia$q$, $q$anestesia$q$, $q$The surgeon administers anesthesia before the operation.$q$, $q$O cirurgião administra anestesia antes da operação.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Epidemic$q$, $q$epidemia$q$, $q$Health officials declare an epidemic in the region.$q$, $q$Autoridades de saúde declaram uma epidemia na região.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Allegory$q$, $q$alegoria$q$, $q$The novel works as an allegory for modern society.$q$, $q$O romance funciona como uma alegoria da sociedade moderna.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Metaphor$q$, $q$metáfora$q$, $q$She uses a powerful metaphor to describe her grief.$q$, $q$Ela usa uma metáfora poderosa para descrever a dor dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Narrator$q$, $q$narrador$q$, $q$The narrator reveals the twist in the final chapter.$q$, $q$O narrador revela a reviravolta no capítulo final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Plot$q$, $q$enredo$q$, $q$The plot thickens after the unexpected betrayal.$q$, $q$O enredo se complica depois da traição inesperada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Character$q$, $q$personagem$q$, $q$The main character grows throughout the story.$q$, $q$O personagem principal amadurece ao longo da história.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Epilogue$q$, $q$epílogo$q$, $q$The epilogue reveals what happens years later.$q$, $q$O epílogo revela o que acontece anos depois.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Sonnet$q$, $q$soneto$q$, $q$She writes a sonnet for her grandmother's birthday.$q$, $q$Ela escreve um soneto para o aniversário da avó dela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prose$q$, $q$prosa$q$, $q$His prose feels dense but rewarding to read.$q$, $q$A prosa dele parece densa, mas gratificante de ler.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Stanza$q$, $q$estrofe$q$, $q$The final stanza changes the meaning of the whole poem.$q$, $q$A última estrofe muda o sentido do poema inteiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Novelist$q$, $q$romancista$q$, $q$The novelist publishes her third book this year.$q$, $q$A romancista publica o terceiro livro dela este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Algorithm$q$, $q$algoritmo$q$, $q$The algorithm sorts the data in seconds.$q$, $q$O algoritmo organiza os dados em segundos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Encryption$q$, $q$criptografia$q$, $q$The bank uses strong encryption to protect accounts.$q$, $q$O banco usa criptografia forte para proteger as contas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Bandwidth$q$, $q$largura de banda$q$, $q$The office needs more bandwidth for video calls.$q$, $q$O escritório precisa de mais largura de banda para chamadas de vídeo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Debug$q$, $q$depurar$q$, $q$I debug the program before the final release.$q$, $q$Eu depuro o programa antes do lançamento final.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Processor$q$, $q$processador$q$, $q$The new processor makes the laptop much faster.$q$, $q$O novo processador torna o laptop muito mais rápido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Latency$q$, $q$latência$q$, $q$High latency makes the game unplayable.$q$, $q$Alta latência torna o jogo impossível de jogar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Redundancy$q$, $q$redundância$q$, $q$The system relies on redundancy to avoid failures.$q$, $q$O sistema conta com redundância para evitar falhas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Authentication$q$, $q$autenticação$q$, $q$The app requires two-step authentication to log in.$q$, $q$O aplicativo exige autenticação em duas etapas para fazer login.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Vulnerability$q$, $q$vulnerabilidade$q$, $q$Engineers fix the vulnerability before it is exploited.$q$, $q$Os engenheiros corrigem a vulnerabilidade antes que ela seja explorada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Prototype$q$, $q$protótipo$q$, $q$The team tests a working prototype next week.$q$, $q$A equipe testa um protótipo funcional na próxima semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Alliance$q$, $q$aliança estratégica$q$, $q$The two companies form a strategic alliance.$q$, $q$As duas empresas formam uma aliança estratégica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Shareholder$q$, $q$acionista$q$, $q$Every shareholder votes on the new policy.$q$, $q$Todo acionista vota na nova política.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Revenue$q$, $q$faturamento$q$, $q$The company's revenue doubles in one year.$q$, $q$O faturamento da empresa dobra em um ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Outsourcing$q$, $q$terceirização$q$, $q$Outsourcing reduces the company's operating costs.$q$, $q$A terceirização reduz os custos operacionais da empresa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Franchise$q$, $q$franquia comercial$q$, $q$They open a franchise of the popular coffee shop.$q$, $q$Eles abrem uma franquia da cafeteria popular.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Scalability$q$, $q$escalabilidade$q$, $q$The startup focuses on scalability from day one.$q$, $q$A startup foca em escalabilidade desde o primeiro dia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Inspection$q$, $q$inspeção$q$, $q$The factory passes the safety inspection.$q$, $q$A fábrica passa na inspeção de segurança.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Default$q$, $q$inadimplência$q$, $q$The bank warns him about the risk of default.$q$, $q$O banco o avisa sobre o risco de inadimplência.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Liquidity$q$, $q$liquidez$q$, $q$The company maintains strong liquidity during the crisis.$q$, $q$A empresa mantém forte liquidez durante a crise.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Trademark$q$, $q$marca registrada$q$, $q$They register the logo as a trademark.$q$, $q$Eles registram o logotipo como marca registrada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Insinuate$q$, $q$insinuar$q$, $q$I never insinuate that he is lying.$q$, $q$Eu nunca insinuo que ele está mentindo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Proclaim$q$, $q$proclamar$q$, $q$I proclaim this day a holiday for the whole city.$q$, $q$Eu proclamo este dia um feriado para a cidade inteira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Caution$q$, $q$advertir$q$, $q$I caution him about the icy road ahead.$q$, $q$Eu advirto ele sobre a estrada com gelo à frente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Urge$q$, $q$exortar$q$, $q$I urge her to reconsider the decision.$q$, $q$Eu exorto ela a reconsiderar a decisão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Ridicule$q$, $q$ridicularizar$q$, $q$I refuse to ridicule his accent in front of others.$q$, $q$Eu me recuso a ridicularizar o sotaque dele na frente dos outros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Defame$q$, $q$caluniar$q$, $q$The article seems to defame the local politician.$q$, $q$O artigo parece caluniar o político local.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reiterate$q$, $q$reiterar$q$, $q$I reiterate my concerns about the timeline.$q$, $q$Eu reitero minhas preocupações sobre o cronograma.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Divulge$q$, $q$divulgar segredo$q$, $q$I refuse to divulge the details of the agreement.$q$, $q$Eu me recuso a divulgar os detalhes do acordo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Acclaim$q$, $q$aclamar$q$, $q$Critics acclaim the film as a masterpiece.$q$, $q$Críticos aclamam o filme como uma obra-prima.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$avancado$q$, $q$Reprimand$q$, $q$repreender$q$, $q$I reprimand him for the late report.$q$, $q$Eu repreendo ele pelo relatório atrasado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
