-- Frases-exemplo do Mental Lingo: lingo_exemplos_basico_lote8.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Soccer$q$, $q$futebol$q$, $q$We play soccer every weekend.$q$, $q$Nós jogamos futebol todo fim de semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Basketball$q$, $q$basquete$q$, $q$He loves to play basketball.$q$, $q$Ele adora jogar basquete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tennis$q$, $q$tênis$q$, $q$She plays tennis on Saturdays.$q$, $q$Ela joga tênis aos sábados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Race$q$, $q$corrida$q$, $q$The race starts at nine.$q$, $q$A corrida começa às nove.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Goal$q$, $q$gol$q$, $q$He scores a goal.$q$, $q$Ele marca um gol.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Score$q$, $q$placar$q$, $q$What is the score of the game?$q$, $q$Qual é o placar do jogo?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Coach$q$, $q$treinador$q$, $q$Our coach is very strict.$q$, $q$Nosso treinador é muito rígido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Player$q$, $q$jogador$q$, $q$He is the best player on the team.$q$, $q$Ele é o melhor jogador do time.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Champion$q$, $q$campeão$q$, $q$She is the champion this year.$q$, $q$Ela é a campeã este ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Prize$q$, $q$prêmio$q$, $q$He wins a big prize.$q$, $q$Ele ganha um prêmio grande.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Gold$q$, $q$ouro$q$, $q$The ring is made of gold.$q$, $q$O anel é feito de ouro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Silver$q$, $q$prata$q$, $q$She wears a silver necklace.$q$, $q$Ela usa um colar de prata.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wood$q$, $q$madeira$q$, $q$The table is made of wood.$q$, $q$A mesa é feita de madeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Iron$q$, $q$ferro$q$, $q$The gate is made of iron.$q$, $q$O portão é feito de ferro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Steel$q$, $q$aço$q$, $q$The bridge is made of steel.$q$, $q$A ponte é feita de aço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cotton$q$, $q$algodão$q$, $q$This shirt is made of cotton.$q$, $q$Esta camisa é feita de algodão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Leather$q$, $q$couro$q$, $q$He wears a leather jacket.$q$, $q$Ele usa uma jaqueta de couro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wool$q$, $q$lã$q$, $q$The sweater is made of wool.$q$, $q$O suéter é feito de lã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Silk$q$, $q$seda$q$, $q$The dress is made of silk.$q$, $q$O vestido é feito de seda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Plastic$q$, $q$plástico$q$, $q$The bottle is made of plastic.$q$, $q$A garrafa é feita de plástico.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$World$q$, $q$mundo$q$, $q$She wants to travel the world.$q$, $q$Ela quer viajar pelo mundo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Flag$q$, $q$bandeira$q$, $q$The flag is red and white.$q$, $q$A bandeira é vermelha e branca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$North$q$, $q$norte$q$, $q$We drive to the north.$q$, $q$Nós dirigimos para o norte.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$South$q$, $q$sul$q$, $q$They live in the south.$q$, $q$Eles moram no sul.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$East$q$, $q$leste$q$, $q$The sun rises in the east.$q$, $q$O sol nasce no leste.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$West$q$, $q$oeste$q$, $q$The sun sets in the west.$q$, $q$O sol se põe no oeste.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Coast$q$, $q$costa$q$, $q$We live near the coast.$q$, $q$Nós moramos perto da costa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Citizen$q$, $q$cidadão$q$, $q$She is a Brazilian citizen.$q$, $q$Ela é cidadã brasileira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tourist$q$, $q$turista$q$, $q$A tourist takes a photo.$q$, $q$Um turista tira uma foto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Passport$q$, $q$passaporte$q$, $q$I need my passport to travel.$q$, $q$Eu preciso do meu passaporte para viajar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fridge$q$, $q$geladeira$q$, $q$The milk is in the fridge.$q$, $q$O leite está na geladeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Stove$q$, $q$fogão$q$, $q$She cooks on the stove.$q$, $q$Ela cozinha no fogão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sink$q$, $q$pia$q$, $q$He washes his hands at the sink.$q$, $q$Ele lava as mãos na pia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Faucet$q$, $q$torneira$q$, $q$Turn off the faucet, please.$q$, $q$Feche a torneira, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Toilet$q$, $q$vaso sanitário$q$, $q$The toilet is clean.$q$, $q$O vaso sanitário está limpo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shower$q$, $q$chuveiro$q$, $q$I take a shower every morning.$q$, $q$Eu tomo banho de chuveiro toda manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bathtub$q$, $q$banheira$q$, $q$The baby plays in the bathtub.$q$, $q$O bebê brinca na banheira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Comb$q$, $q$pente$q$, $q$She uses a comb every day.$q$, $q$Ela usa um pente todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Toothbrush$q$, $q$escova de dentes$q$, $q$I keep my toothbrush in the bathroom.$q$, $q$Eu guardo minha escova de dentes no banheiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mattress$q$, $q$colchão$q$, $q$The mattress is very soft.$q$, $q$O colchão é muito macio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Count$q$, $q$contar números$q$, $q$I count the apples in the basket.$q$, $q$Eu conto as maçãs na cesta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Stack$q$, $q$empilhar$q$, $q$I stack the books on the table.$q$, $q$Eu empilho os livros na mesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Build$q$, $q$construir$q$, $q$They build a new house.$q$, $q$Eles constroem uma casa nova.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cover$q$, $q$cobrir$q$, $q$I cover the food with a napkin.$q$, $q$Eu cubro a comida com um guardanapo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mix$q$, $q$misturar$q$, $q$I mix the flour and the sugar.$q$, $q$Eu misturo a farinha e o açúcar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pack$q$, $q$empacotar$q$, $q$I pack my bag for the trip.$q$, $q$Eu empacoto a mala para a viagem.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Melt$q$, $q$derreter$q$, $q$The ice starts to melt.$q$, $q$O gelo começa a derreter.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Freeze$q$, $q$congelar$q$, $q$I freeze the meat for later.$q$, $q$Eu congelo a carne para depois.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Boil$q$, $q$ferver$q$, $q$I boil the water for tea.$q$, $q$Eu fervo a água para o chá.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bake$q$, $q$assar$q$, $q$I bake a cake for the party.$q$, $q$Eu asso um bolo para a festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Borrow$q$, $q$pegar emprestado$q$, $q$Can I borrow your pen?$q$, $q$Posso pegar sua caneta emprestada?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lend$q$, $q$emprestar$q$, $q$Can you lend me some money?$q$, $q$Você pode me emprestar um dinheiro?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Spend$q$, $q$gastar$q$, $q$I spend too much money on clothes.$q$, $q$Eu gasto muito dinheiro com roupas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Waste$q$, $q$desperdiçar$q$, $q$Don't waste your time.$q$, $q$Não desperdice seu tempo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Invite$q$, $q$convidar$q$, $q$I invite my friends to the party.$q$, $q$Eu convido meus amigos para a festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Agree$q$, $q$concordar$q$, $q$I agree with you.$q$, $q$Eu concordo com você.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Refuse$q$, $q$recusar$q$, $q$I refuse to eat vegetables.$q$, $q$Eu recuso comer legumes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Promise$q$, $q$prometer$q$, $q$I promise to help you.$q$, $q$Eu prometo te ajudar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Forgive$q$, $q$perdoar$q$, $q$Please forgive me.$q$, $q$Por favor, me perdoe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Warn$q$, $q$avisar$q$, $q$I warn him about the danger.$q$, $q$Eu aviso ele sobre o perigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ugly$q$, $q$feio$q$, $q$The old shoes are ugly.$q$, $q$Os sapatos velhos são feios.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pretty$q$, $q$bonitinho$q$, $q$She has a pretty smile.$q$, $q$Ela tem um sorriso bonitinho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bald$q$, $q$careca$q$, $q$My grandfather is bald.$q$, $q$Meu avô é careca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Blond$q$, $q$loiro$q$, $q$She has blond hair.$q$, $q$Ela tem cabelo loiro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pale$q$, $q$pálido$q$, $q$He looks pale today.$q$, $q$Ele parece pálido hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sleepy$q$, $q$sonolento$q$, $q$I feel sleepy after lunch.$q$, $q$Eu me sinto sonolento depois do almoço.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Healthy$q$, $q$saudável$q$, $q$She eats healthy food.$q$, $q$Ela come comida saudável.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hungry$q$, $q$com fome$q$, $q$I am very hungry.$q$, $q$Eu estou com muita fome.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thirsty$q$, $q$com sede$q$, $q$He is thirsty after running.$q$, $q$Ele está com sede depois de correr.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Dizzy$q$, $q$tonto$q$, $q$I feel dizzy right now.$q$, $q$Eu estou tonto agora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Firefighter$q$, $q$bombeiro$q$, $q$The firefighter saves the cat.$q$, $q$O bombeiro salva o gato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mechanic$q$, $q$mecânico$q$, $q$The mechanic fixes my car.$q$, $q$O mecânico conserta meu carro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Baker$q$, $q$padeiro$q$, $q$The baker makes fresh bread.$q$, $q$O padeiro faz pão fresco.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Plumber$q$, $q$encanador$q$, $q$The plumber fixes the sink.$q$, $q$O encanador conserta a pia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Soldier$q$, $q$soldado$q$, $q$The soldier protects the country.$q$, $q$O soldado protege o país.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Judge$q$, $q$juiz$q$, $q$The judge listens carefully.$q$, $q$O juiz escuta com atenção.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thief$q$, $q$ladrão$q$, $q$The thief runs away fast.$q$, $q$O ladrão foge rápido.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Postman$q$, $q$carteiro$q$, $q$The postman brings the mail.$q$, $q$O carteiro traz a correspondência.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sailor$q$, $q$marinheiro$q$, $q$The sailor loves the sea.$q$, $q$O marinheiro adora o mar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Writer$q$, $q$escritor$q$, $q$She is a famous writer.$q$, $q$Ela é uma escritora famosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bug$q$, $q$bicho pequeno$q$, $q$There is a bug on the leaf.$q$, $q$Há um bicho pequeno na folha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Worm$q$, $q$minhoca$q$, $q$The bird eats a worm.$q$, $q$O pássaro come uma minhoca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wing$q$, $q$asa$q$, $q$The bird has a hurt wing.$q$, $q$O pássaro tem uma asa machucada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tail$q$, $q$rabo$q$, $q$The dog wags its tail.$q$, $q$O cachorro balança o rabo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Feather$q$, $q$pena de ave$q$, $q$A feather falls from the bird.$q$, $q$Uma pena cai do pássaro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nest$q$, $q$ninho$q$, $q$The bird builds a nest.$q$, $q$O pássaro constrói um ninho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Horn$q$, $q$chifre$q$, $q$The bull has a big horn.$q$, $q$O touro tem um chifre grande.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Paw$q$, $q$pata$q$, $q$The dog hurts its paw.$q$, $q$O cachorro machuca a pata.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fur$q$, $q$pelo de animal$q$, $q$The cat has soft fur.$q$, $q$O gato tem pelo macio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Seed$q$, $q$semente$q$, $q$She plants a seed in the garden.$q$, $q$Ela planta uma semente no jardim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Air$q$, $q$ar$q$, $q$The air is fresh here.$q$, $q$O ar é fresco aqui.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shadow$q$, $q$sombra$q$, $q$My shadow is very long.$q$, $q$Minha sombra é muito comprida.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fog$q$, $q$neblina$q$, $q$The fog covers the city.$q$, $q$A neblina cobre a cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thunder$q$, $q$trovão$q$, $q$I hear thunder outside.$q$, $q$Eu ouço trovão lá fora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lightning$q$, $q$raio$q$, $q$The lightning is very bright.$q$, $q$O raio está muito brilhante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Flood$q$, $q$enchente$q$, $q$The flood damages the houses.$q$, $q$A enchente danifica as casas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Earthquake$q$, $q$terremoto$q$, $q$The earthquake shakes the city.$q$, $q$O terremoto sacode a cidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Volcano$q$, $q$vulcão$q$, $q$The volcano is dangerous.$q$, $q$O vulcão é perigoso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Dust$q$, $q$poeira$q$, $q$There is dust on the table.$q$, $q$Há poeira na mesa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mud$q$, $q$lama$q$, $q$The kids play in the mud.$q$, $q$As crianças brincam na lama.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
