-- Frases-exemplo do Mental Lingo: lingo_exemplos_intermediario_lote5.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mainland$q$, $q$terra firme$q$, $q$They travel from the island to the mainland.$q$, $q$Eles viajam da ilha para a terra firme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Peninsula$q$, $q$península$q$, $q$Spain sits on the Iberian Peninsula.$q$, $q$A Espanha fica na Península Ibérica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Plain$q$, $q$planície$q$, $q$Farmers grow wheat on the plain.$q$, $q$Os agricultores cultivam trigo na planície.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Canyon$q$, $q$vale profundo$q$, $q$They hike through the deep canyon.$q$, $q$Eles caminham pelo vale profundo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Range$q$, $q$cordilheira$q$, $q$The mountain range stretches for miles.$q$, $q$A cordilheira se estende por quilômetros.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Glacier$q$, $q$geleira$q$, $q$The glacier melts a little every year.$q$, $q$A geleira derrete um pouco todo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Swamp$q$, $q$pântano$q$, $q$Alligators live in the swamp.$q$, $q$Jacarés vivem no pântano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Archipelago$q$, $q$arquipélago$q$, $q$The archipelago has hundreds of small islands.$q$, $q$O arquipélago tem centenas de ilhas pequenas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hemisphere$q$, $q$hemisfério$q$, $q$Brazil is located in the southern hemisphere.$q$, $q$O Brasil fica localizado no hemisfério sul.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Equator$q$, $q$equador$q$, $q$The equator crosses several countries.$q$, $q$O equador atravessa vários países.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rebellion$q$, $q$rebelião$q$, $q$The rebellion begins after years of injustice.$q$, $q$A rebelião começa depois de anos de injustiça.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Empire$q$, $q$império$q$, $q$The empire expands across the continent.$q$, $q$O império se expande pelo continente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Revolution$q$, $q$revolução$q$, $q$The revolution changes the country forever.$q$, $q$A revolução muda o país para sempre.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Colony$q$, $q$colônia$q$, $q$This region was once a colony.$q$, $q$Esta região já foi uma colônia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Independence$q$, $q$independência$q$, $q$The country celebrates its independence every year.$q$, $q$O país comemora sua independência todo ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ancestor$q$, $q$antepassado$q$, $q$Her ancestor came from Portugal.$q$, $q$O antepassado dela veio de Portugal.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Monarch$q$, $q$monarca$q$, $q$The monarch rules for over forty years.$q$, $q$O monarca governa por mais de quarenta anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Antiquity$q$, $q$antiguidade$q$, $q$These objects come from antiquity.$q$, $q$Estes objetos vêm da antiguidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ruin$q$, $q$ruína$q$, $q$Tourists visit the ancient ruin every summer.$q$, $q$Turistas visitam a ruína antiga todo verão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Treaty$q$, $q$tratado$q$, $q$Both countries sign a peace treaty.$q$, $q$Os dois países assinam um tratado de paz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fireplace$q$, $q$lareira$q$, $q$We sit near the fireplace in winter.$q$, $q$Nós sentamos perto da lareira no inverno.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Wardrobe$q$, $q$guarda-roupa$q$, $q$She keeps her coats in the wardrobe.$q$, $q$Ela guarda os casacos dela no guarda-roupa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cupboard$q$, $q$armário de cozinha$q$, $q$He puts the plates in the cupboard.$q$, $q$Ele guarda os pratos no armário de cozinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Doorway$q$, $q$batente de porta$q$, $q$The dog waits in the doorway.$q$, $q$O cachorro espera no batente da porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Step$q$, $q$degrau$q$, $q$Be careful on the last step.$q$, $q$Cuidado com o último degrau.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Handrail$q$, $q$corrimão$q$, $q$She holds the handrail going up the stairs.$q$, $q$Ela segura o corrimão subindo a escada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Doorknob$q$, $q$maçaneta$q$, $q$He turns the doorknob slowly.$q$, $q$Ele gira a maçaneta devagar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Switch$q$, $q$interruptor$q$, $q$She turns off the light switch.$q$, $q$Ela desliga o interruptor de luz.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Outlet$q$, $q$tomada elétrica$q$, $q$The lamp plugs into the outlet.$q$, $q$A lâmpada se conecta na tomada elétrica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Dresser$q$, $q$cômoda$q$, $q$She keeps her socks in the dresser.$q$, $q$Ela guarda as meias na cômoda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Drill$q$, $q$furadeira$q$, $q$He uses a drill to hang the picture.$q$, $q$Ele usa uma furadeira para pendurar o quadro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Screwdriver$q$, $q$chave de fenda$q$, $q$She fixes the chair with a screwdriver.$q$, $q$Ela conserta a cadeira com uma chave de fenda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Saw$q$, $q$serra$q$, $q$He cuts the wood with a saw.$q$, $q$Ele corta a madeira com uma serra.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pliers$q$, $q$alicate$q$, $q$I use pliers to bend the wire.$q$, $q$Eu uso um alicate para dobrar o fio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Level$q$, $q$nível de bolha$q$, $q$He checks the shelf with a level.$q$, $q$Ele confere a prateleira com um nível de bolha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Shovel$q$, $q$pá$q$, $q$She digs the hole with a shovel.$q$, $q$Ela cava o buraco com uma pá.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hoe$q$, $q$enxada$q$, $q$He works the soil with a hoe.$q$, $q$Ele trabalha a terra com uma enxada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sandpaper$q$, $q$lixa$q$, $q$She smooths the wood with sandpaper.$q$, $q$Ela alisa a madeira com lixa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bolt$q$, $q$parafuso com porca$q$, $q$He tightens the bolt with a wrench.$q$, $q$Ele aperta o parafuso com uma chave.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Sledgehammer$q$, $q$marreta$q$, $q$They break the wall with a sledgehammer.$q$, $q$Eles quebram a parede com uma marreta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Manners$q$, $q$boas maneiras$q$, $q$Good manners matter at the dinner table.$q$, $q$Boas maneiras importam à mesa de jantar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Kindness$q$, $q$gentileza$q$, $q$Her kindness surprises everyone she meets.$q$, $q$A gentileza dela surpreende todos que ela conhece.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rudeness$q$, $q$grosseria$q$, $q$His rudeness upsets the whole team.$q$, $q$A grosseria dele incomoda a equipe toda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Apology$q$, $q$pedido de desculpas$q$, $q$He offers a sincere apology.$q$, $q$Ele oferece um pedido de desculpas sincero.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Tip$q$, $q$gorjeta$q$, $q$We leave a generous tip for the waiter.$q$, $q$Nós deixamos uma gorjeta generosa para o garçom.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Coexistence$q$, $q$convivência$q$, $q$The two cultures find a peaceful coexistence.$q$, $q$As duas culturas encontram uma convivência pacífica.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Cooperation$q$, $q$cooperação$q$, $q$The project depends on team cooperation.$q$, $q$O projeto depende da cooperação da equipe.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Intimacy$q$, $q$intimidade$q$, $q$They build intimacy through daily conversations.$q$, $q$Eles constroem intimidade através de conversas diárias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hospitality$q$, $q$hospitalidade$q$, $q$We enjoy their warm hospitality.$q$, $q$Nós apreciamos a calorosa hospitalidade deles.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Solidarity$q$, $q$solidariedade$q$, $q$Neighbors show solidarity during the crisis.$q$, $q$Os vizinhos demonstram solidariedade durante a crise.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mayor$q$, $q$prefeito$q$, $q$The mayor opens the new park.$q$, $q$O prefeito inaugura o novo parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Precinct$q$, $q$delegacia$q$, $q$She reports the theft at the precinct.$q$, $q$Ela relata o roubo na delegacia.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Registry$q$, $q$cartório$q$, $q$He goes to the registry for his documents.$q$, $q$Ele vai ao cartório buscar os documentos dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Plaza$q$, $q$praça central$q$, $q$People gather in the plaza on weekends.$q$, $q$As pessoas se reúnem na praça central nos fins de semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Ambulance$q$, $q$ambulância$q$, $q$The ambulance arrives within minutes.$q$, $q$A ambulância chega em minutos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Terminal$q$, $q$rodoviária$q$, $q$We wait at the bus terminal.$q$, $q$Nós esperamos na rodoviária.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Boardwalk$q$, $q$calçadão$q$, $q$We walk along the boardwalk at sunset.$q$, $q$Nós caminhamos pelo calçadão ao entardecer.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Bazaar$q$, $q$feira popular$q$, $q$They sell handmade items at the bazaar.$q$, $q$Eles vendem itens artesanais na feira popular.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Clinic$q$, $q$clínica$q$, $q$She works at a small local clinic.$q$, $q$Ela trabalha numa pequena clínica local.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mailbox$q$, $q$caixa de correio$q$, $q$He checks the mailbox every afternoon.$q$, $q$Ele confere a caixa de correio toda tarde.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Incredible$q$, $q$incrível$q$, $q$The view from the top is incredible.$q$, $q$A vista do topo é incrível.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Terrible$q$, $q$terrível$q$, $q$The traffic today is terrible.$q$, $q$O trânsito hoje está terrível.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Marvelous$q$, $q$maravilhoso$q$, $q$The concert is a marvelous experience.$q$, $q$O show é uma experiência maravilhosa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Disappointing$q$, $q$decepcionante$q$, $q$The ending of the movie is disappointing.$q$, $q$O final do filme é decepcionante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Boring$q$, $q$chato$q$, $q$The lecture feels a bit boring today.$q$, $q$A palestra parece um pouco chata hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Thrilling$q$, $q$emocionante$q$, $q$The roller coaster ride is thrilling.$q$, $q$O passeio na montanha-russa é emocionante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Annoying$q$, $q$irritante$q$, $q$His loud music is very annoying.$q$, $q$A música alta dele é muito irritante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Relaxing$q$, $q$relaxante$q$, $q$A walk in the park is relaxing.$q$, $q$Uma caminhada no parque é relaxante.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Astonishing$q$, $q$surpreendente$q$, $q$The results are truly astonishing.$q$, $q$Os resultados são verdadeiramente surpreendentes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Confusing$q$, $q$confuso$q$, $q$These instructions are quite confusing.$q$, $q$Estas instruções são bem confusas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Fortunately$q$, $q$felizmente$q$, $q$Fortunately, no one gets hurt.$q$, $q$Felizmente, ninguém se machuca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Unfortunately$q$, $q$infelizmente$q$, $q$Unfortunately, the flight is cancelled.$q$, $q$Infelizmente, o voo é cancelado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Obviously$q$, $q$obviamente$q$, $q$Obviously, we need more time.$q$, $q$Obviamente, nós precisamos de mais tempo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Clearly$q$, $q$claramente$q$, $q$She explains the plan clearly.$q$, $q$Ela explica o plano claramente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Presumably$q$, $q$presumivelmente$q$, $q$Presumably, the train will be late.$q$, $q$Presumivelmente, o trem vai atrasar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Seldom$q$, $q$raramente$q$, $q$They seldom go out during the week.$q$, $q$Eles raramente saem durante a semana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Constantly$q$, $q$constantemente$q$, $q$He constantly checks his phone.$q$, $q$Ele constantemente confere o telefone dele.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Immediately$q$, $q$imediatamente$q$, $q$Please call me immediately.$q$, $q$Por favor, me ligue imediatamente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Roughly$q$, $q$aproximadamente$q$, $q$The trip takes roughly two hours.$q$, $q$A viagem leva aproximadamente duas horas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Mainly$q$, $q$principalmente$q$, $q$The team focuses mainly on quality.$q$, $q$A equipe foca principalmente em qualidade.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Therefore$q$, $q$portanto$q$, $q$It is raining; therefore, we stay inside.$q$, $q$Está chovendo; portanto, nós ficamos dentro de casa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Nevertheless$q$, $q$entretanto$q$, $q$The plan is risky; nevertheless, they try it.$q$, $q$O plano é arriscado; entretanto, eles o tentam.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Moreover$q$, $q$além disso$q$, $q$The house is big; moreover, it has a garden.$q$, $q$A casa é grande; além disso, tem um jardim.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Nonetheless$q$, $q$ainda assim$q$, $q$It is late; nonetheless, we finish the work.$q$, $q$Está tarde; ainda assim, nós terminamos o trabalho.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Whereas$q$, $q$enquanto que$q$, $q$He likes coffee, whereas she prefers tea.$q$, $q$Ele gosta de café, enquanto ela prefere chá.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Instead$q$, $q$em vez disso$q$, $q$We stay home instead of going out.$q$, $q$Nós ficamos em casa em vez de sair.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Otherwise$q$, $q$caso contrário$q$, $q$Hurry up, otherwise we will be late.$q$, $q$Se apresse, caso contrário nós vamos nos atrasar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Indeed$q$, $q$de fato$q$, $q$The results are, indeed, very promising.$q$, $q$Os resultados são, de fato, muito promissores.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Albeit$q$, $q$embora$q$, $q$The trip is short, albeit expensive.$q$, $q$A viagem é curta, embora cara.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Afterwards$q$, $q$logo depois$q$, $q$We eat dinner and, afterwards, watch a movie.$q$, $q$Nós jantamos e, logo depois, assistimos a um filme.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Grab$q$, $q$agarrar com força$q$, $q$I grab the rope with both hands.$q$, $q$Eu agarro a corda com as duas mãos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Hurl$q$, $q$arremessar com força$q$, $q$I hurl the rock into the river.$q$, $q$Eu arremesso a pedra no rio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Heap$q$, $q$amontoar$q$, $q$I heap the clothes on the bed.$q$, $q$Eu amontoo as roupas na cama.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Scrub$q$, $q$esfregar$q$, $q$I scrub the pan until it shines.$q$, $q$Eu esfrego a panela até brilhar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Squeeze$q$, $q$espremer$q$, $q$I squeeze the lemon into the tea.$q$, $q$Eu espremo o limão no chá.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Pinch$q$, $q$beliscar$q$, $q$I pinch the dough to close it.$q$, $q$Eu belisco a massa para fechá-la.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Poke$q$, $q$cutucar$q$, $q$I poke the balloon with a pin.$q$, $q$Eu cutuco o balão com um alfinete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Swing$q$, $q$balançar$q$, $q$The kids swing on the old rope.$q$, $q$As crianças balançam na corda velha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Spill$q$, $q$derramar$q$, $q$I spill coffee on my shirt.$q$, $q$Eu derramo café na minha camisa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$intermediario$q$, $q$Rip$q$, $q$rasgar$q$, $q$I rip the paper by accident.$q$, $q$Eu rasgo o papel por acidente.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
