-- Frases-exemplo do Mental Lingo: lingo_exemplos_basico_lote7.json (100 frases). Idempotente.
begin;
-- MENTAL LINGO fase 2 — frases-exemplo curadas por palavra (aprovado por Rhoney, 26/09/2026).
-- Uma frase curta com tradução por palavra, escrita e revisada por humanos (nunca gerada em
-- tempo real). Só 'approved' é servida. A fala da tradução em português vale só para o nível
-- 'basico' (decisão de Rhoney: no Intermediário/Avançado só a frase em inglês).

create table if not exists mental.lingo_exemplos (
    id uuid primary key default gen_random_uuid(),
    idioma text not null default 'ingles',
    nivel text not null check (nivel in ('basico', 'intermediario', 'avancado')),
    palavra text not null,
    palavra_pt text,
    frase text not null,
    traducao text not null,
    review_status text not null default 'approved',
    created_at timestamp not null default (now() at time zone 'utc'),
    unique (idioma, palavra, frase)
);
create index if not exists idx_lingo_exemplos_palavra on mental.lingo_exemplos (idioma, lower(palavra));

alter table mental.lingo_exemplos enable row level security;

insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Peach$q$, $q$pêssego$q$, $q$I eat a peach for breakfast.$q$, $q$Eu como um pêssego no café da manhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pear$q$, $q$pera$q$, $q$She buys a pear at the market.$q$, $q$Ela compra uma pera no mercado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cherry$q$, $q$cereja$q$, $q$I like the taste of cherry.$q$, $q$Eu gosto do sabor de cereja.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Watermelon$q$, $q$melancia$q$, $q$We eat watermelon in summer.$q$, $q$Nós comemos melancia no verão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mango$q$, $q$manga fruta$q$, $q$The mango is very sweet.$q$, $q$A manga é muito doce.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Corn$q$, $q$milho$q$, $q$We eat corn at the party.$q$, $q$Nós comemos milho na festa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Mushroom$q$, $q$cogumelo$q$, $q$She adds mushroom to the soup.$q$, $q$Ela adiciona cogumelo na sopa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bitter$q$, $q$amargo$q$, $q$This coffee is too bitter.$q$, $q$Este café está muito amargo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sour$q$, $q$azedo$q$, $q$The lemon is very sour.$q$, $q$O limão é muito azedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Salty$q$, $q$salgado$q$, $q$The soup is too salty.$q$, $q$A sopa está muito salgada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hammer$q$, $q$martelo$q$, $q$He uses a hammer to fix the chair.$q$, $q$Ele usa um martelo para consertar a cadeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Rope$q$, $q$corda$q$, $q$They climb with a rope.$q$, $q$Eles escalam com uma corda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ladder$q$, $q$escada de mão$q$, $q$He climbs the ladder to paint the wall.$q$, $q$Ele sobe na escada de mão para pintar a parede.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Bucket$q$, $q$balde$q$, $q$She fills the bucket with water.$q$, $q$Ela enche o balde com água.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Broom$q$, $q$vassoura$q$, $q$I clean the floor with a broom.$q$, $q$Eu limpo o chão com uma vassoura.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Needle$q$, $q$agulha$q$, $q$She sews with a needle.$q$, $q$Ela costura com uma agulha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Scissors$q$, $q$tesoura$q$, $q$I cut the paper with scissors.$q$, $q$Eu corto o papel com uma tesoura.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Glue$q$, $q$cola$q$, $q$He uses glue to fix the toy.$q$, $q$Ele usa cola para consertar o brinquedo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tool$q$, $q$ferramenta$q$, $q$This tool is very useful.$q$, $q$Esta ferramenta é muito útil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wire$q$, $q$fio$q$, $q$The wire is very thin.$q$, $q$O fio é muito fino.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Boyfriend$q$, $q$namorado$q$, $q$She talks to her boyfriend every day.$q$, $q$Ela fala com o namorado todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Girlfriend$q$, $q$namorada$q$, $q$He calls his girlfriend at night.$q$, $q$Ele liga para a namorada à noite.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wedding$q$, $q$casamento$q$, $q$The wedding is on Saturday.$q$, $q$O casamento é no sábado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Enemy$q$, $q$inimigo$q$, $q$He is not my enemy.$q$, $q$Ele não é meu inimigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hero$q$, $q$herói$q$, $q$My father is my hero.$q$, $q$Meu pai é meu herói.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Leader$q$, $q$líder$q$, $q$She is a good leader.$q$, $q$Ela é uma boa líder.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Member$q$, $q$membro$q$, $q$He is a member of the team.$q$, $q$Ele é membro do time.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Owner$q$, $q$dono$q$, $q$The owner of the store is kind.$q$, $q$O dono da loja é gentil.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Elderly$q$, $q$idoso$q$, $q$We help the elderly cross the street.$q$, $q$Nós ajudamos os idosos a atravessar a rua.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Teenager$q$, $q$adolescente$q$, $q$My daughter is a teenager now.$q$, $q$Minha filha é adolescente agora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Enter$q$, $q$entrar$q$, $q$Please enter the room.$q$, $q$Por favor, entre na sala.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fill$q$, $q$encher$q$, $q$Fill the glass with water.$q$, $q$Encha o copo com água.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Pour$q$, $q$despejar$q$, $q$I pour the milk into the cup.$q$, $q$Eu despejo o leite no copo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Burn$q$, $q$queimar$q$, $q$Be careful, don't burn your hand.$q$, $q$Cuidado, não queime a mão.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Drop$q$, $q$deixar cair$q$, $q$Don't drop the phone.$q$, $q$Não deixe o telefone cair.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lift$q$, $q$levantar algo$q$, $q$Help me lift this box.$q$, $q$Me ajude a levantar esta caixa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Kick$q$, $q$chutar$q$, $q$I kick the ball to my friend.$q$, $q$Eu chuto a bola para meu amigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Kiss$q$, $q$beijar$q$, $q$I kiss my mother goodnight.$q$, $q$Eu beijo minha mãe antes de dormir.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hug$q$, $q$abraçar$q$, $q$They hug each other happily.$q$, $q$Eles se abraçam felizes.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Grin$q$, $q$sorrir$q$, $q$I grin at my friend.$q$, $q$Eu sorrio para meu amigo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Laugh$q$, $q$rir$q$, $q$The children laugh at the joke.$q$, $q$As crianças riem da piada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Cry$q$, $q$chorar$q$, $q$The baby starts to cry.$q$, $q$O bebê começa a chorar.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Shout$q$, $q$gritar$q$, $q$Don't shout in the library.$q$, $q$Não grite na biblioteca.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Whisper$q$, $q$sussurrar$q$, $q$I whisper the secret to her.$q$, $q$Eu sussurro o segredo para ela.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Breathe$q$, $q$respirar$q$, $q$Breathe slowly, please.$q$, $q$Respire devagar, por favor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Paint$q$, $q$pintar$q$, $q$I paint the wall blue.$q$, $q$Eu pinto a parede de azul.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Draw$q$, $q$desenhar$q$, $q$She likes to draw animals.$q$, $q$Ela gosta de desenhar animais.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fly$q$, $q$voar$q$, $q$Birds fly in the sky.$q$, $q$Os pássaros voam no céu.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Grow$q$, $q$crescer$q$, $q$Plants grow in the sun.$q$, $q$As plantas crescem no sol.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ride$q$, $q$andar de bicicleta$q$, $q$I ride my bike to school.$q$, $q$Eu ando de bicicleta para a escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thick$q$, $q$grosso$q$, $q$The book is very thick.$q$, $q$O livro é muito grosso.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sharp$q$, $q$afiado$q$, $q$Be careful, the knife is sharp.$q$, $q$Cuidado, a faca está afiada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Smooth$q$, $q$liso$q$, $q$The stone is very smooth.$q$, $q$A pedra é muito lisa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Rough$q$, $q$áspero$q$, $q$The road is very rough.$q$, $q$A estrada é muito áspera.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Soft$q$, $q$macio$q$, $q$The blanket is very soft.$q$, $q$O cobertor é muito macio.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Hard$q$, $q$duro$q$, $q$The chair is too hard.$q$, $q$A cadeira é muito dura.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Flat$q$, $q$plano$q$, $q$The land here is very flat.$q$, $q$A terra aqui é muito plana.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Round$q$, $q$redondo$q$, $q$The table is round.$q$, $q$A mesa é redonda.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Tight$q$, $q$apertado$q$, $q$These shoes are too tight.$q$, $q$Estes sapatos estão muito apertados.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Loose$q$, $q$solto$q$, $q$The rope is loose.$q$, $q$A corda está solta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ready$q$, $q$pronto$q$, $q$Are you ready for the test?$q$, $q$Você está pronto para a prova?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Wrong$q$, $q$errado$q$, $q$This answer is wrong.$q$, $q$Esta resposta está errada.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$True$q$, $q$verdadeiro$q$, $q$Her story is true.$q$, $q$A história dela é verdadeira.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$False$q$, $q$falso$q$, $q$His answer is false.$q$, $q$A resposta dele é falsa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Alone$q$, $q$sozinho$q$, $q$She likes to walk alone.$q$, $q$Ela gosta de caminhar sozinha.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Lucky$q$, $q$sortudo$q$, $q$I feel very lucky today.$q$, $q$Eu me sinto muito sortudo hoje.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Unique$q$, $q$único$q$, $q$Every person is unique.$q$, $q$Cada pessoa é única.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sure$q$, $q$certo de algo$q$, $q$Are you sure about this?$q$, $q$Você tem certeza disso?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Same$q$, $q$mesmo igual$q$, $q$We have the same shoes.$q$, $q$Nós temos o mesmo sapato.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Other$q$, $q$outro$q$, $q$I want the other one.$q$, $q$Eu quero o outro.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Eleven$q$, $q$onze$q$, $q$The movie starts at eleven.$q$, $q$O filme começa às onze.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Twelve$q$, $q$doze$q$, $q$There are twelve months in a year.$q$, $q$Há doze meses num ano.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Twenty$q$, $q$vinte$q$, $q$She is twenty years old.$q$, $q$Ela tem vinte anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thirty$q$, $q$trinta$q$, $q$My father is thirty five years old.$q$, $q$Meu pai tem trinta e cinco anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Forty$q$, $q$quarenta$q$, $q$There are forty students in the school.$q$, $q$Há quarenta alunos na escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Fifty$q$, $q$cinquenta$q$, $q$The ticket costs fifty dollars.$q$, $q$O bilhete custa cinquenta dólares.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Sixty$q$, $q$sessenta$q$, $q$My grandmother is sixty years old.$q$, $q$Minha avó tem sessenta anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Ninety$q$, $q$noventa$q$, $q$The old man is ninety years old.$q$, $q$O senhor idoso tem noventa anos.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Thousand$q$, $q$mil$q$, $q$The book has one thousand pages.$q$, $q$O livro tem mil páginas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Million$q$, $q$milhão$q$, $q$The city has one million people.$q$, $q$A cidade tem um milhão de pessoas.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Why$q$, $q$por que$q$, $q$Why are you sad?$q$, $q$Por que você está triste?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Whose$q$, $q$de quem$q$, $q$Whose bag is this?$q$, $q$De quem é esta bolsa?$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Something$q$, $q$algo$q$, $q$I want to tell you something.$q$, $q$Eu quero te contar algo.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nothing$q$, $q$nada$q$, $q$There is nothing in the box.$q$, $q$Não há nada na caixa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Everything$q$, $q$tudo$q$, $q$She knows everything about music.$q$, $q$Ela sabe tudo sobre música.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Everyone$q$, $q$todos$q$, $q$Everyone likes the teacher.$q$, $q$Todos gostam do professor.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Someone$q$, $q$alguém$q$, $q$Someone is at the door.$q$, $q$Alguém está na porta.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nobody$q$, $q$ninguém$q$, $q$Nobody is home now.$q$, $q$Ninguém está em casa agora.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Anything$q$, $q$qualquer coisa$q$, $q$You can ask me anything.$q$, $q$Você pode me perguntar qualquer coisa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Nowhere$q$, $q$em lugar nenhum$q$, $q$The keys are nowhere to be found.$q$, $q$As chaves não estão em lugar nenhum.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Often$q$, $q$frequentemente$q$, $q$I often walk to school.$q$, $q$Eu frequentemente vou a pé para a escola.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Usually$q$, $q$geralmente$q$, $q$I usually wake up at seven.$q$, $q$Eu geralmente acordo às sete.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Almost$q$, $q$quase$q$, $q$I am almost ready.$q$, $q$Eu estou quase pronto.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Maybe$q$, $q$talvez$q$, $q$Maybe we can go tomorrow.$q$, $q$Talvez nós possamos ir amanhã.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Really$q$, $q$realmente$q$, $q$I really like this song.$q$, $q$Eu realmente gosto desta música.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Together$q$, $q$juntos$q$, $q$We study together every day.$q$, $q$Nós estudamos juntos todos os dias.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Quickly$q$, $q$rapidamente$q$, $q$She runs quickly to the bus.$q$, $q$Ela corre rapidamente para o ônibus.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Slowly$q$, $q$devagar$q$, $q$He walks slowly in the park.$q$, $q$Ele caminha devagar no parque.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Carefully$q$, $q$com cuidado$q$, $q$Please drive carefully.$q$, $q$Por favor, dirija com cuidado.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
insert into mental.lingo_exemplos (idioma, nivel, palavra, palavra_pt, frase, traducao, review_status) values ($q$ingles$q$, $q$basico$q$, $q$Suddenly$q$, $q$de repente$q$, $q$Suddenly, the rain starts.$q$, $q$De repente, a chuva começa.$q$, 'approved') on conflict (idioma, palavra, frase) do nothing;
commit;
