from sqlalchemy.orm import Session

from . import models

TERRITORIES = [
    {"id": "palavras", "challenge_type": "palavras", "requires_subscription": False, "free_sample_count": 0, "display_order": 1},
    {"id": "numeros", "challenge_type": "numeros", "requires_subscription": False, "free_sample_count": 0, "display_order": 2},
    {"id": "logica", "challenge_type": "logica", "requires_subscription": True, "free_sample_count": 2, "display_order": 3},
    {"id": "conhecimento", "challenge_type": "conhecimento", "requires_subscription": True, "free_sample_count": 2, "display_order": 4},
]

# V2 item 1 — Badges/Conquistas (V2_KICKOFF.md §6A). Catálogo curado à
# mão, mesmo conteúdo espelhado em migrations/004_badges.sql.
BADGES = [
    {
        "code": "first_conquest", "name": "Primeira Conquista",
        "description": "Conquiste seu primeiro território.",
        "criteria_type": "territory_conquered_count", "criteria_value": 1, "display_order": 1,
    },
    {
        "code": "collector", "name": "Colecionador",
        "description": "Conquiste todos os territórios disponíveis.",
        "criteria_type": "all_territories_conquered", "criteria_value": 0, "display_order": 2,
    },
    {
        "code": "iron_streak", "name": "Sequência de Ferro",
        "description": "Mantenha uma sequência de 7 dias seguidos.",
        "criteria_type": "streak_days", "criteria_value": 7, "display_order": 3,
    },
    {
        "code": "sharp_mind", "name": "Mente Afiada",
        "description": "Responda corretamente 50 desafios no total.",
        "criteria_type": "total_correct_answers", "criteria_value": 50, "display_order": 4,
    },
    {
        "code": "no_help_needed", "name": "Sem Ajuda",
        "description": "Responda corretamente 10 desafios sem usar nenhuma dica.",
        "criteria_type": "hint_free_correct_answers", "criteria_value": 10, "display_order": 5,
    },
]

CHALLENGES = [
    # Palavras
    {
        "territory_id": "palavras", "difficulty_level": 1,
        "prompt": "Qual é o antônimo de 'grande'?",
        "options": ["Enorme", "Pequeno", "Alto", "Largo"],
        "correct_answer": "Pequeno",
        "explanation": "Antônimo é a palavra de sentido oposto — o oposto de 'grande' é 'pequeno'.",
        "age_reviewed": True,
        "hints": ["Pense no oposto de tamanho.", "Começa com 'P'."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 2,
        "prompt": "Reordene as letras 'ROVLI' para formar uma palavra.",
        "options": None,
        "correct_answer": "LIVRO",
        "explanation": "As letras R-O-V-L-I formam 'LIVRO'.",
        "age_reviewed": True,
        "hints": ["É um objeto que se lê.", "Tem 5 letras e começa com L."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 1,
        "prompt": "Qual é o sinônimo de 'feliz'?",
        "options": ["Alegre", "Triste", "Cansado", "Calmo"],
        "correct_answer": "Alegre",
        "explanation": "Sinônimo é a palavra de sentido parecido — 'alegre' tem o mesmo sentido de 'feliz'.",
        "age_reviewed": True,
        "hints": ["É um sentimento positivo.", "Começa com 'A'."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 2,
        "prompt": "Reordene as letras 'SALCA' para formar uma palavra.",
        "options": None,
        "correct_answer": "CASAL",
        "explanation": "As letras S-A-L-C-A formam 'CASAL'.",
        "age_reviewed": True,
        "hints": ["É uma dupla de pessoas.", "Tem 5 letras e começa com C."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 3,
        "prompt": "Qual destas palavras é antônimo de 'rápido'?",
        "options": ["Lento", "Veloz", "Ligeiro", "Ágil"],
        "correct_answer": "Lento",
        "explanation": "'Lento' é o oposto de 'rápido'; as outras opções são sinônimos de 'rápido'.",
        "age_reviewed": True,
        "hints": ["É o oposto de velocidade alta.", "Começa com 'L'."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 1,
        "prompt": "Qual é o antônimo de 'claro'?",
        "options": ["Escuro", "Brilhante", "Visível", "Aceso"],
        "correct_answer": "Escuro",
        "explanation": "'Escuro' é o oposto de 'claro'.",
        "age_reviewed": True,
        "hints": ["Pense na falta de luz.", "Começa com 'E'."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 1,
        "prompt": "Qual é o sinônimo de 'bonito'?",
        "options": ["Belo", "Feio", "Comum", "Grande"],
        "correct_answer": "Belo",
        "explanation": "'Belo' tem o mesmo sentido de 'bonito'.",
        "age_reviewed": True,
        "hints": ["É uma palavra elogiosa sobre aparência.", "Começa com 'B'."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 1,
        "prompt": "Qual é o antônimo de 'quente'?",
        "options": ["Frio", "Morno", "Ardente", "Quieto"],
        "correct_answer": "Frio",
        "explanation": "'Frio' é o oposto de 'quente'.",
        "age_reviewed": True,
        "hints": ["Pense em temperatura baixa.", "Começa com 'F'."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 2,
        "prompt": "Reordene as letras 'DERTA' para formar uma palavra.",
        "options": None,
        "correct_answer": "TARDE",
        "explanation": "As letras D-E-R-T-A formam 'TARDE'.",
        "age_reviewed": True,
        "hints": ["É um período do dia.", "Vem depois do meio-dia."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 2,
        "prompt": "Reordene as letras 'EDREV' para formar uma palavra.",
        "options": None,
        "correct_answer": "VERDE",
        "explanation": "As letras E-D-R-E-V formam 'VERDE'.",
        "age_reviewed": True,
        "hints": ["É uma cor.", "É a cor das folhas."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 3,
        "prompt": "Qual destas palavras é sinônimo de 'perspicaz'?",
        "options": ["Esperto", "Distraído", "Lento", "Confuso"],
        "correct_answer": "Esperto",
        "explanation": "'Perspicaz' descreve quem percebe as coisas rapidamente — o mesmo sentido de 'esperto'.",
        "age_reviewed": True,
        "hints": ["É uma qualidade de quem entende rápido.", "Começa com 'E'."],
    },
    {
        "territory_id": "palavras", "difficulty_level": 3,
        "prompt": "Qual destas palavras é antônimo de 'generoso'?",
        "options": ["Mesquinho", "Gentil", "Amável", "Solidário"],
        "correct_answer": "Mesquinho",
        "explanation": "'Mesquinho' é o oposto de 'generoso' — quem não gosta de compartilhar.",
        "age_reviewed": True,
        "hints": ["É quem não gosta de dar ou compartilhar.", "Começa com 'M'."],
    },
    # Números
    {
        "territory_id": "numeros", "difficulty_level": 1,
        "prompt": "Quanto é 6 + 7?",
        "options": ["12", "13", "14", "11"],
        "correct_answer": "13",
        "explanation": "6 + 7 = 13.",
        "age_reviewed": True,
        "hints": ["É maior que 12.", "É um número ímpar."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 2,
        "prompt": "Complete a sequência: 2, 4, 8, 16, ?",
        "options": ["24", "32", "20", "18"],
        "correct_answer": "32",
        "explanation": "Cada número é o dobro do anterior: 16 × 2 = 32.",
        "age_reviewed": True,
        "hints": ["Cada número é o dobro do anterior.", "16 vezes 2."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 1,
        "prompt": "Quanto é 9 - 4?",
        "options": ["4", "5", "6", "3"],
        "correct_answer": "5",
        "explanation": "9 - 4 = 5.",
        "age_reviewed": True,
        "hints": ["É um número ímpar.", "Está entre 4 e 6."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 2,
        "prompt": "Complete a sequência: 1, 1, 2, 3, 5, ?",
        "options": ["6", "7", "8", "9"],
        "correct_answer": "8",
        "explanation": "Cada número é a soma dos dois anteriores (sequência de Fibonacci): 3 + 5 = 8.",
        "age_reviewed": True,
        "hints": ["Some os dois números anteriores.", "3 + 5."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 3,
        "prompt": "Quanto é 7 × 6?",
        "options": ["40", "42", "48", "36"],
        "correct_answer": "42",
        "explanation": "7 × 6 = 42.",
        "age_reviewed": True,
        "hints": ["É maior que 40.", "É um número par."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 1,
        "prompt": "Quanto é 15 - 7?",
        "options": ["7", "8", "9", "6"],
        "correct_answer": "8",
        "explanation": "15 - 7 = 8.",
        "age_reviewed": True,
        "hints": ["É um número par.", "Está entre 6 e 9."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 1,
        "prompt": "Quanto é 4 × 3?",
        "options": ["10", "11", "12", "14"],
        "correct_answer": "12",
        "explanation": "4 × 3 = 12.",
        "age_reviewed": True,
        "hints": ["É um número par.", "É maior que 10."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 1,
        "prompt": "Quanto é 20 ÷ 4?",
        "options": ["4", "5", "6", "8"],
        "correct_answer": "5",
        "explanation": "20 ÷ 4 = 5.",
        "age_reviewed": True,
        "hints": ["É um número ímpar.", "É menor que 6."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 2,
        "prompt": "Complete a sequência: 3, 6, 9, 12, ?",
        "options": ["14", "15", "16", "18"],
        "correct_answer": "15",
        "explanation": "Cada número aumenta 3: 12 + 3 = 15.",
        "age_reviewed": True,
        "hints": ["Cada número é 3 a mais que o anterior.", "12 + 3."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 2,
        "prompt": "Complete a sequência: 100, 90, 80, 70, ?",
        "options": ["50", "60", "65", "75"],
        "correct_answer": "60",
        "explanation": "Cada número diminui 10: 70 - 10 = 60.",
        "age_reviewed": True,
        "hints": ["Cada número é 10 a menos que o anterior.", "70 - 10."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 3,
        "prompt": "Quanto é 9 × 9?",
        "options": ["72", "81", "91", "99"],
        "correct_answer": "81",
        "explanation": "9 × 9 = 81.",
        "age_reviewed": True,
        "hints": ["É maior que 72.", "Termina em 1."],
    },
    {
        "territory_id": "numeros", "difficulty_level": 3,
        "prompt": "Quanto é 144 ÷ 12?",
        "options": ["10", "11", "12", "13"],
        "correct_answer": "12",
        "explanation": "144 ÷ 12 = 12.",
        "age_reviewed": True,
        "hints": ["É um número par.", "É maior que 10."],
    },
    # Lógica
    {
        "territory_id": "logica", "difficulty_level": 1,
        "prompt": "Qual item não pertence ao grupo: Maçã, Banana, Cenoura, Uva?",
        "options": ["Maçã", "Banana", "Cenoura", "Uva"],
        "correct_answer": "Cenoura",
        "explanation": "Maçã, banana e uva são frutas; cenoura é um legume.",
        "age_reviewed": True,
        "hints": ["Três deles crescem em árvores ou parreiras.", "Um deles é um legume, não fruta."],
    },
    {
        "territory_id": "logica", "difficulty_level": 1,
        "prompt": "Qual número não pertence ao grupo: 2, 4, 6, 9?",
        "options": ["2", "4", "6", "9"],
        "correct_answer": "9",
        "explanation": "2, 4 e 6 são pares; 9 é o único número ímpar do grupo.",
        "age_reviewed": True,
        "hints": ["Três deles são números pares.", "Um deles é ímpar."],
    },
    {
        "territory_id": "logica", "difficulty_level": 2,
        "prompt": "Se hoje é terça-feira, que dia da semana será depois de amanhã?",
        "options": ["Quarta", "Quinta", "Sexta", "Segunda"],
        "correct_answer": "Quinta",
        "explanation": "Terça + 2 dias = quinta-feira.",
        "age_reviewed": True,
        "hints": ["Conte dois dias a partir de terça.", "Não é quarta, é um dia depois dela."],
    },
    {
        "territory_id": "logica", "difficulty_level": 1,
        "prompt": "Qual item não pertence ao grupo: Círculo, Quadrado, Triângulo, Vermelho?",
        "options": ["Círculo", "Quadrado", "Triângulo", "Vermelho"],
        "correct_answer": "Vermelho",
        "explanation": "Círculo, quadrado e triângulo são formas geométricas; vermelho é uma cor.",
        "age_reviewed": True,
        "hints": ["Três deles são formas geométricas.", "Um deles é uma cor."],
    },
    {
        "territory_id": "logica", "difficulty_level": 1,
        "prompt": "Qual item não pertence ao grupo: Cachorro, Gato, Cavalo, Cadeira?",
        "options": ["Cachorro", "Gato", "Cavalo", "Cadeira"],
        "correct_answer": "Cadeira",
        "explanation": "Cachorro, gato e cavalo são animais; cadeira é um objeto.",
        "age_reviewed": True,
        "hints": ["Três deles são seres vivos.", "Um deles é um móvel."],
    },
    {
        "territory_id": "logica", "difficulty_level": 1,
        "prompt": "Se A é maior que B, e B é maior que C, quem é o menor dos três?",
        "options": ["A", "B", "C", "Não dá para saber"],
        "correct_answer": "C",
        "explanation": "Se A > B e B > C, então C é o menor dos três.",
        "age_reviewed": True,
        "hints": ["Ordene do maior para o menor.", "É a última letra da comparação."],
    },
    {
        "territory_id": "logica", "difficulty_level": 2,
        "prompt": "Se ontem foi sexta-feira, qual dia será amanhã?",
        "options": ["Domingo", "Segunda", "Sábado", "Sexta"],
        "correct_answer": "Domingo",
        "explanation": "Se ontem foi sexta, hoje é sábado, então amanhã é domingo.",
        "age_reviewed": True,
        "hints": ["Primeiro descubra que dia é hoje.", "Hoje é sábado."],
    },
    {
        "territory_id": "logica", "difficulty_level": 2,
        "prompt": "Numa fila, Ana está na frente de Beto, e Beto está na frente de Carla. Quem está no fim da fila?",
        "options": ["Ana", "Beto", "Carla", "Nenhum"],
        "correct_answer": "Carla",
        "explanation": "A ordem da fila é Ana, Beto, Carla — Carla é a última.",
        "age_reviewed": True,
        "hints": ["Desenhe a ordem da fila.", "É a última pessoa mencionada."],
    },
    {
        "territory_id": "logica", "difficulty_level": 2,
        "prompt": "Complete a sequência: 1, 4, 9, 16, ?",
        "options": ["20", "24", "25", "23"],
        "correct_answer": "25",
        "explanation": "São os quadrados dos números 1, 2, 3, 4, 5: 5 × 5 = 25.",
        "age_reviewed": True,
        "hints": ["São números ao quadrado (1×1, 2×2, 3×3...).", "5 × 5."],
    },
    {
        "territory_id": "logica", "difficulty_level": 3,
        "prompt": "Todos os xis são yis. Alguns yis são zis. Podemos afirmar que todos os xis são zis?",
        "options": ["Sim", "Não", "Depende", "Sempre"],
        "correct_answer": "Não",
        "explanation": "Só sabemos que ALGUNS yis são zis — não há garantia de que os xis estejam entre esses.",
        "age_reviewed": True,
        "hints": ["'Alguns' não significa 'todos'.", "Não há informação suficiente para garantir isso."],
    },
    {
        "territory_id": "logica", "difficulty_level": 3,
        "prompt": "Num grupo de 5 amigos, cada um cumprimenta todos os outros uma vez com um aperto de mão. Quantos apertos de mão acontecem no total?",
        "options": ["8", "9", "10", "12"],
        "correct_answer": "10",
        "explanation": "Cada um dos 5 cumprimenta os outros 4, mas cada aperto é contado uma vez: (5×4)/2 = 10.",
        "age_reviewed": True,
        "hints": ["Não conte o mesmo aperto duas vezes.", "(5 × 4) ÷ 2."],
    },
    {
        "territory_id": "logica", "difficulty_level": 3,
        "prompt": "Qual número não pertence ao grupo: 3, 5, 7, 8, 11?",
        "options": ["3", "5", "7", "8"],
        "correct_answer": "8",
        "explanation": "3, 5, 7 e 11 são números primos; 8 é o único que não é primo.",
        "age_reviewed": True,
        "hints": ["Quatro deles só podem ser divididos por 1 e por si mesmos.", "Um deles é par e tem outros divisores."],
    },
    # Conhecimento
    {
        "territory_id": "conhecimento", "difficulty_level": 1,
        "prompt": "Qual é a capital do Brasil?",
        "options": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
        "correct_answer": "Brasília",
        "explanation": "Brasília é a capital federal do Brasil desde 1960.",
        "age_reviewed": True,
        "hints": ["Não é a cidade mais populosa do país.", "Foi inaugurada em 1960."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 1,
        "prompt": "Qual é o maior oceano do mundo?",
        "options": ["Atlântico", "Pacífico", "Índico", "Ártico"],
        "correct_answer": "Pacífico",
        "explanation": "O Oceano Pacífico é o maior e mais profundo oceano do mundo.",
        "age_reviewed": True,
        "hints": ["Fica entre a Ásia e as Américas.", "Começa com 'P'."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 1,
        "prompt": "Em que país fica a Torre Eiffel?",
        "options": ["França", "Itália", "Espanha", "Alemanha"],
        "correct_answer": "França",
        "explanation": "A Torre Eiffel fica em Paris, capital da França.",
        "age_reviewed": True,
        "hints": ["É o mesmo país da cidade de Paris.", "Começa com 'F'."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 2,
        "prompt": "Quantos planetas existem no Sistema Solar?",
        "options": ["7", "8", "9", "10"],
        "correct_answer": "8",
        "explanation": "O Sistema Solar tem 8 planetas — Plutão foi reclassificado como planeta anão em 2006.",
        "age_reviewed": True,
        "hints": ["É menos do que 9.", "Termina em Netuno, não em Plutão."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 1,
        "prompt": "Qual é o maior país do mundo em área?",
        "options": ["Rússia", "China", "Canadá", "EUA"],
        "correct_answer": "Rússia",
        "explanation": "A Rússia é o maior país do mundo em área territorial.",
        "age_reviewed": True,
        "hints": ["Fica entre a Europa e a Ásia.", "Começa com 'R'."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 1,
        "prompt": "Em que continente fica o Egito?",
        "options": ["África", "Ásia", "Europa", "América"],
        "correct_answer": "África",
        "explanation": "O Egito fica no continente africano.",
        "age_reviewed": True,
        "hints": ["É o mesmo continente do deserto do Saara.", "Começa com 'Á'."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 2,
        "prompt": "Quem pintou a Mona Lisa?",
        "options": ["Leonardo da Vinci", "Picasso", "Van Gogh", "Michelangelo"],
        "correct_answer": "Leonardo da Vinci",
        "explanation": "A Mona Lisa foi pintada por Leonardo da Vinci, no século XVI.",
        "age_reviewed": True,
        "hints": ["Foi um artista e inventor renascentista italiano.", "Também pintou 'A Última Ceia'."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 2,
        "prompt": "Qual é o metal que é líquido à temperatura ambiente?",
        "options": ["Mercúrio", "Ferro", "Ouro", "Chumbo"],
        "correct_answer": "Mercúrio",
        "explanation": "O mercúrio é o único metal líquido à temperatura ambiente.",
        "age_reviewed": True,
        "hints": ["Era usado em termômetros antigos.", "Tem o mesmo nome de um planeta."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 2,
        "prompt": "Quantos ossos tem, aproximadamente, o corpo de um adulto?",
        "options": ["106", "206", "306", "406"],
        "correct_answer": "206",
        "explanation": "O esqueleto adulto humano tem cerca de 206 ossos.",
        "age_reviewed": True,
        "hints": ["É mais que 100 e menos que 300.", "Bebês nascem com mais ossos que isso."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 2,
        "prompt": "Qual é o idioma mais falado no mundo como língua nativa?",
        "options": ["Mandarim", "Inglês", "Espanhol", "Hindi"],
        "correct_answer": "Mandarim",
        "explanation": "O mandarim é o idioma com mais falantes nativos no mundo, principalmente na China.",
        "age_reviewed": True,
        "hints": ["É falado principalmente na China.", "Não usa alfabeto latino."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 3,
        "prompt": "Em que ano começou a Segunda Guerra Mundial?",
        "options": ["1935", "1939", "1941", "1945"],
        "correct_answer": "1939",
        "explanation": "A Segunda Guerra Mundial começou em 1939, com a invasão da Polônia.",
        "age_reviewed": True,
        "hints": ["Foi no final da década de 1930.", "Terminou em 1945."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 3,
        "prompt": "Qual é o elemento químico de símbolo 'O'?",
        "options": ["Ouro", "Oxigênio", "Ósmio", "Óxido"],
        "correct_answer": "Oxigênio",
        "explanation": "O símbolo químico 'O' representa o Oxigênio — o ouro é 'Au'.",
        "age_reviewed": True,
        "hints": ["É essencial para respirarmos.", "Não é o mesmo que o símbolo do ouro."],
    },
    {
        "territory_id": "conhecimento", "difficulty_level": 3,
        "prompt": "Qual é a moeda oficial do Japão?",
        "options": ["Won", "Yuan", "Iene", "Rupia"],
        "correct_answer": "Iene",
        "explanation": "O Iene é a moeda oficial do Japão.",
        "age_reviewed": True,
        "hints": ["Não é a moeda da China nem da Coreia.", "Começa com 'I'."],
    },
]


def seed_if_empty(db: Session) -> None:
    if db.query(models.Territory).count() > 0:
        return

    for t in TERRITORIES:
        db.add(models.Territory(**t))
    db.commit()

    for c in CHALLENGES:
        hints = c.pop("hints")
        challenge = models.Challenge(**c)
        db.add(challenge)
        db.commit()
        db.refresh(challenge)
        for level, content in enumerate(hints, start=1):
            db.add(models.ChallengeHint(challenge_id=challenge.id, hint_level=level, content=content))
        db.commit()

    for b in BADGES:
        db.add(models.Badge(**b))
    db.commit()
